; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov002
; Range:  0x022ccf9c..0x022cd220 (644 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern data_020ce340
        .extern data_020ce410
        .extern data_020ce570
        .extern data_020cec30
        .extern data_020cedc0
        .extern data_020cee70
        .extern data_020cef30
        .extern data_020cf010
        .extern data_020cf560
        .extern data_020cf5b0
        .extern data_020cf8e0
        .extern data_020cf9b0
        .extern data_020cfab0
        .extern data_020cfc30
        .extern data_020d03a0
        .extern data_020d0cf0
        .extern data_020d0d50
        .extern data_020d0da0
        .extern data_020d0e10
        .extern data_020d0e80
        .extern data_020d0ee0
        .extern data_020d1120
        .extern data_020d11c0
        .extern data_020d12c0
        .extern data_020d1b50
        .extern data_020d1bb0
        .extern data_020d1f00
        .extern data_020d1f50
        .extern data_020d1fd0
        .extern data_020d2040
        .extern data_020d20f0
        .extern data_020d21a0
        .extern data_020d2260
        .extern data_020d2310
        .extern data_020d23c0
        .extern data_020d2470
        .extern data_020d2530
        .extern data_020d25e0
        .extern data_020d26a0
        .extern data_020d27f0
        .extern data_020d2980
        .extern data_020d2aa0
        .extern data_020d2b50
        .extern data_020d2c00
        .extern data_020d2cb0
        .extern data_020d2d60
        .extern data_020d2e10
        .extern data_020d2ec0
        .extern data_020d2fc0
        .extern data_020d3120
        .extern data_020d35e0
        .extern data_020d3700
        .extern data_020d37c0
        .extern data_020d3880
        .extern data_020d38e0
        .extern data_020d4340
        .extern data_020d4410
        .extern data_020d4510
        .extern data_020d4620
        .extern data_020d4670
        .extern data_020d47a0
        .extern data_020d5030
        .extern data_020d5190
        .extern data_020d5bb0
        .extern data_020d5c10
        .extern data_020d5e20
        .extern data_020d5f60
        .extern data_020d60a0
        .extern data_020d61e0
        .extern data_020d6250
        .extern data_020d6370
        .extern data_020d6490
        .extern data_020e08a0
        .extern data_020d65b0
        .extern data_020e0c60
        .extern data_020d67a0

        .global data_ov002_022ccf9c
data_ov002_022ccf9c:
        .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        .word data_020ce340
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020ce410
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020ce570
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020cec30
        .byte 0x03, 0x00, 0x00, 0x00
        .word data_020cedc0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cee70
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cef30
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020cf010
        .byte 0x09, 0x00, 0x00, 0x00
        .word data_020cf560
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cf5b0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020cf8e0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cf9b0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020cfab0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cfc30
        .byte 0x06, 0x00, 0x00, 0x00
        .word data_020d03a0
        .byte 0x09, 0x00, 0x00, 0x00
        .word data_020d0cf0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0d50
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0da0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0e10
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0e80
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0ee0
        .byte 0x03, 0x00, 0x00, 0x00
        .word data_020d1120
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d11c0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d12c0
        .byte 0x0f, 0x00, 0x00, 0x00
        .word data_020d1b50
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d1bb0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d1f00
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d1f50
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d1fd0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2040
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d20f0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d21a0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2260
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2310
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d23c0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2470
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2530
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d25e0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d26a0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d27f0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2980
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2aa0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2b50
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2c00
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2cb0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2d60
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2e10
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2ec0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2fc0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d3120
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020d35e0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d3700
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d37c0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d3880
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d38e0
        .byte 0x08, 0x00, 0x00, 0x00
        .word data_020d4340
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d4410
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d4510
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d4620
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d4670
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d47a0
        .byte 0x0f, 0x00, 0x00, 0x00
        .word data_020d5030
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d5190
        .byte 0x09, 0x00, 0x00, 0x00
        .word data_020d5bb0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d5c10
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d5e20
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d5f60
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d60a0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d61e0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d6250
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d6370
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d6490
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020e08a0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d65b0
        .byte 0x06, 0x00, 0x00, 0x00
        .word data_020e0c60
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d67a0
        .byte 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
