/* Brief 170 cross-region cluster B true scalar.
 *
 * Generated by tools/cross_region_cluster_apply.py from
 * the region's own symbols.txt + orig bytes. Recipe per
 * brief 117: mwcc routes `int X = N;` to `.data`
 * automatically; no `__attribute__((section))` needed.
 */

int data_ov009_021ad938 = 0x7e0024;
