; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov007
; Range:  0x021b2fc0..0x021b3218 (600 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern func_ov002_021b2f78
        .extern data_020d20f0
        .extern data_ov007_021b3244
        .extern data_020d21a0
        .extern data_ov007_021b3254
        .extern data_ov007_021b2f82
        .extern data_ov007_021b2f94
        .extern data_ov007_021b2fae
        .extern data_020d2260
        .extern data_ov007_021b3358
        .extern data_020d2310
        .extern data_ov007_021b3274
        .extern data_020d23c0
        .extern data_ov007_021b3264
        .extern data_020d2470
        .extern data_ov007_021b3224
        .extern data_020d2530
        .extern func_ov002_021b3234
        .extern data_020d25e0
        .extern data_ov007_021b3284
        .extern data_ov007_021b2f88
        .extern data_ov007_021b2f9c
        .extern data_ov007_021b2fa4
        .extern data_020d26a0
        .extern data_ov007_021b331c
        .extern data_020d27f0
        .extern data_ov007_021b3330
        .extern data_020d2980
        .extern data_ov007_021b3344
        .extern data_020d2aa0
        .extern data_ov007_021b32f4
        .extern data_020d2b50
        .extern data_ov007_021b32a4
        .extern data_020d2c00
        .extern data_ov007_021b32cc
        .extern data_020d2cb0
        .extern data_ov007_021b32e0
        .extern data_020d2d60
        .extern data_ov007_021b3308
        .extern data_020d2e10
        .extern data_ov007_021b32b8
        .extern data_ov007_021b2f8e
        .extern data_ov007_021b2f7c
        .extern data_020d0e80
        .extern func_ov006_021b3218

        .global data_ov007_021b2fc0
data_ov007_021b2fc0:
        .byte 0x61, 0x00, 0x00, 0x00, 0x61, 0x00, 0x00, 0x00
        .byte 0x61, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d20f0
        .word data_ov007_021b3244
        .byte 0x64, 0x00, 0x00, 0x00, 0x63, 0x00, 0x00, 0x00
        .byte 0x62, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d21a0
        .word data_ov007_021b3254
        .byte 0x67, 0x00, 0x00, 0x00, 0x66, 0x00, 0x00, 0x00
        .byte 0x65, 0x00, 0x00, 0x00
        .word data_ov007_021b2f82
        .word data_ov007_021b2f94
        .word data_ov007_021b2fae
        .word data_020d2260
        .word data_ov007_021b3358
        .byte 0x68, 0x00, 0x00, 0x00, 0x68, 0x00, 0x00, 0x00
        .byte 0x68, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2310
        .word data_ov007_021b3274
        .byte 0x69, 0x00, 0x00, 0x00, 0x69, 0x00, 0x00, 0x00
        .byte 0x69, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d23c0
        .word data_ov007_021b3264
        .byte 0x6a, 0x00, 0x00, 0x00, 0x6a, 0x00, 0x00, 0x00
        .byte 0x6a, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2470
        .word data_ov007_021b3224
        .byte 0x6b, 0x00, 0x00, 0x00, 0x6b, 0x00, 0x00, 0x00
        .byte 0x6b, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2530
        .word func_ov002_021b3234
        .byte 0x6c, 0x00, 0x00, 0x00, 0x6c, 0x00, 0x00, 0x00
        .byte 0x6c, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d25e0
        .word data_ov007_021b3284
        .byte 0x6f, 0x00, 0x00, 0x00, 0x6e, 0x00, 0x00, 0x00
        .byte 0x6d, 0x00, 0x00, 0x00
        .word data_ov007_021b2f88
        .word data_ov007_021b2f9c
        .word data_ov007_021b2fa4
        .word data_020d26a0
        .word data_ov007_021b331c
        .byte 0x72, 0x00, 0x00, 0x00, 0x71, 0x00, 0x00, 0x00
        .byte 0x70, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d27f0
        .word data_ov007_021b3330
        .byte 0x75, 0x00, 0x00, 0x00, 0x74, 0x00, 0x00, 0x00
        .byte 0x73, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2980
        .word data_ov007_021b3344
        .byte 0x78, 0x00, 0x00, 0x00, 0x77, 0x00, 0x00, 0x00
        .byte 0x76, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2aa0
        .word data_ov007_021b32f4
        .byte 0x7b, 0x00, 0x00, 0x00, 0x7a, 0x00, 0x00, 0x00
        .byte 0x79, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2b50
        .word data_ov007_021b32a4
        .byte 0x7e, 0x00, 0x00, 0x00, 0x7d, 0x00, 0x00, 0x00
        .byte 0x7c, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2c00
        .word data_ov007_021b32cc
        .byte 0x7f, 0x00, 0x00, 0x00, 0x7f, 0x00, 0x00, 0x00
        .byte 0x7f, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2cb0
        .word data_ov007_021b32e0
        .byte 0x80, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00
        .byte 0x80, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2d60
        .word data_ov007_021b3308
        .byte 0x81, 0x00, 0x00, 0x00, 0x81, 0x00, 0x00, 0x00
        .byte 0x81, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word data_020d2e10
        .word data_ov007_021b32b8
        .byte 0x82, 0x00, 0x00, 0x00, 0x82, 0x00, 0x00, 0x00
        .byte 0x82, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word data_ov007_021b2f8e
        .word data_ov007_021b2f7c
        .word data_020d0e80
        .word func_ov006_021b3218
        .byte 0x31, 0x00, 0x00, 0x00, 0x31, 0x00, 0x00, 0x00
        .byte 0x31, 0x00, 0x00, 0x00
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
        .word func_ov002_021b2f78
