; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020f8c60..0x020f8fc8 (872 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern data_020f8fc8
        .extern data_020f90e0
        .extern data_020f9108
        .extern data_020f9130
        .extern data_020f917c
        .extern data_020f91a4
        .extern data_020f91d4
        .extern data_020f9204
        .extern data_020f9234
        .extern data_020f9264
        .extern data_020f9294
        .extern data_020f92c4
        .extern data_020f92f4
        .extern data_020f9324
        .extern data_020f9354
        .extern data_020f9384
        .extern data_020f93b4
        .extern data_020f93e4
        .extern data_020f9414
        .extern data_020f9444
        .extern data_020f9474
        .extern data_020f94a4
        .extern data_020f94d4
        .extern data_020f9504
        .extern data_020f9534
        .extern data_020f9564
        .extern data_020f9594
        .extern data_020f95c4
        .extern data_020f95f4
        .extern data_020f9624
        .extern data_020f9654
        .extern data_020f9684
        .extern data_020f96b4
        .extern data_020f96e4
        .extern data_020f9714
        .extern data_020f9744
        .extern data_020f9774
        .extern data_020f97a4
        .extern data_020f97d4
        .extern data_020f9804
        .extern data_020f9834
        .extern data_020f9864
        .extern data_020f9894
        .extern data_020f98c4
        .extern data_020f9ab4
        .extern data_020f9b48
        .extern data_020f9d54
        .extern data_020f9d68
        .extern data_020f9d7c
        .extern data_020f9d90
        .extern data_020f9da4
        .extern data_020f9db8
        .extern data_020f9dcc
        .extern data_020f9de0
        .extern data_020f9df4
        .extern data_020f9e8c
        .extern data_020f9ea8
        .extern data_020f9ec4
        .extern data_020f9ee0
        .extern data_020f9efc
        .extern data_020f9f18
        .extern data_020f9f34
        .extern data_020f9f50
        .extern data_020f9bb0

        .global data_020f8c60
data_020f8c60:
        .byte 0x00, 0x00, 0x00, 0xf1
        .word data_020f8fc8
        .byte 0x04, 0x00, 0x00, 0x00
        .word data_020f90e0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9108
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9130
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f917c
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f91a4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f91d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9204
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9234
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9264
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9294
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f92c4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f92f4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9324
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9354
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9384
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f93b4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f93e4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9414
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9444
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9474
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f94a4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f94d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9504
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9534
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9564
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9594
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f95c4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f95f4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9624
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9654
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9684
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f96b4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f96e4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9714
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9744
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9774
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f97a4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f97d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9804
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9834
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9864
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9894
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f98c4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ab4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9b48
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9b48
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9d54
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9d68
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9d7c
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9d90
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9da4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9db8
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9dcc
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9de0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9df4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e8c
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ea8
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ec4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ee0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9efc
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f18
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f34
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9f50
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9bb0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9bb0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9bb0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9bb0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9bb0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9bb0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9bb0
        .byte 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0
