; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020bec3c..0x020bec58 (28 bytes, 3 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .rodata

        .global data_020bec3c
data_020bec3c:
        .byte 0x57, 0x61, 0x79, 0x70, 0x6f, 0x72, 0x74, 0x32

        .global data_020bec44
data_020bec44:
        .byte 0x46, 0x52, 0x45, 0x45, 0x53, 0x50, 0x4f, 0x54

        .global data_020bec4c
data_020bec4c:
        .ascii "NINTENDOWFC"
        .byte 0x00
