; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020c4204..0x020c44c4 (704 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern func_02001540
        .extern data_020c3fb8
        .extern func_0200ac2c
        .extern data_020c4158
        .extern func_ov004_021cb518
        .extern data_020c4178
        .extern func_02012cc8
        .extern data_020c41c8
        .extern func_0201261c
        .extern data_020c3fe4
        .extern data_ov000_021b2280
        .extern data_020c4050
        .extern data_ov000_021b2e58
        .extern data_020c4068
        .extern data_ov000_021b343c
        .extern data_020c40d8
        .extern data_ov000_021b3a1c
        .extern data_020c4188
        .extern data_ov000_021b3f88
        .extern data_020c40e8
        .extern data_ov000_021b49b4
        .extern data_020c4074
        .extern data_ov000_021b4f20
        .extern data_020c40f8
        .extern func_ov001_021ca2f8
        .extern data_020c3fa8
        .extern func_0200aa00
        .extern data_020c4198
        .extern data_ov006_021d0afc
        .extern data_020c3fd0
        .extern data_ov006_021cc01c
        .extern data_020c3ffc
        .extern data_ov006_021cb700
        .extern data_020c4044
        .extern data_ov006_021d0b4c
        .extern data_020c4080
        .extern func_ov008_021aafa4
        .extern data_020c408c
        .extern data_ov000_021b4014
        .extern data_020c4138
        .extern data_ov000_021b4028
        .extern data_020c4098
        .extern data_ov000_021b5a14
        .extern data_020c3fb0
        .extern data_ov000_021b5a64
        .extern data_020c4020
        .extern func_ov009_021ad7d4
        .extern data_020c402c
        .extern func_ov000_021ace14
        .extern data_020c3fd8
        .extern func_ov000_021aa4a0
        .extern data_020c4038
        .extern func_ov022_021ab460
        .extern data_020c4168
        .extern data_ov000_021b26d0
        .extern data_020c41dc
        .extern data_ov000_021b26ec
        .extern data_020c405c
        .extern data_ov009_021ada1c
        .extern data_020c3ff0
        .extern data_ov009_021ada6c
        .extern data_020c41f0
        .extern data_ov000_021b2824
        .extern data_020c4108
        .extern data_ov000_021b2c8c
        .extern data_020c4118
        .extern data_020c41b8
        .extern func_ov004_021d6ed0
        .extern data_020c4014
        .extern func_ov004_021dba08
        .extern data_020c4008
        .extern func_0200ac3c
        .extern data_020c40a8
        .extern data_ov000_021b5614
        .extern data_020c4148
        .extern func_0200aae4
        .extern data_020c40c8
        .extern func_0200ab6c
        .extern data_020c3fc8
        .extern func_0200ab28
        .extern data_020c3fc0
        .extern func_0200abb0
        .extern data_020c41a8
        .extern func_0200ac24
        .extern data_020c4128
        .extern func_0200aa08
        .extern data_020c40b8

        .global data_020c4204
data_020c4204:
        .word func_02001540
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c3fb8
        .word func_0200ac2c
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c4158
        .word func_ov004_021cb518
        .byte 0x04, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c4178
        .word func_02012cc8
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c41c8
        .word func_0201261c
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c3fe4
        .word data_ov000_021b2280
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c4050
        .word data_ov000_021b2e58
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c4068
        .word data_ov000_021b343c
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c40d8
        .word data_ov000_021b3a1c
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c4188
        .word data_ov000_021b3f88
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c40e8
        .word data_ov000_021b49b4
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c4074
        .word data_ov000_021b4f20
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c40f8
        .word func_ov001_021ca2f8
        .byte 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c3fa8
        .word func_0200aa00
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c4198
        .word data_ov006_021d0afc
        .byte 0x0b, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c3fd0
        .word data_ov006_021cc01c
        .byte 0x0c, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c3ffc
        .word data_ov006_021cb700
        .byte 0x0d, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c4044
        .word data_ov006_021d0b4c
        .byte 0x0b, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c4080
        .word func_ov008_021aafa4
        .byte 0x08, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff
        .word data_020c408c
        .word data_ov000_021b4014
        .byte 0x05, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00
        .word data_020c4138
        .word data_ov000_021b4028
        .byte 0x05, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00
        .word data_020c4098
        .word data_ov000_021b5a14
        .byte 0x05, 0x00, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00
        .word data_020c3fb0
        .word data_ov000_021b5a64
        .byte 0x05, 0x00, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00
        .word data_020c4020
        .word func_ov009_021ad7d4
        .byte 0x09, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff
        .word data_020c402c
        .word func_ov000_021ace14
        .byte 0x12, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff
        .word data_020c3fd8
        .word func_ov000_021aa4a0
        .byte 0x15, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff
        .word data_020c4038
        .word func_ov022_021ab460
        .byte 0x16, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff
        .word data_020c4168
        .word data_ov000_021b26d0
        .byte 0x05, 0x00, 0x00, 0x00, 0x13, 0x00, 0x00, 0x00
        .word data_020c41dc
        .word data_ov000_021b26ec
        .byte 0x05, 0x00, 0x00, 0x00, 0x0e, 0x00, 0x00, 0x00
        .word data_020c405c
        .word data_ov009_021ada1c
        .byte 0x14, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff
        .word data_020c3ff0
        .word data_ov009_021ada6c
        .byte 0x14, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff
        .word data_020c41f0
        .word data_ov000_021b2824
        .byte 0x05, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00
        .word data_020c4108
        .word data_ov000_021b2c8c
        .byte 0x05, 0x00, 0x00, 0x00, 0x11, 0x00, 0x00, 0x00
        .word data_020c4118
        .word data_ov000_021b2280
        .byte 0x05, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00
        .word data_020c41b8
        .word func_ov004_021d6ed0
        .byte 0x04, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c4014
        .word func_ov004_021dba08
        .byte 0x04, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00
        .word data_020c4008
        .word func_0200ac3c
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c40a8
        .word data_ov000_021b5614
        .byte 0x05, 0x00, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00
        .word data_020c4148
        .word func_0200aae4
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c40c8
        .word func_0200ab6c
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c3fc8
        .word func_0200ab28
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c3fc0
        .word func_0200abb0
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c41a8
        .word func_0200ac24
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c4128
        .word func_0200aa08
        .byte 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        .word data_020c40b8
