; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020c3188..0x020c3198 (16 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .rodata

        .global data_020c3188
data_020c3188:
        .byte 0x00, 0x00, 0x80, 0x68, 0x90, 0x68, 0x80, 0x68
        .byte 0x94, 0x68, 0x00, 0x00, 0x90, 0x68, 0x80, 0x68
