; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020b46e0..0x020b4728 (72 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .rodata

        .extern data_020c3ca8
        .extern data_020c3cb0
        .extern data_020c3cb8
        .extern data_020c3cc0
        .extern data_020c3cf4
        .extern data_020c3d00
        .extern data_020c3d0c
        .extern data_020c3d18
        .extern data_020c3d24
        .extern data_020c3d30
        .extern data_020c3d3c
        .extern data_020c3d48
        .extern data_020c3d54
        .extern data_020c3d60
        .extern data_020c3d6c
        .extern data_020c3d78
        .extern data_020c3d84
        .extern data_020c3d90

        .global data_020b46e0
data_020b46e0:
        .word data_020c3d00
        .word data_020c3d24
        .word data_020c3d0c
        .word data_020c3d60
        .word data_020c3cf4
        .word data_020c3d18
        .word data_020c3d30
        .word data_020c3d54
        .word data_020c3d48
        .word data_020c3d3c
        .word data_020c3d6c
        .word data_020c3ca8
        .word data_020c3d78
        .word data_020c3cb0
        .word data_020c3d84
        .word data_020c3cb8
        .word data_020c3d90
        .word data_020c3cc0
