; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020beb58..0x020beb8c (52 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .rodata

        .extern func_02033de8
        .extern func_02033f10
        .extern func_02033f28
        .extern func_02033f40
        .extern func_02033fb0
        .extern func_02034014
        .extern func_0203402c
        .extern func_02034054
        .extern func_02034094
        .extern func_020340b8
        .extern func_020340d0
        .extern func_020340e0
        .extern func_0203410c

        .global data_020beb58
data_020beb58:
        .word func_02033de8
        .word func_02033f10
        .word func_02033f28
        .word func_02033f40
        .word func_02033fb0
        .word func_02034014
        .word func_0203402c
        .word func_02034054
        .word func_02034094
        .word func_020340b8
        .word func_020340d0
        .word func_020340e0
        .word func_0203410c
