; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020b5ab8..0x020b5b80 (200 bytes, 3 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .rodata

        .extern data_020c59d8
        .extern data_020c59dc
        .extern data_020c59e0
        .extern data_020c59e4
        .extern data_020c59e8
        .extern data_020c5a48
        .extern data_020c5a90
        .extern data_020c5aa0
        .extern data_020c5ab8
        .extern data_020c5ac0
        .extern data_020c5ac8
        .extern data_020c5ad0
        .extern data_020c5ad8
        .extern data_020c5ae0
        .extern data_020c5ae8
        .extern data_020c5af0
        .extern data_020c5af8
        .extern data_020c5b00
        .extern data_020c5b08
        .extern data_020c5b10
        .extern data_020c5b18
        .extern data_020c5b24
        .extern data_020c5b48
        .extern data_020c5b60
        .extern data_020c5b6c
        .extern data_020c5b84
        .extern data_020c5b90
        .extern data_020c5b9c
        .extern data_020c5ba8
        .extern data_020c5bb8
        .extern data_020c5bc8
        .extern data_020c5bd8
        .extern data_020c5be8
        .extern data_020c5bfc
        .extern data_020c5c10
        .extern data_020c5c24
        .extern data_020c5c38
        .extern data_020c5c4c
        .extern data_020c5c64

        .global data_020b5ab8
data_020b5ab8:
        .word data_020c59e0
        .word data_020c59e8
        .word data_020c5a90
        .word data_020c5aa0
        .word data_020c59d8
        .word data_020c5ae0
        .word data_020c5af0
        .word data_020c5af8
        .word data_020c5b00
        .word data_020c5b08
        .word data_020c5b10
        .word data_020c5ad8

        .global data_020b5ae8
data_020b5ae8:
        .word data_020c5ab8
        .word data_020c5b84
        .word data_020c5bb8
        .word data_020c5be8
        .word data_020c5b24
        .word data_020c5c4c
        .word data_020c5bc8
        .word data_020c5ac8
        .word data_020c5c64
        .word data_020c5bfc
        .word data_020c5bd8
        .word data_020c5b90
        .word data_020c5b9c
        .word data_020c5c10
        .word data_020c5c24
        .word data_020c5b6c
        .word data_020c5ba8
        .word data_020c5c38

        .global data_020b5b30
data_020b5b30:
        .word data_020c5ae8
        .word data_020c59e8
        .word data_020c5ac0
        .word data_020c5b18
        .word data_020c5a48
        .word data_020c59e4
        .word data_020c59d8
        .word data_020c5b48
        .word data_020c5b60
        .word data_020c5ad0
        .word data_020c5ae8
        .word data_020c59e8
        .word data_020c5ac0
        .word data_020c5b18
        .word data_020c5a48
        .word data_020c59e4
        .word data_020c59dc
        .word data_020c5b48
        .word data_020c5b60
        .word data_020c5ad0
