"""Unit tests for tools/ci_format_diff_reasons.py.

Regressions in this renderer would spam PR comments (once CI is
wired) with wrong alarm signals — the "N regressions" headline is
load-bearing for decomper and brain attention. Pins:

  - extract_snapshot: (unit, name) keying; defensive parsing
  - compute_delta: regression / improvement / new / dropped / stable
    classification; bucket counts and transition matrix correctness
  - Movement properties: is_regression, is_improvement, pct_delta,
    is_new, is_dropped all behave at the boundary cases
  - render_markdown: empty diff / regression headline / improvement
    headline / dropped-entries section / footer marker
  - render_json: schema integrity, round-trip
  - main() is robust to non-UTF-8 stdout (same guard as the
    worklist-diff tool)
"""

from __future__ import annotations

import contextlib
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

_TOOLS = Path(__file__).resolve().parent.parent / "tools"
sys.path.insert(0, str(_TOOLS))

from ci_format_diff_reasons import (  # noqa: E402
    Movement,
    SnapshotEntry,
    compute_delta,
    extract_snapshot,
    render_json,
    render_markdown,
)
from diff_reasons import (  # noqa: E402
    BUCKET_CLOSE,
    BUCKET_LOW,
    BUCKET_MATCHED,
    BUCKET_MEDIUM,
    BUCKET_ZERO,
)


FOOTER_MARKER = (
    "<sub>🤖 Generated by `tools/ci_format_diff_reasons.py`"
)


def _fn(name: str, pct: float, size: int = 0x10) -> dict:
    return {
        "name": name,
        "size": size,
        "fuzzy_match_percent": pct,
    }


def _report(units: list[tuple[str, list[dict]]]) -> dict:
    return {
        "version": 2,
        "units": [{"name": u, "functions": fns} for u, fns in units],
    }


def _entry(unit: str, name: str, pct: float, size: int = 0x10) -> SnapshotEntry:
    return SnapshotEntry(
        unit=unit, name=name, size=size, fuzzy_match_percent=pct,
    )


# ------------------------------------------------------------------------- #
# extract_snapshot
# ------------------------------------------------------------------------- #


class TestExtractSnapshot(unittest.TestCase):
    def test_empty(self):
        self.assertEqual(extract_snapshot({}), {})

    def test_basic_shape(self):
        r = _report([("ov005.c", [_fn("fn", 75.0)])])
        snap = extract_snapshot(r)
        self.assertEqual(len(snap), 1)
        e = snap[("ov005.c", "fn")]
        self.assertEqual(e.fuzzy_match_percent, 75.0)
        self.assertEqual(e.bucket, BUCKET_CLOSE)

    def test_missing_fuzzy_defaults_to_zero(self):
        r = {"units": [{"name": "u", "functions": [{"name": "fn", "size": 4}]}]}
        snap = extract_snapshot(r)
        self.assertEqual(snap[("u", "fn")].fuzzy_match_percent, 0.0)
        self.assertEqual(snap[("u", "fn")].bucket, BUCKET_ZERO)

    def test_null_fuzzy_treated_as_zero(self):
        r = _report([("u", [{"name": "fn", "size": 4,
                             "fuzzy_match_percent": None}])])
        self.assertEqual(
            extract_snapshot(r)[("u", "fn")].fuzzy_match_percent, 0.0,
        )

    def test_duplicate_name_last_wins(self):
        # Two functions with the same (unit, name) — last one wins.
        # Doesn't happen in practice but documenting the behaviour.
        r = _report([
            ("u", [_fn("fn", 50.0), _fn("fn", 90.0)]),
        ])
        snap = extract_snapshot(r)
        self.assertEqual(
            snap[("u", "fn")].fuzzy_match_percent, 90.0,
        )


# ------------------------------------------------------------------------- #
# compute_delta
# ------------------------------------------------------------------------- #


class TestComputeDelta(unittest.TestCase):
    def test_identity_no_movements(self):
        snap = {
            ("u", "fn"): _entry("u", "fn", 100.0),
        }
        delta = compute_delta(snap, dict(snap))
        self.assertEqual(delta.movements, [])
        self.assertEqual(delta.regressions, [])
        self.assertEqual(delta.improvements, [])
        self.assertEqual(delta.new_entries, [])
        self.assertEqual(delta.dropped_entries, [])

    def test_regression_flagged(self):
        # matched → close = regression.
        before = {("u", "fn"): _entry("u", "fn", 100.0)}
        after = {("u", "fn"): _entry("u", "fn", 80.0)}
        delta = compute_delta(before, after)
        self.assertEqual(len(delta.regressions), 1)
        reg = delta.regressions[0]
        self.assertEqual(reg.bucket_before, BUCKET_MATCHED)
        self.assertEqual(reg.bucket_after, BUCKET_CLOSE)
        self.assertAlmostEqual(reg.pct_delta, -20.0)

    def test_improvement_flagged(self):
        before = {("u", "fn"): _entry("u", "fn", 50.0)}
        after = {("u", "fn"): _entry("u", "fn", 100.0)}
        delta = compute_delta(before, after)
        self.assertEqual(len(delta.improvements), 1)
        imp = delta.improvements[0]
        self.assertEqual(imp.bucket_before, BUCKET_MEDIUM)
        self.assertEqual(imp.bucket_after, BUCKET_MATCHED)

    def test_same_bucket_pct_change_not_regression(self):
        # 98% → 96% stays in the ALMOST bucket. It's technically a
        # small backslide but doesn't change the bucket, so it's
        # neither flagged as regression nor improvement. The raw
        # movement IS recorded though, for the JSON delta.
        before = {("u", "fn"): _entry("u", "fn", 98.0)}
        after = {("u", "fn"): _entry("u", "fn", 96.0)}
        delta = compute_delta(before, after)
        self.assertEqual(delta.regressions, [])
        self.assertEqual(delta.improvements, [])
        # But the pct change was captured:
        self.assertEqual(len(delta.movements), 1)
        self.assertAlmostEqual(delta.movements[0].pct_delta, -2.0)

    def test_new_entry(self):
        before = {}
        after = {("u", "fn"): _entry("u", "fn", 50.0)}
        delta = compute_delta(before, after)
        self.assertEqual(len(delta.new_entries), 1)
        self.assertEqual(delta.new_entries[0].name, "fn")
        self.assertEqual(delta.regressions, [])

    def test_dropped_entry(self):
        before = {("u", "fn"): _entry("u", "fn", 100.0)}
        after = {}
        delta = compute_delta(before, after)
        self.assertEqual(len(delta.dropped_entries), 1)
        self.assertEqual(delta.dropped_entries[0].name, "fn")
        # A dropped entry is NOT counted as a regression (it's
        # renamed/removed, distinct class of event).
        self.assertEqual(delta.regressions, [])

    def test_bucket_counts_correct(self):
        before = {
            ("u", "a"): _entry("u", "a", 100.0),
            ("u", "b"): _entry("u", "b", 50.0),
            ("u", "c"): _entry("u", "c", 10.0),
        }
        after = {
            ("u", "a"): _entry("u", "a", 100.0),
            ("u", "b"): _entry("u", "b", 100.0),   # improvement
            ("u", "c"): _entry("u", "c", 10.0),
        }
        delta = compute_delta(before, after)
        self.assertEqual(delta.bucket_counts_before[BUCKET_MATCHED], 1)
        self.assertEqual(delta.bucket_counts_before[BUCKET_MEDIUM], 1)
        self.assertEqual(delta.bucket_counts_before[BUCKET_LOW], 1)
        self.assertEqual(delta.bucket_counts_after[BUCKET_MATCHED], 2)
        self.assertEqual(delta.bucket_counts_after[BUCKET_MEDIUM], 0)
        self.assertEqual(delta.bucket_counts_after[BUCKET_LOW], 1)

    def test_transitions_matrix(self):
        before = {
            ("u", "a"): _entry("u", "a", 100.0),  # matched
            ("u", "b"): _entry("u", "b", 100.0),  # matched
            ("u", "c"): _entry("u", "c", 50.0),   # medium
        }
        after = {
            ("u", "a"): _entry("u", "a", 100.0),   # matched → matched
            ("u", "b"): _entry("u", "b", 80.0),    # matched → close
            ("u", "c"): _entry("u", "c", 100.0),    # medium → matched
        }
        delta = compute_delta(before, after)
        # matched → matched: 1
        self.assertEqual(delta.transitions[BUCKET_MATCHED][BUCKET_MATCHED], 1)
        # matched → close: 1
        self.assertEqual(delta.transitions[BUCKET_MATCHED][BUCKET_CLOSE], 1)
        # medium → matched: 1
        self.assertEqual(delta.transitions[BUCKET_MEDIUM][BUCKET_MATCHED], 1)


# ------------------------------------------------------------------------- #
# Movement properties
# ------------------------------------------------------------------------- #


class TestMovement(unittest.TestCase):
    def test_is_regression_by_depth(self):
        m = Movement(
            entry_before=_entry("u", "fn", 100.0),
            entry_after=_entry("u", "fn", 80.0),
        )
        self.assertTrue(m.is_regression)
        self.assertFalse(m.is_improvement)

    def test_is_improvement_by_depth(self):
        m = Movement(
            entry_before=_entry("u", "fn", 80.0),
            entry_after=_entry("u", "fn", 100.0),
        )
        self.assertTrue(m.is_improvement)
        self.assertFalse(m.is_regression)

    def test_new_is_neither(self):
        m = Movement(entry_before=None, entry_after=_entry("u", "fn", 50.0))
        self.assertTrue(m.is_new)
        self.assertFalse(m.is_regression)
        self.assertFalse(m.is_improvement)

    def test_dropped_is_neither(self):
        m = Movement(entry_before=_entry("u", "fn", 50.0), entry_after=None)
        self.assertTrue(m.is_dropped)
        self.assertFalse(m.is_regression)

    def test_pct_delta_none_when_either_missing(self):
        m = Movement(entry_before=None, entry_after=_entry("u", "fn", 50.0))
        self.assertIsNone(m.pct_delta)

    def test_pct_delta_correct(self):
        m = Movement(
            entry_before=_entry("u", "fn", 60.0),
            entry_after=_entry("u", "fn", 85.0),
        )
        self.assertAlmostEqual(m.pct_delta, 25.0)


# ------------------------------------------------------------------------- #
# render_markdown
# ------------------------------------------------------------------------- #


class TestRenderMarkdown(unittest.TestCase):
    def test_empty_delta_no_movements(self):
        # Identity diff: same snapshots both sides, nothing moves.
        delta = compute_delta({}, {})
        md = render_markdown(delta)
        self.assertIn("No bucket movements", md)
        self.assertIn(FOOTER_MARKER, md)

    def test_regression_headline_renders(self):
        before = {("u", "fn"): _entry("u", "fn", 100.0)}
        after = {("u", "fn"): _entry("u", "fn", 30.0)}
        delta = compute_delta(before, after)
        md = render_markdown(delta)
        self.assertIn("🛑 **1 regression(s)**", md)
        self.assertIn("### 🛑 Regressions (1)", md)
        self.assertIn("`fn`", md)
        self.assertIn("matched", md)
        self.assertIn("medium", md)
        self.assertIn("-70.00pp", md)

    def test_improvement_section(self):
        before = {("u", "fn"): _entry("u", "fn", 50.0)}
        after = {("u", "fn"): _entry("u", "fn", 100.0)}
        delta = compute_delta(before, after)
        md = render_markdown(delta)
        self.assertIn("✅ **1 improvement(s)**", md)
        self.assertIn("### ✅ Improvements (1)", md)
        self.assertIn("+50.00pp", md)

    def test_dropped_section_warns_about_footgun(self):
        before = {("u", "fn"): _entry("u", "fn", 100.0)}
        after = {}
        delta = compute_delta(before, after)
        md = render_markdown(delta)
        self.assertIn("🗑️ Dropped entries", md)
        # The surface warning about symbol renames is load-bearing —
        # it points at the exact class of bug that happens easily.
        self.assertIn("rename-breaks-everything", md)

    def test_new_section_surfaces(self):
        before = {}
        after = {("u", "fn"): _entry("u", "fn", 50.0)}
        delta = compute_delta(before, after)
        md = render_markdown(delta)
        self.assertIn("🆕 New entries", md)
        self.assertIn("`fn`", md)

    def test_top_n_truncation(self):
        # 30 regressions, top_n=5 → only 5 shown with truncation note.
        before = {
            ("u", f"fn_{i}"): _entry("u", f"fn_{i}", 100.0)
            for i in range(30)
        }
        after = {
            ("u", f"fn_{i}"): _entry("u", f"fn_{i}", 10.0)
            for i in range(30)
        }
        delta = compute_delta(before, after)
        md = render_markdown(delta, top_n=5)
        self.assertIn("### 🛑 Regressions (30)", md)
        self.assertIn("and 25 more regressions", md)

    def test_footer_always_present(self):
        for (before, after) in [
            ({}, {}),
            ({("u", "f"): _entry("u", "f", 100.0)}, {}),
            ({}, {("u", "f"): _entry("u", "f", 100.0)}),
        ]:
            md = render_markdown(compute_delta(before, after))
            self.assertIn(FOOTER_MARKER, md)


# ------------------------------------------------------------------------- #
# render_json
# ------------------------------------------------------------------------- #


class TestRenderJson(unittest.TestCase):
    def test_schema(self):
        before = {("u", "fn_reg"): _entry("u", "fn_reg", 100.0)}
        after = {
            ("u", "fn_reg"): _entry("u", "fn_reg", 80.0),
            ("u", "fn_new"): _entry("u", "fn_new", 50.0),
        }
        delta = compute_delta(before, after)
        payload = render_json(delta)
        # Round-trip.
        json.dumps(payload)
        self.assertIn("bucket_counts_before", payload)
        self.assertIn("bucket_counts_after", payload)
        self.assertIn("transitions", payload)
        self.assertIn("regressions", payload)
        self.assertIn("improvements", payload)
        self.assertIn("new", payload)
        self.assertIn("dropped", payload)
        self.assertEqual(len(payload["regressions"]), 1)
        self.assertEqual(len(payload["new"]), 1)
        self.assertEqual(payload["regressions"][0]["before"]["bucket"],
                         BUCKET_MATCHED)
        self.assertEqual(payload["regressions"][0]["after"]["bucket"],
                         BUCKET_CLOSE)


# ------------------------------------------------------------------------- #
# main() — UTF-8 guard + missing-file behaviour
# ------------------------------------------------------------------------- #


class TestMainUtf8Stdout(unittest.TestCase):
    """Same guard as the worklist-diff tool (PR #95). Emoji headers
    (📉 🛑 ✅ 🆕 🗑️) would crash on a Windows cp1252 console without
    the reconfigure."""

    def test_main_with_cp1252_stdout_does_not_crash(self):
        from ci_format_diff_reasons import main
        with tempfile.TemporaryDirectory() as td:
            before = Path(td) / "b.json"
            after = Path(td) / "a.json"
            before.write_text(json.dumps(
                _report([("u", [_fn("fn", 100.0)])])
            ))
            after.write_text(json.dumps(
                _report([("u", [_fn("fn", 50.0)])])
            ))
            buf = io.BytesIO()
            ascii_stdout = io.TextIOWrapper(
                buf, encoding="cp1252", errors="strict",
                write_through=True,
            )
            argv = [
                "ci_format_diff_reasons.py",
                str(before), str(after),
            ]
            with patch.object(sys, "argv", argv), \
                 contextlib.redirect_stdout(ascii_stdout):
                rc = main()
            ascii_stdout.flush()
            self.assertEqual(rc, 0)
            # Output contains utf-8-encoded emoji bytes.
            self.assertIn(b"\xf0\x9f\x93\x89", buf.getvalue())  # 📉

    def test_main_missing_before_renders_warning(self):
        from ci_format_diff_reasons import main
        with tempfile.TemporaryDirectory() as td:
            after = Path(td) / "a.json"
            after.write_text(json.dumps(
                _report([("u", [_fn("fn", 100.0)])])
            ))
            buf = io.StringIO()
            argv = [
                "ci_format_diff_reasons.py",
                str(Path(td) / "missing.json"), str(after),
            ]
            with patch.object(sys, "argv", argv), \
                 contextlib.redirect_stdout(buf):
                rc = main()
            self.assertEqual(rc, 0)
            out = buf.getvalue()
            self.assertIn("Snapshot missing", out)
            # The after snapshot's fn shows up as "new" when before
            # is empty — sanity check the fallback rendering.
            self.assertIn("`fn`", out)


if __name__ == "__main__":
    unittest.main()
