"""Unit tests for tools/ci_format_worklist_diff.py.

The CI comment pipeline pipes render() output straight into `gh pr
comment`. Regressions here would spam every decomp PR with malformed
markdown. Pinning:

  - JSON loader tolerates malformed rows + parses hex addrs
  - compute_diff: landed / new / migrations classified correctly
    by (module, addr) identity
  - Sorting is deterministic (tier rank → size → addr)
  - render() covers: no-changes case, mixed case, per-section
    limit truncation, tier-summary bold-on-nonzero, footer marker
  - main() is robust to non-UTF-8 stdout (Windows cp1252 consoles)
"""

from __future__ import annotations

import io
import json
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import patch

_TOOLS = Path(__file__).resolve().parent.parent / "tools"
sys.path.insert(0, str(_TOOLS))

from ci_format_worklist_diff import (  # noqa: E402
    TIER_ORDER,
    WorklistDiff,
    WorklistEntry,
    _entry_sort_key,
    _load_breakdown,
    _load_entries,
    _parse_addr,
    _signed,
    _tier_rank,
    compute_diff,
    render,
)


FOOTER_MARKER = (
    "<sub>🤖 Generated by `tools/ci_format_worklist_diff.py`"
)


def _entry(module: str, addr: int, **kwargs) -> WorklistEntry:
    return WorklistEntry(
        tier=kwargs.get("tier", "easy"),
        module=module,
        addr=addr,
        size=kwargs.get("size", 0x10),
        name=kwargs.get("name", f"func_{module}_{addr:08x}"),
    )


def _write_snapshot(path: Path, worklist: list[dict],
                    breakdown: dict | None = None) -> None:
    payload = {
        "version": "eur",
        "tier_breakdown": breakdown or {},
        "worklist": worklist,
    }
    path.write_text(json.dumps(payload))


# ------------------------------------------------------------------------- #


class TestParseAddr(unittest.TestCase):
    def test_hex_string(self):
        self.assertEqual(_parse_addr("0x100"), 0x100)
        self.assertEqual(_parse_addr("0X021aa4a0"), 0x021aa4a0)

    def test_int(self):
        self.assertEqual(_parse_addr(256), 256)

    def test_garbage_returns_none(self):
        self.assertIsNone(_parse_addr("not_a_number"))
        self.assertIsNone(_parse_addr(None))
        self.assertIsNone(_parse_addr([]))


class TestLoadEntries(unittest.TestCase):
    def test_roundtrip(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "snap.json"
            _write_snapshot(p, [
                {"tier": "easy", "module": "ov006",
                 "addr": "0x021ba1f0", "size": 8, "name": "x"},
            ])
            entries = _load_entries(p)
        self.assertIn(("ov006", 0x021ba1f0), entries)
        e = entries[("ov006", 0x021ba1f0)]
        self.assertEqual(e.tier, "easy")
        self.assertEqual(e.size, 8)
        self.assertEqual(e.name, "x")

    def test_missing_file_returns_empty(self):
        self.assertEqual(_load_entries(Path("/nonexistent")), {})

    def test_malformed_rows_skipped(self):
        # Missing module / unparseable addr must not crash.
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "snap.json"
            _write_snapshot(p, [
                {"tier": "easy", "module": "ov006",
                 "addr": "0x100", "size": 8, "name": "ok"},
                {"tier": "easy", "addr": "0x200", "size": 8},       # no module
                {"tier": "easy", "module": "ov006", "addr": "bad"},  # no addr
            ])
            entries = _load_entries(p)
        self.assertEqual(len(entries), 1)
        self.assertIn(("ov006", 0x100), entries)


class TestLoadBreakdown(unittest.TestCase):
    def test_missing_file_returns_empty(self):
        self.assertEqual(_load_breakdown(Path("/nonexistent")), {})

    def test_present_breakdown(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "snap.json"
            _write_snapshot(p, [], breakdown={
                "easy": {"matched": 5, "unmatched": 100, "total": 105},
            })
            b = _load_breakdown(p)
        self.assertEqual(b["easy"]["matched"], 5)

    def test_corrupt_json_returns_empty(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "snap.json"
            p.write_text("{not valid json")
            self.assertEqual(_load_breakdown(p), {})


class TestSortHelpers(unittest.TestCase):
    def test_tier_rank_ordering(self):
        self.assertLess(_tier_rank("trivial"), _tier_rank("easy"))
        self.assertLess(_tier_rank("easy"), _tier_rank("hard"))

    def test_unknown_tier_sorts_last(self):
        self.assertEqual(_tier_rank("unknown"), len(TIER_ORDER))

    def test_entry_sort_key_tier_first(self):
        easy = _entry("ov005", 0x100, tier="easy", size=0x40)
        triv = _entry("ov006", 0x200, tier="trivial", size=0x20)
        # trivial < easy in sort order regardless of size.
        self.assertLess(_entry_sort_key(triv), _entry_sort_key(easy))


class TestSigned(unittest.TestCase):
    def test_positive_has_plus(self):
        self.assertEqual(_signed(5), "+5")

    def test_zero_has_no_sign(self):
        self.assertEqual(_signed(0), "0")

    def test_negative_is_bare_minus(self):
        self.assertEqual(_signed(-3), "-3")


# ------------------------------------------------------------------------- #
# compute_diff
# ------------------------------------------------------------------------- #


class TestComputeDiff(unittest.TestCase):
    def test_identity_no_changes(self):
        before = {("ov006", 0x100): _entry("ov006", 0x100)}
        after = dict(before)
        d = compute_diff(before, after, {}, {})
        self.assertEqual(d.landed, [])
        self.assertEqual(d.new, [])
        self.assertEqual(d.migrations, [])

    def test_match_landed_detection(self):
        # Item present in before, absent in after → landed.
        before = {
            ("ov005", 0x100): _entry("ov005", 0x100),
            ("ov005", 0x200): _entry("ov005", 0x200),
        }
        after = {("ov005", 0x200): _entry("ov005", 0x200)}
        d = compute_diff(before, after, {}, {})
        self.assertEqual(len(d.landed), 1)
        self.assertEqual(d.landed[0].addr, 0x100)
        self.assertEqual(d.new, [])

    def test_new_entry_detection(self):
        before = {}
        after = {("ov006", 0x300): _entry("ov006", 0x300)}
        d = compute_diff(before, after, {}, {})
        self.assertEqual(d.landed, [])
        self.assertEqual(len(d.new), 1)
        self.assertEqual(d.new[0].addr, 0x300)

    def test_tier_migration_detection(self):
        before = {("ov011", 0x100): _entry("ov011", 0x100, tier="medium")}
        after = {("ov011", 0x100): _entry("ov011", 0x100, tier="named")}
        d = compute_diff(before, after, {}, {})
        self.assertEqual(d.landed, [])
        self.assertEqual(d.new, [])
        self.assertEqual(len(d.migrations), 1)
        b, a = d.migrations[0]
        self.assertEqual(b.tier, "medium")
        self.assertEqual(a.tier, "named")

    def test_landed_sorted_easiest_first(self):
        # Two landed items: trivial (small) + easy (large). trivial
        # must come first.
        before = {
            ("ov005", 0x100): _entry("ov005", 0x100, tier="easy", size=0x40),
            ("ov006", 0x200): _entry("ov006", 0x200, tier="trivial", size=0x4),
        }
        after = {}
        d = compute_diff(before, after, {}, {})
        self.assertEqual([e.tier for e in d.landed], ["trivial", "easy"])

    def test_tier_summary_union_of_tiers(self):
        # TIER_ORDER tiers always appear; unknowns present in either
        # breakdown also surface.
        before_b = {"easy": {"matched": 55, "unmatched": 1068, "total": 1123}}
        after_b = {"easy": {"matched": 59, "unmatched": 1064, "total": 1123}}
        d = compute_diff({}, {}, before_b, after_b)
        self.assertEqual(d.tier_summary["easy"], (55, 59))
        # TIER_ORDER entries always present even if breakdown didn't include.
        self.assertIn("trivial", d.tier_summary)
        self.assertEqual(d.tier_summary["trivial"], (0, 0))


# ------------------------------------------------------------------------- #
# render
# ------------------------------------------------------------------------- #


class TestRender(unittest.TestCase):
    def test_no_changes(self):
        d = WorklistDiff(
            landed=[], new=[], migrations=[],
            tier_summary={t: (0, 0) for t in TIER_ORDER},
        )
        md = render(d)
        self.assertIn("📉 Worklist delta", md)
        self.assertIn("No worklist changes", md)
        self.assertIn(FOOTER_MARKER, md)
        # No "matches landed" / "new candidates" sections.
        self.assertNotIn("Matches landed", md)
        self.assertNotIn("New worklist entries", md)
        self.assertNotIn("Tier migrations", md)

    def test_only_tier_summary_when_counts_shift_without_worklist_changes(self):
        # Edge case: breakdown totals changed but no individual worklist
        # identity shifted. Can happen when someone adds a TU carve
        # without matching anything. Tier summary should render; the
        # three other sections should not.
        d = WorklistDiff(
            landed=[], new=[], migrations=[],
            tier_summary={"easy": (55, 55), "trivial": (75, 78)},
        )
        md = render(d)
        self.assertIn("Tier matched-count delta", md)
        self.assertIn("**+3**", md)  # trivial delta bolded

    def test_full_mixed_output(self):
        landed = [
            _entry("ov005", 0x100, tier="easy", size=0x10, name="landed_a"),
            _entry("ov006", 0x200, tier="easy", size=0x10, name="landed_b"),
        ]
        new = [_entry("ov015", 0x1234, tier="easy", name="new_one")]
        mig = (
            _entry("ov011", 0xABC, tier="medium", name="migrated"),
            _entry("ov011", 0xABC, tier="named", name="migrated"),
        )
        d = WorklistDiff(
            landed=landed, new=new, migrations=[mig],
            tier_summary={
                "trivial": (0, 0),
                "easy":    (55, 59),
                "sinit":   (46, 46),
            },
        )
        md = render(d)
        # Headline count.
        self.assertIn("2 match(es) landed", md)
        self.assertIn("1 new candidate(s)", md)
        self.assertIn("1 tier migration(s)", md)
        # Section presence.
        self.assertIn("✅ Matches landed (2)", md)
        self.assertIn("🆕 New worklist entries (1)", md)
        self.assertIn("🔀 Tier migrations (1)", md)
        # Specific rows rendered.
        self.assertIn("`landed_a`", md)
        self.assertIn("`landed_b`", md)
        self.assertIn("`new_one`", md)
        self.assertIn("`medium`", md)
        self.assertIn("`named`", md)
        # Tier summary: easy Δ is +4 (bold), sinit Δ is 0 (plain).
        self.assertIn("**+4**", md)
        self.assertNotIn("**0**", md)
        # Footer.
        self.assertIn(FOOTER_MARKER, md)

    def test_per_section_limit_with_truncation(self):
        many = [
            _entry("ov006", 0x100 + i * 4, name=f"fn_{i}", tier="trivial")
            for i in range(50)
        ]
        d = WorklistDiff(
            landed=many, new=[], migrations=[],
            tier_summary={"trivial": (0, 50)},
        )
        md = render(d, limit_per_section=10)
        # First 10 rendered.
        self.assertIn("`fn_0`", md)
        self.assertIn("`fn_9`", md)
        # 11th onward should NOT appear.
        self.assertNotIn("`fn_10`", md)
        # Truncation note.
        self.assertIn("_…and 40 more matches landed_", md)


class TestFooterMarker(unittest.TestCase):
    def test_marker_in_every_render(self):
        """The footer marker is load-bearing — any CI wiring will use
        it to upsert a single comment instead of spamming on push."""
        for d in [
            WorklistDiff(landed=[], new=[], migrations=[],
                         tier_summary={}),
            WorklistDiff(
                landed=[_entry("ov005", 0x100)],
                new=[], migrations=[],
                tier_summary={"easy": (0, 1)},
            ),
        ]:
            md = render(d)
            self.assertIn(FOOTER_MARKER, md)


# ------------------------------------------------------------------------- #
# End-to-end: load both snapshots + render
# ------------------------------------------------------------------------- #


class TestEndToEnd(unittest.TestCase):
    def test_real_fixture_pair(self):
        # Simulates the shape of a real decomp-PR's before/after:
        # 2 landed matches + 1 new candidate + 1 migration.
        before = {
            "tier_breakdown": {
                "easy": {"matched": 55, "unmatched": 1068, "total": 1123},
            },
            "worklist": [
                {"tier": "easy", "module": "ov000", "addr": "0x021ac038",
                 "size": 16, "name": "func_ov000_021ac038"},
                {"tier": "easy", "module": "ov000", "addr": "0x021ac550",
                 "size": 16, "name": "func_ov000_021ac550"},
                {"tier": "medium", "module": "ov011", "addr": "0x021ce324",
                 "size": 32, "name": "func_ov011_021ce324"},
            ],
        }
        after = {
            "tier_breakdown": {
                "easy": {"matched": 57, "unmatched": 1066, "total": 1123},
            },
            "worklist": [
                # 021ac038 + 021ac550 landed.
                {"tier": "named", "module": "ov011", "addr": "0x021ce324",
                 "size": 32, "name": "func_ov011_021ce324"},
                # New candidate.
                {"tier": "easy", "module": "ov015", "addr": "0x021b1234",
                 "size": 8, "name": "func_ov015_021b1234"},
            ],
        }
        with tempfile.TemporaryDirectory() as td:
            before_p = Path(td) / "before.json"
            after_p = Path(td) / "after.json"
            before_p.write_text(json.dumps(before))
            after_p.write_text(json.dumps(after))

            entries_before = _load_entries(before_p)
            entries_after = _load_entries(after_p)
            b_break = _load_breakdown(before_p)
            a_break = _load_breakdown(after_p)

        d = compute_diff(
            entries_before, entries_after, b_break, a_break,
        )
        self.assertEqual(len(d.landed), 2)
        self.assertEqual(len(d.new), 1)
        self.assertEqual(len(d.migrations), 1)

        md = render(d)
        # Sanity on the rendered output.
        self.assertIn("2 match(es) landed", md)
        self.assertIn("`func_ov000_021ac038`", md)
        self.assertIn("`func_ov000_021ac550`", md)
        self.assertIn("`func_ov015_021b1234`", md)
        self.assertIn("`medium`", md)
        self.assertIn("`named`", md)


class TestMainUtf8StdoutReconfigure(unittest.TestCase):
    """Regression coverage for the Windows cp1252 stdout crash.

    `render()` includes the 📉 emoji (plus ✅ 🆕 🔀 in richer diffs).
    On a default Windows cp1252 console, `print(md)` would raise
    UnicodeEncodeError before the fix. `main()` reconfigures stdout
    to utf-8 early to prevent that; these tests pin the guard.
    """

    def _write_pair_with_landed_match(self, td: Path) -> tuple[Path, Path]:
        """Create a before/after pair that exercises the emoji-rich
        path (matches-landed banner surfaces ✅, header always has 📉)."""
        before = td / "before.json"
        after = td / "after.json"
        _write_snapshot(before, [
            {"tier": "easy", "module": "ov006",
             "addr": "0x021ba1f0", "size": 8, "name": "x"},
        ], breakdown={"easy": {"matched": 1, "unmatched": 2, "total": 3}})
        _write_snapshot(after, [], breakdown={
            "easy": {"matched": 2, "unmatched": 1, "total": 3},
        })
        return before, after

    def test_main_with_ascii_only_stdout_does_not_crash(self):
        """Simulate a cp1252 console by routing stdout through a
        BytesIO wrapped in a TextIOWrapper with encoding='cp1252'
        and errors='strict'. Before the fix, `print(md)` would raise
        UnicodeEncodeError on the 📉 header. After the fix, main()
        reconfigures to utf-8 early and the write succeeds."""
        from ci_format_worklist_diff import main
        with tempfile.TemporaryDirectory() as td:
            before, after = self._write_pair_with_landed_match(Path(td))
            buf = io.BytesIO()
            ascii_stdout = io.TextIOWrapper(
                buf, encoding="cp1252", errors="strict",
                write_through=True,
            )
            argv = ["ci_format_worklist_diff.py", str(before), str(after)]
            with patch.object(sys, "argv", argv), \
                 redirect_stdout(ascii_stdout):
                rc = main()
            ascii_stdout.flush()
            self.assertEqual(rc, 0)
        written = buf.getvalue()
        # The header emoji must be preserved in the bytes — reconfigure
        # switched the encoding to utf-8 in place, so it's encoded as
        # the utf-8 byte sequence for 📉 (0xF0 0x9F 0x93 0x89).
        self.assertIn(b"\xf0\x9f\x93\x89", written)

    def test_main_with_no_reconfigure_support_does_not_crash(self):
        """Some stdout replacements (StringIO, custom test captures)
        don't expose `reconfigure` at all. The try/except around the
        call must swallow AttributeError cleanly."""
        from ci_format_worklist_diff import main
        with tempfile.TemporaryDirectory() as td:
            before, after = self._write_pair_with_landed_match(Path(td))
            buf = io.StringIO()  # no .reconfigure method
            argv = ["ci_format_worklist_diff.py", str(before), str(after)]
            with patch.object(sys, "argv", argv), redirect_stdout(buf):
                rc = main()
            self.assertEqual(rc, 0)
        self.assertIn("📉 Worklist delta", buf.getvalue())


if __name__ == "__main__":
    unittest.main()
