"""Unit tests for tools/diff_reasons.py.

The tool's job is to turn an opaque `47.3%` into actionable buckets
for decomp-triage. A regression in the bucket boundaries (or the
`iter_function_entries` parser being too strict on missing fields)
would give the decomper wrong signals about what's close-to-matching
— nasty and hard to spot downstream. These tests pin:

  - classify() boundary behaviour at every edge (0, 0.01, 25, 75, 95,
    99.999, 100)
  - load_report() graceful failure on missing / malformed files
  - iter_function_entries() defensive parsing (missing fields, zero
    fuzzy, null fuzzy, empty units list)
  - sort order (bucket rank → match% desc → unit → name)
  - classify_report per-module breakdown
  - render_markdown structure (headline, almost bucket visible,
    matched bucket hidden by default, footer marker)
  - render_json schema (bucket_counts total_functions etc.)
"""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent.parent / "tools"
sys.path.insert(0, str(_TOOLS))

from diff_reasons import (  # noqa: E402
    BUCKET_ALMOST,
    BUCKET_CLOSE,
    BUCKET_LOW,
    BUCKET_MATCHED,
    BUCKET_MEDIUM,
    BUCKET_ORDER,
    BUCKET_ZERO,
    ClassifiedReport,
    FunctionEntry,
    classify,
    classify_report,
    iter_function_entries,
    load_report,
    render_json,
    render_markdown,
)


FOOTER_MARKER = "<sub>🤖 Generated by `tools/diff_reasons.py`"


def _fn(
    unit: str, name: str, pct: float, size: int = 0x10,
) -> dict:
    """Build one function entry in the shape objdiff emits."""
    return {
        "name": name,
        "size": size,
        "fuzzy_match_percent": pct,
    }


def _report(units: list[tuple[str, list[dict]]]) -> dict:
    """Build a minimal report.json dict from (unit_name, functions)
    pairs. Follows objdiff's schema from protos/report.proto."""
    return {
        "version": 2,
        "measures": {},
        "units": [
            {"name": name, "functions": fns} for name, fns in units
        ],
    }


# ------------------------------------------------------------------------- #
# classify() boundaries
# ------------------------------------------------------------------------- #


class TestClassify(unittest.TestCase):
    def test_zero_is_zero_bucket(self):
        self.assertEqual(classify(0.0), BUCKET_ZERO)

    def test_just_above_zero_is_low(self):
        self.assertEqual(classify(0.01), BUCKET_LOW)

    def test_low_upper_boundary(self):
        # 25 is the threshold into medium, so 24.999 is the last low.
        self.assertEqual(classify(24.999), BUCKET_LOW)
        self.assertEqual(classify(25.0), BUCKET_MEDIUM)

    def test_medium_upper_boundary(self):
        self.assertEqual(classify(74.999), BUCKET_MEDIUM)
        self.assertEqual(classify(75.0), BUCKET_CLOSE)

    def test_close_upper_boundary(self):
        self.assertEqual(classify(94.999), BUCKET_CLOSE)
        self.assertEqual(classify(95.0), BUCKET_ALMOST)

    def test_almost_upper_boundary_below_matched(self):
        self.assertEqual(classify(99.0), BUCKET_ALMOST)
        self.assertEqual(classify(99.998), BUCKET_ALMOST)

    def test_matched_epsilon_absorbs_float_noise(self):
        # protobuf wire float may deliver 99.9999 from a 100.0 encode.
        # The matched bucket must absorb that.
        self.assertEqual(classify(99.9999), BUCKET_MATCHED)
        self.assertEqual(classify(100.0), BUCKET_MATCHED)


# ------------------------------------------------------------------------- #
# load_report()
# ------------------------------------------------------------------------- #


class TestLoadReport(unittest.TestCase):
    def test_missing_file_returns_none(self):
        self.assertIsNone(load_report(Path("/nonexistent.json")))

    def test_malformed_json_returns_none(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "r.json"
            p.write_text("{not json")
            self.assertIsNone(load_report(p))

    def test_valid_json_returns_dict(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "r.json"
            p.write_text(json.dumps(_report([])))
            got = load_report(p)
            self.assertIsNotNone(got)
            self.assertEqual(got.get("version"), 2)


# ------------------------------------------------------------------------- #
# iter_function_entries()
# ------------------------------------------------------------------------- #


class TestIterFunctionEntries(unittest.TestCase):
    def test_empty_report(self):
        self.assertEqual(iter_function_entries(_report([])), [])

    def test_missing_fuzzy_treated_as_zero(self):
        # objdiff's protobuf may omit zero-valued fuzzy_match_percent
        # when serialising JSON. Tolerate that.
        r = {
            "units": [{
                "name": "u",
                "functions": [{"name": "fn", "size": 4}],
            }],
        }
        out = iter_function_entries(r)
        self.assertEqual(len(out), 1)
        self.assertEqual(out[0].fuzzy_match_percent, 0.0)
        self.assertEqual(out[0].bucket, BUCKET_ZERO)

    def test_null_fuzzy_treated_as_zero(self):
        r = _report([("u", [{"name": "fn", "size": 4,
                             "fuzzy_match_percent": None}])])
        out = iter_function_entries(r)
        self.assertEqual(out[0].fuzzy_match_percent, 0.0)

    def test_sort_bucket_rank_first(self):
        r = _report([
            ("u", [
                _fn("u", "zz_at_100", 100.0),   # matched last
                _fn("u", "aa_at_95", 95.0),      # almost first
                _fn("u", "bb_at_80", 80.0),      # close middle
            ]),
        ])
        out = iter_function_entries(r)
        # Expected order: almost, close, matched.
        buckets = [e.bucket for e in out]
        self.assertEqual(
            buckets,
            [BUCKET_ALMOST, BUCKET_CLOSE, BUCKET_MATCHED],
        )

    def test_sort_within_bucket_by_fuzzy_desc(self):
        r = _report([
            ("u", [
                _fn("u", "lower_almost", 95.1),
                _fn("u", "higher_almost", 99.5),
            ]),
        ])
        out = iter_function_entries(r)
        # Higher match% first within the bucket.
        self.assertEqual(out[0].name, "higher_almost")
        self.assertEqual(out[1].name, "lower_almost")

    def test_missing_unit_name_has_fallback(self):
        # Defensive: if a unit has no name field, still produce an
        # entry with a clearly-flagged placeholder.
        r = {
            "units": [
                {"functions": [_fn("", "orphan", 50.0)]},
            ],
        }
        out = iter_function_entries(r)
        self.assertEqual(len(out), 1)
        self.assertEqual(out[0].unit, "<unknown>")


# ------------------------------------------------------------------------- #
# classify_report() aggregation
# ------------------------------------------------------------------------- #


class TestClassifyReport(unittest.TestCase):
    def _fixture(self) -> dict:
        return _report([
            ("ov005.c", [
                _fn("ov005.c", "fn_matched", 100.0),
                _fn("ov005.c", "fn_almost", 98.0),
                _fn("ov005.c", "fn_almost2", 96.0),
            ]),
            ("ov006.c", [
                _fn("ov006.c", "fn_close", 80.0),
                _fn("ov006.c", "fn_medium", 50.0),
                _fn("ov006.c", "fn_low", 10.0),
                _fn("ov006.c", "fn_zero", 0.0),
            ]),
        ])

    def test_total_function_count(self):
        c = classify_report(self._fixture())
        self.assertEqual(c.total_functions, 7)

    def test_per_bucket_counts(self):
        c = classify_report(self._fixture())
        self.assertEqual(c.count(BUCKET_MATCHED), 1)
        self.assertEqual(c.count(BUCKET_ALMOST), 2)
        self.assertEqual(c.count(BUCKET_CLOSE), 1)
        self.assertEqual(c.count(BUCKET_MEDIUM), 1)
        self.assertEqual(c.count(BUCKET_LOW), 1)
        self.assertEqual(c.count(BUCKET_ZERO), 1)

    def test_per_module_distribution(self):
        c = classify_report(self._fixture())
        ov005 = c.per_module_buckets["ov005.c"]
        ov006 = c.per_module_buckets["ov006.c"]
        self.assertEqual(ov005[BUCKET_ALMOST], 2)
        self.assertEqual(ov005[BUCKET_MATCHED], 1)
        self.assertEqual(ov006[BUCKET_CLOSE], 1)
        self.assertEqual(ov006[BUCKET_ZERO], 1)

    def test_empty_report_yields_zero_counts(self):
        c = classify_report(_report([]))
        self.assertEqual(c.total_functions, 0)
        for b in BUCKET_ORDER:
            self.assertEqual(c.count(b), 0)


# ------------------------------------------------------------------------- #
# render_markdown()
# ------------------------------------------------------------------------- #


class TestRenderMarkdown(unittest.TestCase):
    def test_empty_report_still_renders(self):
        md = render_markdown(
            ClassifiedReport(total_functions=0, buckets={b: [] for b in BUCKET_ORDER}),
        )
        self.assertIn("Match-depth classification", md)
        self.assertIn(FOOTER_MARKER, md)

    def test_almost_bucket_headline_present(self):
        c = classify_report(_report([
            ("u", [_fn("u", "fn_at_97", 97.0)]),
        ]))
        md = render_markdown(c)
        self.assertIn("🟡 Almost-there (95-99%, 1)", md)
        self.assertIn("`fn_at_97`", md)
        self.assertIn("97.00%", md)

    def test_matched_bucket_hidden_by_default(self):
        # A report where every function is at 100% should render an
        # empty main body — the bucket summary hides matched by
        # default to keep the view action-oriented.
        c = classify_report(_report([
            ("u", [_fn("u", "fn1", 100.0), _fn("u", "fn2", 100.0)]),
        ]))
        md = render_markdown(c)
        self.assertNotIn("`matched`", md)
        # Count is still visible in the prose headline, though.
        self.assertIn("Classified **2** function(s)", md)

    def test_matched_bucket_shown_when_requested(self):
        c = classify_report(_report([
            ("u", [_fn("u", "fn1", 100.0)]),
        ]))
        md = render_markdown(c, include_matched=True)
        self.assertIn("`matched`", md)

    def test_top_n_truncation(self):
        # 30 almost-bucket fns, top=5 → only 5 rows + truncation note.
        fns = [_fn("u", f"fn_{i}", 95.0 + i * 0.1) for i in range(30)]
        c = classify_report(_report([("u", fns)]))
        md = render_markdown(c, top_n=5)
        # Newest fn has highest % and appears first.
        self.assertIn("`fn_29`", md)
        # Truncation note surfaces.
        self.assertIn("and 25 more", md)

    def test_per_unit_section_skips_zero_only_units(self):
        # A unit with only matched + zero functions shouldn't appear
        # in the per-unit heatmap (nothing actionable there).
        c = classify_report(_report([
            ("boring.c", [
                _fn("boring.c", "a", 100.0),
                _fn("boring.c", "b", 0.0),
            ]),
            ("interesting.c", [
                _fn("interesting.c", "c", 90.0),
            ]),
        ]))
        md = render_markdown(c)
        self.assertIn("`interesting.c`", md)
        # boring.c has no non-0 non-100 entries.
        self.assertNotIn("| `boring.c` |", md)


# ------------------------------------------------------------------------- #
# render_json()
# ------------------------------------------------------------------------- #


class TestRenderJson(unittest.TestCase):
    def test_json_schema(self):
        c = classify_report(_report([
            ("u", [_fn("u", "fn1", 95.0), _fn("u", "fn2", 50.0)]),
        ]))
        payload = render_json(c)
        # Round-trip.
        json.dumps(payload)
        self.assertEqual(payload["total_functions"], 2)
        self.assertIn("bucket_counts", payload)
        self.assertEqual(payload["bucket_counts"][BUCKET_ALMOST], 1)
        self.assertEqual(payload["bucket_counts"][BUCKET_MEDIUM], 1)
        self.assertIn("buckets", payload)
        self.assertEqual(len(payload["buckets"][BUCKET_ALMOST]), 1)
        self.assertEqual(
            payload["buckets"][BUCKET_ALMOST][0]["name"], "fn1",
        )
        self.assertIn("per_unit", payload)


class TestFunctionEntryBucketProperty(unittest.TestCase):
    def test_bucket_property_derives_from_fuzzy(self):
        e = FunctionEntry(unit="u", name="fn", size=4,
                          fuzzy_match_percent=96.0)
        self.assertEqual(e.bucket, BUCKET_ALMOST)


if __name__ == "__main__":
    unittest.main()
