; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov002
; Range:  0x022cad38..0x022cb96c (3124 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern func_ov002_0224848c
        .extern func_ov002_022482d0
        .extern func_ov002_022483ac
        .extern func_ov002_02248434
        .extern func_ov002_02248a1c
        .extern func_ov002_02248ab0
        .extern func_ov002_02248bc0
        .extern func_ov002_02248ce8
        .extern func_ov002_02248b5c
        .extern func_ov002_02248d70
        .extern func_ov002_02249090
        .extern func_ov002_02248e4c
        .extern func_ov002_02248f60
        .extern func_ov002_02248fdc
        .extern func_ov002_0224915c
        .extern func_ov002_022491c8
        .extern func_ov002_02249268
        .extern func_ov002_02249310
        .extern func_ov002_02249398
        .extern func_ov002_022493f0
        .extern func_ov002_022494a4
        .extern func_ov002_0224958c
        .extern func_ov002_02249818
        .extern func_ov002_02249918
        .extern func_ov002_022499b0
        .extern func_ov002_02249c28
        .extern func_ov002_02249a54
        .extern func_ov002_02249cec
        .extern func_ov002_0224b01c
        .extern func_ov002_022496b4
        .extern func_ov002_02249b88
        .extern func_ov002_02249790
        .extern func_ov002_02249af0
        .extern func_ov002_02249d9c
        .extern func_ov002_02249e84
        .extern func_ov002_02249ec4
        .extern func_ov002_02249f68
        .extern func_ov002_0224a038
        .extern func_ov002_0224a120
        .extern func_ov002_0224a1e4
        .extern func_ov002_0224a28c
        .extern func_ov002_0224a32c
        .extern func_ov002_0224a580
        .extern func_ov002_0224a618
        .extern func_ov002_0224a6f4
        .extern func_ov002_0224a778
        .extern func_ov002_0224a954
        .extern func_ov002_0224a3d0
        .extern func_ov002_0224a4f8
        .extern func_ov002_0224aa14
        .extern func_ov002_0224aac0
        .extern func_ov002_0224ab44
        .extern func_ov002_0224abcc
        .extern func_ov002_0224ac6c
        .extern func_ov002_0224ad64
        .extern func_ov002_0224aeb8
        .extern func_ov002_0224b0b0
        .extern func_ov002_0224b158
        .extern func_ov002_0224b1e0
        .extern func_ov002_0224b550
        .extern func_ov002_0224b948
        .extern func_ov002_0224b27c
        .extern func_ov002_0224b2e0
        .extern func_ov002_0224b3b0
        .extern func_ov002_0224b464
        .extern func_ov002_0224b49c
        .extern func_ov002_0224b5b4
        .extern func_ov002_0224b68c
        .extern func_ov002_0224b848
        .extern func_ov002_0224bbd8
        .extern func_ov002_0224b9cc
        .extern func_ov002_0224bae8
        .extern func_ov002_0224bb54
        .extern func_ov002_0224bc88
        .extern func_ov002_0224bd3c
        .extern func_ov002_0224bdd4
        .extern func_ov002_0224be50
        .extern func_ov002_0224bf3c
        .extern func_ov002_0224c2a4
        .extern func_ov002_0224c034
        .extern func_ov002_0224c160
        .extern func_ov002_0224c0b8
        .extern func_ov002_0224c1e4
        .extern func_ov002_0224c358
        .extern func_ov002_0224c440
        .extern func_ov002_0224c4e8
        .extern func_ov002_0224c57c
        .extern func_ov002_0224c620
        .extern func_ov002_0224c69c
        .extern func_ov002_0224c8c4
        .extern func_ov002_0224c980
        .extern func_ov002_0224ca08
        .extern func_ov002_0224cc54
        .extern func_ov002_0224cac4
        .extern func_ov002_0224cbfc
        .extern func_ov002_0224d8b4
        .extern func_ov002_0224d938
        .extern func_ov002_0224cc90
        .extern func_ov002_0224cd18
        .extern func_ov002_0224cd9c
        .extern func_ov002_0224ce18
        .extern func_ov002_0224cf14
        .extern func_ov002_0224cf98
        .extern func_ov002_0224d044
        .extern func_ov002_0224d0f8
        .extern func_ov002_0224d19c
        .extern func_ov002_0224d1f0
        .extern func_ov002_0224d2ec
        .extern func_ov002_0224d374
        .extern func_ov002_0224d424
        .extern func_ov002_0224d4ac
        .extern func_ov002_0224d510
        .extern func_ov002_0224d5c8
        .extern func_ov002_0224d660
        .extern func_ov002_0224d718
        .extern func_ov002_0224d794
        .extern func_ov002_0224d818
        .extern func_ov002_0224da7c
        .extern func_ov002_0224db94
        .extern func_ov002_0224dafc
        .extern func_ov002_0224dc24
        .extern func_ov002_0224ddf0
        .extern func_ov002_0224de94
        .extern func_ov002_0224df78
        .extern func_ov002_0224e018
        .extern func_ov002_0224e0dc
        .extern func_ov002_0224e184
        .extern func_ov002_0224e230
        .extern func_ov002_0224e374
        .extern func_ov002_0224e2b8
        .extern func_ov002_0224e390
        .extern func_ov002_0224e490
        .extern func_ov002_0224e518
        .extern func_ov002_0224e660
        .extern func_ov002_0224e6e8
        .extern func_ov002_0224e78c
        .extern func_ov002_0224e840
        .extern func_ov002_0224e8fc
        .extern func_ov002_0224e9cc
        .extern func_ov002_0224ea54
        .extern func_ov002_0224eab4
        .extern func_ov002_0224eb3c
        .extern func_ov002_0224ed8c
        .extern func_ov002_0224ee48
        .extern func_ov002_0224eeac
        .extern func_ov002_0224ef84
        .extern func_ov002_0224f024
        .extern func_ov002_0224f0c4
        .extern func_ov002_0224f178
        .extern func_ov002_0224f370
        .extern func_ov002_0224f3e4
        .extern func_ov002_0224f4a0
        .extern func_ov002_0224f548
        .extern func_ov002_0224f5fc
        .extern func_ov002_0224f74c
        .extern func_ov002_0224f7a0
        .extern func_ov002_0224f824
        .extern func_ov002_0224f8ac
        .extern func_ov002_0224f910
        .extern func_ov002_0224f9c0
        .extern func_ov002_0224fa6c
        .extern func_ov002_0224fad8
        .extern func_ov002_0224fb58
        .extern func_ov002_0224fcd4
        .extern func_ov002_0224fd94
        .extern func_ov002_0224fe84
        .extern func_ov002_0224ff28
        .extern func_ov002_02250044
        .extern func_ov002_02250234
        .extern func_ov002_02250350
        .extern func_ov002_022503d8
        .extern func_ov002_02250498
        .extern func_ov002_02250540
        .extern func_ov002_022505e8
        .extern func_ov002_02250670
        .extern func_ov002_0225070c
        .extern func_ov002_022507c0
        .extern func_ov002_0225085c
        .extern func_ov002_02250a28
        .extern func_ov002_02250b34
        .extern func_ov002_02250b44
        .extern func_ov002_02250d14
        .extern func_ov002_02250d9c
        .extern func_ov002_02250e40
        .extern func_ov002_02251104
        .extern func_ov002_022511bc
        .extern func_ov002_022512a4
        .extern func_ov002_02251380
        .extern func_ov002_02251484
        .extern func_ov002_022515b0
        .extern func_ov002_0225163c
        .extern func_ov002_0225170c
        .extern func_ov002_022517c0
        .extern func_ov002_02251844
        .extern func_ov002_02251908
        .extern func_ov002_02251b14
        .extern func_ov002_022519c4
        .extern func_ov002_02251bb0
        .extern func_ov002_02251c3c
        .extern func_ov002_02251d00
        .extern func_ov002_02251d78
        .extern func_ov002_02251df4
        .extern func_ov002_02251ec0
        .extern func_ov002_02251f70
        .extern func_ov002_02252014
        .extern func_ov002_022520f0
        .extern func_ov002_022521ac
        .extern func_ov002_02252240
        .extern func_ov002_022523cc
        .extern func_ov002_02252438
        .extern func_ov002_022524a4
        .extern func_ov002_02252558
        .extern func_ov002_02252664
        .extern func_ov002_02252734
        .extern func_ov002_022527b8
        .extern func_ov002_02252868
        .extern func_ov002_02252914
        .extern func_ov002_02252998
        .extern func_ov002_02252a58
        .extern func_ov002_02252af8
        .extern func_ov002_02252b80
        .extern func_ov002_02252c08
        .extern func_ov002_02252ca4
        .extern func_ov002_02252d2c
        .extern func_ov002_02252d98
        .extern func_ov002_02252e54
        .extern func_ov002_02252f64
        .extern func_ov002_02253000
        .extern func_ov002_022530a8
        .extern func_ov002_02253154
        .extern func_ov002_022531bc
        .extern func_ov002_02253304
        .extern func_ov002_02259b4c
        .extern func_ov002_02253390

        .global data_ov002_022cad38
data_ov002_022cad38:
        .word func_ov002_0224848c
        .byte 0xd6, 0x0f, 0x00, 0x00
        .word func_ov002_022482d0
        .byte 0x0c, 0x10, 0x00, 0x00
        .word func_ov002_022483ac
        .byte 0x51, 0x10, 0x00, 0x00
        .word func_ov002_02248434
        .byte 0xe4, 0x10, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x38, 0x11, 0x00, 0x00
        .word func_ov002_02248a1c
        .byte 0x4a, 0x11, 0x00, 0x00
        .word func_ov002_02248ab0
        .byte 0x4f, 0x11, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x52, 0x11, 0x00, 0x00
        .word func_ov002_02248ce8
        .byte 0xa0, 0x11, 0x00, 0x00
        .word func_ov002_02248b5c
        .byte 0xe4, 0x11, 0x00, 0x00
        .word func_ov002_02248d70
        .byte 0x32, 0x12, 0x00, 0x00
        .word func_ov002_02249090
        .byte 0x93, 0x12, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x94, 0x12, 0x00, 0x00
        .word func_ov002_02248e4c
        .byte 0xa4, 0x12, 0x00, 0x00
        .word func_ov002_02248f60
        .byte 0xa7, 0x12, 0x00, 0x00
        .word func_ov002_02248fdc
        .byte 0xca, 0x12, 0x00, 0x00
        .word func_ov002_0224915c
        .byte 0xde, 0x12, 0x00, 0x00
        .word func_ov002_02249090
        .byte 0xe5, 0x12, 0x00, 0x00
        .word func_ov002_022491c8
        .byte 0xea, 0x12, 0x00, 0x00
        .word func_ov002_02249268
        .byte 0xed, 0x12, 0x00, 0x00
        .word func_ov002_02249310
        .byte 0xf4, 0x12, 0x00, 0x00
        .word func_ov002_02249398
        .byte 0xf9, 0x12, 0x00, 0x00
        .word func_ov002_022493f0
        .byte 0x03, 0x13, 0x00, 0x00
        .word func_ov002_022491c8
        .byte 0x08, 0x13, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x15, 0x13, 0x00, 0x00
        .word func_ov002_022494a4
        .byte 0x2f, 0x13, 0x00, 0x00
        .word func_ov002_0224958c
        .byte 0x33, 0x13, 0x00, 0x00
        .word func_ov002_02249818
        .byte 0x34, 0x13, 0x00, 0x00
        .word func_ov002_02249918
        .byte 0x35, 0x13, 0x00, 0x00
        .word func_ov002_02249818
        .byte 0x39, 0x13, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0x3a, 0x13, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0x3b, 0x13, 0x00, 0x00
        .word func_ov002_02249c28
        .byte 0x3c, 0x13, 0x00, 0x00
        .word func_ov002_02249818
        .byte 0x3e, 0x13, 0x00, 0x00
        .word func_ov002_02249818
        .byte 0x3f, 0x13, 0x00, 0x00
        .word func_ov002_02249818
        .byte 0x41, 0x13, 0x00, 0x00
        .word func_ov002_02249a54
        .byte 0x42, 0x13, 0x00, 0x00
        .word func_ov002_02249818
        .byte 0x59, 0x13, 0x00, 0x00
        .word func_ov002_02249cec
        .byte 0x5b, 0x13, 0x00, 0x00
        .word func_ov002_0224b01c
        .byte 0x62, 0x13, 0x00, 0x00
        .word func_ov002_022496b4
        .byte 0x65, 0x13, 0x00, 0x00
        .word func_ov002_02249b88
        .byte 0x66, 0x13, 0x00, 0x00
        .word func_ov002_02249b88
        .byte 0x6a, 0x13, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0x79, 0x13, 0x00, 0x00
        .word func_ov002_02249790
        .byte 0x7c, 0x13, 0x00, 0x00
        .word func_ov002_02249af0
        .byte 0x7d, 0x13, 0x00, 0x00
        .word func_ov002_02249b88
        .byte 0x9d, 0x13, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0xa1, 0x13, 0x00, 0x00
        .word func_ov002_02249d9c
        .byte 0xed, 0x13, 0x00, 0x00
        .word func_ov002_02249e84
        .byte 0xf5, 0x13, 0x00, 0x00
        .word func_ov002_02249ec4
        .byte 0xfe, 0x13, 0x00, 0x00
        .word func_ov002_02249f68
        .byte 0x0b, 0x14, 0x00, 0x00
        .word func_ov002_0224a038
        .byte 0x3d, 0x14, 0x00, 0x00
        .word func_ov002_0224a120
        .byte 0x45, 0x14, 0x00, 0x00
        .word func_ov002_0224a1e4
        .byte 0x46, 0x14, 0x00, 0x00
        .word func_ov002_0224a28c
        .byte 0x49, 0x14, 0x00, 0x00
        .word func_ov002_02249ec4
        .byte 0x4c, 0x14, 0x00, 0x00
        .word func_ov002_02249ec4
        .byte 0x52, 0x14, 0x00, 0x00
        .word func_ov002_0224a32c
        .byte 0x57, 0x14, 0x00, 0x00
        .word func_ov002_02249ec4
        .byte 0x66, 0x14, 0x00, 0x00
        .word func_ov002_0224a580
        .byte 0x68, 0x14, 0x00, 0x00
        .word func_ov002_0224a618
        .byte 0x6e, 0x14, 0x00, 0x00
        .word func_ov002_0224a6f4
        .byte 0x6f, 0x14, 0x00, 0x00
        .word func_ov002_0224a778
        .byte 0x74, 0x14, 0x00, 0x00
        .word func_ov002_0224a954
        .byte 0x76, 0x14, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0x80, 0x14, 0x00, 0x00
        .word func_ov002_02249310
        .byte 0x81, 0x14, 0x00, 0x00
        .word func_ov002_02248ab0
        .byte 0x82, 0x14, 0x00, 0x00
        .word func_ov002_0224a4f8
        .byte 0x83, 0x14, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0x84, 0x14, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0x85, 0x14, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0x86, 0x14, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0x87, 0x14, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0x88, 0x14, 0x00, 0x00
        .word func_ov002_02249b88
        .byte 0x8b, 0x14, 0x00, 0x00
        .word func_ov002_0224aac0
        .byte 0x90, 0x14, 0x00, 0x00
        .word func_ov002_0224ab44
        .byte 0x9c, 0x14, 0x00, 0x00
        .word func_ov002_022491c8
        .byte 0x9e, 0x14, 0x00, 0x00
        .word func_ov002_0224abcc
        .byte 0xa7, 0x14, 0x00, 0x00
        .word func_ov002_0224ac6c
        .byte 0xb3, 0x14, 0x00, 0x00
        .word func_ov002_0224ad64
        .byte 0xba, 0x14, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0xc1, 0x14, 0x00, 0x00
        .word func_ov002_0224aeb8
        .byte 0xc2, 0x14, 0x00, 0x00
        .word func_ov002_02249310
        .byte 0xc4, 0x14, 0x00, 0x00
        .word func_ov002_0224b0b0
        .byte 0xc6, 0x14, 0x00, 0x00
        .word func_ov002_0224b01c
        .byte 0xd0, 0x14, 0x00, 0x00
        .word func_ov002_0224b0b0
        .byte 0xd2, 0x14, 0x00, 0x00
        .word func_ov002_0224b158
        .byte 0xd7, 0x14, 0x00, 0x00
        .word func_ov002_0224b1e0
        .byte 0xdd, 0x14, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0xe7, 0x14, 0x00, 0x00
        .word func_ov002_0224b550
        .byte 0xea, 0x14, 0x00, 0x00
        .word func_ov002_02248ce8
        .byte 0xee, 0x14, 0x00, 0x00
        .word func_ov002_0224b948
        .byte 0xef, 0x14, 0x00, 0x00
        .word func_ov002_0224b27c
        .byte 0xf6, 0x14, 0x00, 0x00
        .word func_ov002_0224b2e0
        .byte 0xf7, 0x14, 0x00, 0x00
        .word func_ov002_0224b3b0
        .byte 0xfd, 0x14, 0x00, 0x00
        .word func_ov002_0224b464
        .byte 0x07, 0x15, 0x00, 0x00
        .word func_ov002_0224b49c
        .byte 0x08, 0x15, 0x00, 0x00
        .word func_ov002_0224b49c
        .byte 0x15, 0x15, 0x00, 0x00
        .word func_ov002_0224b550
        .byte 0x1e, 0x15, 0x00, 0x00
        .word func_ov002_0224b5b4
        .byte 0x22, 0x15, 0x00, 0x00
        .word func_ov002_0224b68c
        .byte 0x29, 0x15, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x2f, 0x15, 0x00, 0x00
        .word func_ov002_0224b848
        .byte 0x31, 0x15, 0x00, 0x00
        .word func_ov002_0224b948
        .byte 0x34, 0x15, 0x00, 0x00
        .word func_ov002_0224bbd8
        .byte 0x36, 0x15, 0x00, 0x00
        .word func_ov002_0224b9cc
        .byte 0x3b, 0x15, 0x00, 0x00
        .word func_ov002_0224bae8
        .byte 0x62, 0x15, 0x00, 0x00
        .word func_ov002_0224bb54
        .byte 0x6a, 0x15, 0x00, 0x00
        .word func_ov002_0224bbd8
        .byte 0x6d, 0x15, 0x00, 0x00
        .word func_ov002_0224bc88
        .byte 0x72, 0x15, 0x00, 0x00
        .word func_ov002_0224bd3c
        .byte 0x79, 0x15, 0x00, 0x00
        .word func_ov002_0224bdd4
        .byte 0x7a, 0x15, 0x00, 0x00
        .word func_ov002_0224be50
        .byte 0x85, 0x15, 0x00, 0x00
        .word func_ov002_0224bf3c
        .byte 0x8b, 0x15, 0x00, 0x00
        .word func_ov002_0224c2a4
        .byte 0x90, 0x15, 0x00, 0x00
        .word func_ov002_0224c034
        .byte 0x93, 0x15, 0x00, 0x00
        .word func_ov002_0224c160
        .byte 0x9c, 0x15, 0x00, 0x00
        .word func_ov002_0224c0b8
        .byte 0xa1, 0x15, 0x00, 0x00
        .word func_ov002_0224c160
        .byte 0xa3, 0x15, 0x00, 0x00
        .word func_ov002_0224c1e4
        .byte 0xac, 0x15, 0x00, 0x00
        .word func_ov002_0224c2a4
        .byte 0xb5, 0x15, 0x00, 0x00
        .word func_ov002_0224c358
        .byte 0xb6, 0x15, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0xb9, 0x15, 0x00, 0x00
        .word func_ov002_0224c440
        .byte 0xbc, 0x15, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xd0, 0x15, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0xd4, 0x15, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0xdd, 0x15, 0x00, 0x00
        .word func_ov002_0224b550
        .byte 0xe0, 0x15, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xe2, 0x15, 0x00, 0x00
        .word func_ov002_0224c4e8
        .byte 0xe6, 0x15, 0x00, 0x00
        .word func_ov002_0224c57c
        .byte 0xed, 0x15, 0x00, 0x00
        .word func_ov002_0224c620
        .byte 0x10, 0x16, 0x00, 0x00
        .word func_ov002_0224c69c
        .byte 0x11, 0x16, 0x00, 0x00
        .word func_ov002_0224c69c
        .byte 0x12, 0x16, 0x00, 0x00
        .word func_ov002_0224c8c4
        .byte 0x16, 0x16, 0x00, 0x00
        .word func_ov002_0224c980
        .byte 0x19, 0x16, 0x00, 0x00
        .word func_ov002_0224ca08
        .byte 0x26, 0x16, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x28, 0x16, 0x00, 0x00
        .word func_ov002_0224cc54
        .byte 0x29, 0x16, 0x00, 0x00
        .word func_ov002_0224cac4
        .byte 0x2c, 0x16, 0x00, 0x00
        .word func_ov002_0224cbfc
        .byte 0x30, 0x16, 0x00, 0x00
        .word func_ov002_02248ce8
        .byte 0x31, 0x16, 0x00, 0x00
        .word func_ov002_02248e4c
        .byte 0x38, 0x16, 0x00, 0x00
        .word func_ov002_02248ce8
        .byte 0x42, 0x16, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x47, 0x16, 0x00, 0x00
        .word func_ov002_0224d8b4
        .byte 0x4a, 0x16, 0x00, 0x00
        .word func_ov002_0224d938
        .byte 0x56, 0x16, 0x00, 0x00
        .word func_ov002_0224cc54
        .byte 0x5a, 0x16, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x5b, 0x16, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0x64, 0x16, 0x00, 0x00
        .word func_ov002_0224cc90
        .byte 0x6b, 0x16, 0x00, 0x00
        .word func_ov002_0224cd18
        .byte 0x78, 0x16, 0x00, 0x00
        .word func_ov002_0224cd9c
        .byte 0x7d, 0x16, 0x00, 0x00
        .word func_ov002_0224c69c
        .byte 0x7e, 0x16, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x86, 0x16, 0x00, 0x00
        .word func_ov002_0224ce18
        .byte 0x89, 0x16, 0x00, 0x00
        .word func_ov002_0224cf14
        .byte 0x9f, 0x16, 0x00, 0x00
        .word func_ov002_0224cf98
        .byte 0xa4, 0x16, 0x00, 0x00
        .word func_ov002_0224d044
        .byte 0xa8, 0x16, 0x00, 0x00
        .word func_ov002_0224d0f8
        .byte 0xb9, 0x16, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xbc, 0x16, 0x00, 0x00
        .word func_ov002_0224d938
        .byte 0xc0, 0x16, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xc1, 0x16, 0x00, 0x00
        .word func_ov002_0224d19c
        .byte 0xc2, 0x16, 0x00, 0x00
        .word func_ov002_0224d1f0
        .byte 0xc4, 0x16, 0x00, 0x00
        .word func_ov002_0224d2ec
        .byte 0xc5, 0x16, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xc6, 0x16, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xc7, 0x16, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xc8, 0x16, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xc9, 0x16, 0x00, 0x00
        .word func_ov002_0224d374
        .byte 0xcb, 0x16, 0x00, 0x00
        .word func_ov002_0224d374
        .byte 0xd5, 0x16, 0x00, 0x00
        .word func_ov002_0224d424
        .byte 0xd6, 0x16, 0x00, 0x00
        .word func_ov002_0224d4ac
        .byte 0xd8, 0x16, 0x00, 0x00
        .word func_ov002_0224d510
        .byte 0xe4, 0x16, 0x00, 0x00
        .word func_ov002_0224d374
        .byte 0xf6, 0x16, 0x00, 0x00
        .word func_ov002_02248f60
        .byte 0xf8, 0x16, 0x00, 0x00
        .word func_ov002_02248ce8
        .byte 0xfd, 0x16, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0x0c, 0x17, 0x00, 0x00
        .word func_ov002_0224d5c8
        .byte 0x12, 0x17, 0x00, 0x00
        .word func_ov002_0224d510
        .byte 0x13, 0x17, 0x00, 0x00
        .word func_ov002_0224c69c
        .byte 0x14, 0x17, 0x00, 0x00
        .word func_ov002_0224d660
        .byte 0x15, 0x17, 0x00, 0x00
        .word func_ov002_0224d718
        .byte 0x17, 0x17, 0x00, 0x00
        .word func_ov002_0224d794
        .byte 0x27, 0x17, 0x00, 0x00
        .word func_ov002_0224d818
        .byte 0x41, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x45, 0x17, 0x00, 0x00
        .word func_ov002_0224d938
        .byte 0x46, 0x17, 0x00, 0x00
        .word func_ov002_0224b68c
        .byte 0x48, 0x17, 0x00, 0x00
        .word func_ov002_0224da7c
        .byte 0x54, 0x17, 0x00, 0x00
        .word func_ov002_0224d818
        .byte 0x58, 0x17, 0x00, 0x00
        .word func_ov002_0224db94
        .byte 0x5c, 0x17, 0x00, 0x00
        .word func_ov002_0224dafc
        .byte 0x64, 0x17, 0x00, 0x00
        .word func_ov002_0224db94
        .byte 0x68, 0x17, 0x00, 0x00
        .word func_ov002_0224dc24
        .byte 0x69, 0x17, 0x00, 0x00
        .word func_ov002_0224ddf0
        .byte 0x88, 0x17, 0x00, 0x00
        .word func_ov002_0224de94
        .byte 0x8a, 0x17, 0x00, 0x00
        .word func_ov002_022483ac
        .byte 0x8c, 0x17, 0x00, 0x00
        .word func_ov002_0224df78
        .byte 0x95, 0x17, 0x00, 0x00
        .word func_ov002_0224e018
        .byte 0x96, 0x17, 0x00, 0x00
        .word func_ov002_0224e0dc
        .byte 0x9a, 0x17, 0x00, 0x00
        .word func_ov002_0224e184
        .byte 0xa2, 0x17, 0x00, 0x00
        .word func_ov002_0224e230
        .byte 0xaf, 0x17, 0x00, 0x00
        .word func_ov002_0224e374
        .byte 0xb2, 0x17, 0x00, 0x00
        .word func_ov002_0224e2b8
        .byte 0xb7, 0x17, 0x00, 0x00
        .word func_ov002_0224b3b0
        .byte 0xbe, 0x17, 0x00, 0x00
        .word func_ov002_0224d510
        .byte 0xc3, 0x17, 0x00, 0x00
        .word func_ov002_0224bdd4
        .byte 0xc5, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xc9, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd1, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd2, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd3, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd5, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd7, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd8, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd9, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xda, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xdd, 0x17, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0xe5, 0x17, 0x00, 0x00
        .word func_ov002_0224e390
        .byte 0xe6, 0x17, 0x00, 0x00
        .word func_ov002_0224e390
        .byte 0xf1, 0x17, 0x00, 0x00
        .word func_ov002_0224e490
        .byte 0xf4, 0x17, 0x00, 0x00
        .word func_ov002_0224e518
        .byte 0xf5, 0x17, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xf7, 0x17, 0x00, 0x00
        .word func_ov002_0224e660
        .byte 0xf8, 0x17, 0x00, 0x00
        .word func_ov002_0224e6e8
        .byte 0xf9, 0x17, 0x00, 0x00
        .word func_ov002_0224e78c
        .byte 0x07, 0x18, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x0b, 0x18, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x0c, 0x18, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x11, 0x18, 0x00, 0x00
        .word func_ov002_0224c0b8
        .byte 0x12, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x14, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x17, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x18, 0x18, 0x00, 0x00
        .word func_ov002_0224e840
        .byte 0x20, 0x18, 0x00, 0x00
        .word func_ov002_02249b88
        .byte 0x21, 0x18, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0x22, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x3c, 0x18, 0x00, 0x00
        .word func_ov002_02249310
        .byte 0x3d, 0x18, 0x00, 0x00
        .word func_ov002_0224e8fc
        .byte 0x45, 0x18, 0x00, 0x00
        .word func_ov002_0224e9cc
        .byte 0x47, 0x18, 0x00, 0x00
        .word func_ov002_0224ea54
        .byte 0x4c, 0x18, 0x00, 0x00
        .word func_ov002_0224cbfc
        .byte 0x5d, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x5e, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x64, 0x18, 0x00, 0x00
        .word func_ov002_0224eab4
        .byte 0x67, 0x18, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0x70, 0x18, 0x00, 0x00
        .word func_ov002_0224eb3c
        .byte 0x71, 0x18, 0x00, 0x00
        .word func_ov002_0224eb3c
        .byte 0x72, 0x18, 0x00, 0x00
        .word func_ov002_0224eb3c
        .byte 0x76, 0x18, 0x00, 0x00
        .word func_ov002_0224ed8c
        .byte 0x79, 0x18, 0x00, 0x00
        .word func_ov002_0224915c
        .byte 0x7a, 0x18, 0x00, 0x00
        .word func_ov002_0224ee48
        .byte 0x7e, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x7f, 0x18, 0x00, 0x00
        .word func_ov002_0224eeac
        .byte 0x80, 0x18, 0x00, 0x00
        .word func_ov002_0224ef84
        .byte 0x81, 0x18, 0x00, 0x00
        .word func_ov002_0224f024
        .byte 0x89, 0x18, 0x00, 0x00
        .word func_ov002_0224f0c4
        .byte 0x95, 0x18, 0x00, 0x00
        .word func_ov002_0224f178
        .byte 0x9a, 0x18, 0x00, 0x00
        .word func_ov002_0224a3d0
        .byte 0x9e, 0x18, 0x00, 0x00
        .word func_ov002_0224f370
        .byte 0x9f, 0x18, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0xa3, 0x18, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xb4, 0x18, 0x00, 0x00
        .word func_ov002_0224a580
        .byte 0xc5, 0x18, 0x00, 0x00
        .word func_ov002_0224f3e4
        .byte 0xcb, 0x18, 0x00, 0x00
        .word func_ov002_0224f4a0
        .byte 0xcc, 0x18, 0x00, 0x00
        .word func_ov002_0224f548
        .byte 0xd4, 0x18, 0x00, 0x00
        .word func_ov002_0224f5fc
        .byte 0xd9, 0x18, 0x00, 0x00
        .word func_ov002_0224f74c
        .byte 0xda, 0x18, 0x00, 0x00
        .word func_ov002_0224f7a0
        .byte 0xe0, 0x18, 0x00, 0x00
        .word func_ov002_0224aa14
        .byte 0xf4, 0x18, 0x00, 0x00
        .word func_ov002_0224e390
        .byte 0xf7, 0x18, 0x00, 0x00
        .word func_ov002_0224f824
        .byte 0xf8, 0x18, 0x00, 0x00
        .word func_ov002_0224f8ac
        .byte 0xfe, 0x18, 0x00, 0x00
        .word func_ov002_0224f910
        .byte 0x00, 0x19, 0x00, 0x00
        .word func_ov002_0224f9c0
        .byte 0x07, 0x19, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x08, 0x19, 0x00, 0x00
        .word func_ov002_0224fa6c
        .byte 0x0a, 0x19, 0x00, 0x00
        .word func_ov002_02249b88
        .byte 0x18, 0x19, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x19, 0x19, 0x00, 0x00
        .word func_ov002_02248bc0
        .byte 0x1e, 0x19, 0x00, 0x00
        .word func_ov002_0224d510
        .byte 0x1f, 0x19, 0x00, 0x00
        .word func_ov002_0224fad8
        .byte 0x20, 0x19, 0x00, 0x00
        .word func_ov002_0224fb58
        .byte 0x21, 0x19, 0x00, 0x00
        .word func_ov002_0224fcd4
        .byte 0x27, 0x19, 0x00, 0x00
        .word func_ov002_0224fd94
        .byte 0x2b, 0x19, 0x00, 0x00
        .word func_ov002_0224fe84
        .byte 0x35, 0x19, 0x00, 0x00
        .word func_ov002_0224ff28
        .byte 0x38, 0x19, 0x00, 0x00
        .word func_ov002_02250044
        .byte 0x39, 0x19, 0x00, 0x00
        .word func_ov002_02250234
        .byte 0x3a, 0x19, 0x00, 0x00
        .word func_ov002_02250350
        .byte 0x44, 0x19, 0x00, 0x00
        .word func_ov002_022503d8
        .byte 0x4f, 0x19, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0x51, 0x19, 0x00, 0x00
        .word func_ov002_02250498
        .byte 0x5c, 0x19, 0x00, 0x00
        .word func_ov002_0224c69c
        .byte 0x6a, 0x19, 0x00, 0x00
        .word func_ov002_02250540
        .byte 0x6f, 0x19, 0x00, 0x00
        .word func_ov002_022505e8
        .byte 0x71, 0x19, 0x00, 0x00
        .word func_ov002_02249f68
        .byte 0x72, 0x19, 0x00, 0x00
        .word func_ov002_02250670
        .byte 0x73, 0x19, 0x00, 0x00
        .word func_ov002_0225070c
        .byte 0x74, 0x19, 0x00, 0x00
        .word func_ov002_022507c0
        .byte 0x78, 0x19, 0x00, 0x00
        .word func_ov002_0224be50
        .byte 0x79, 0x19, 0x00, 0x00
        .word func_ov002_0225085c
        .byte 0x7c, 0x19, 0x00, 0x00
        .word func_ov002_02250a28
        .byte 0x8d, 0x19, 0x00, 0x00
        .word func_ov002_02250b34
        .byte 0x8e, 0x19, 0x00, 0x00
        .word func_ov002_02250b44
        .byte 0x90, 0x19, 0x00, 0x00
        .word func_ov002_02249b88
        .byte 0x96, 0x19, 0x00, 0x00
        .word func_ov002_02250d14
        .byte 0xa7, 0x19, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0xac, 0x19, 0x00, 0x00
        .word func_ov002_02250d9c
        .byte 0xad, 0x19, 0x00, 0x00
        .word func_ov002_02250e40
        .byte 0xae, 0x19, 0x00, 0x00
        .word func_ov002_02251104
        .byte 0xb1, 0x19, 0x00, 0x00
        .word func_ov002_0224c69c
        .byte 0xb5, 0x19, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xb6, 0x19, 0x00, 0x00
        .word func_ov002_022511bc
        .byte 0xc0, 0x19, 0x00, 0x00
        .word func_ov002_0224b550
        .byte 0xc5, 0x19, 0x00, 0x00
        .word func_ov002_022512a4
        .byte 0xca, 0x19, 0x00, 0x00
        .word func_ov002_0224a580
        .byte 0xd7, 0x19, 0x00, 0x00
        .word func_ov002_02251380
        .byte 0xd8, 0x19, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xdc, 0x19, 0x00, 0x00
        .word func_ov002_02251484
        .byte 0xdd, 0x19, 0x00, 0x00
        .word func_ov002_02251484
        .byte 0xec, 0x19, 0x00, 0x00
        .word func_ov002_022515b0
        .byte 0xf4, 0x19, 0x00, 0x00
        .word func_ov002_0224c57c
        .byte 0x03, 0x1a, 0x00, 0x00
        .word func_ov002_0225163c
        .byte 0x05, 0x1a, 0x00, 0x00
        .word func_ov002_0225170c
        .byte 0x0c, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x10, 0x1a, 0x00, 0x00
        .word func_ov002_022517c0
        .byte 0x12, 0x1a, 0x00, 0x00
        .word func_ov002_02251844
        .byte 0x13, 0x1a, 0x00, 0x00
        .word func_ov002_02251908
        .byte 0x16, 0x1a, 0x00, 0x00
        .word func_ov002_02251b14
        .byte 0x17, 0x1a, 0x00, 0x00
        .word func_ov002_022519c4
        .byte 0x1a, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x24, 0x1a, 0x00, 0x00
        .word func_ov002_02251bb0
        .byte 0x25, 0x1a, 0x00, 0x00
        .word func_ov002_02251bb0
        .byte 0x26, 0x1a, 0x00, 0x00
        .word func_ov002_02251c3c
        .byte 0x2b, 0x1a, 0x00, 0x00
        .word func_ov002_02251d00
        .byte 0x2c, 0x1a, 0x00, 0x00
        .word func_ov002_02251d00
        .byte 0x2d, 0x1a, 0x00, 0x00
        .word func_ov002_02251d00
        .byte 0x2e, 0x1a, 0x00, 0x00
        .word func_ov002_02251d00
        .byte 0x31, 0x1a, 0x00, 0x00
        .word func_ov002_02251d78
        .byte 0x36, 0x1a, 0x00, 0x00
        .word func_ov002_02251df4
        .byte 0x42, 0x1a, 0x00, 0x00
        .word func_ov002_0224e8fc
        .byte 0x5c, 0x1a, 0x00, 0x00
        .word func_ov002_02251ec0
        .byte 0x5d, 0x1a, 0x00, 0x00
        .word func_ov002_02251f70
        .byte 0x61, 0x1a, 0x00, 0x00
        .word func_ov002_02252014
        .byte 0x64, 0x1a, 0x00, 0x00
        .word func_ov002_022520f0
        .byte 0x6a, 0x1a, 0x00, 0x00
        .word func_ov002_022521ac
        .byte 0x6b, 0x1a, 0x00, 0x00
        .word func_ov002_02252240
        .byte 0x6c, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x76, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0x7b, 0x1a, 0x00, 0x00
        .word func_ov002_022523cc
        .byte 0x7c, 0x1a, 0x00, 0x00
        .word func_ov002_02252438
        .byte 0x7d, 0x1a, 0x00, 0x00
        .word func_ov002_022524a4
        .byte 0x7e, 0x1a, 0x00, 0x00
        .word func_ov002_02252558
        .byte 0x7f, 0x1a, 0x00, 0x00
        .word func_ov002_02252664
        .byte 0x80, 0x1a, 0x00, 0x00
        .word func_ov002_02252734
        .byte 0x8d, 0x1a, 0x00, 0x00
        .word func_ov002_022527b8
        .byte 0x8f, 0x1a, 0x00, 0x00
        .word func_ov002_02252868
        .byte 0x97, 0x1a, 0x00, 0x00
        .word func_ov002_02252914
        .byte 0x98, 0x1a, 0x00, 0x00
        .word func_ov002_02252998
        .byte 0x9b, 0x1a, 0x00, 0x00
        .word func_ov002_02252a58
        .byte 0xa1, 0x1a, 0x00, 0x00
        .word func_ov002_0224d718
        .byte 0xa2, 0x1a, 0x00, 0x00
        .word func_ov002_02252af8
        .byte 0xa9, 0x1a, 0x00, 0x00
        .word func_ov002_02252b80
        .byte 0xae, 0x1a, 0x00, 0x00
        .word func_ov002_02252c08
        .byte 0xaf, 0x1a, 0x00, 0x00
        .word func_ov002_02252c08
        .byte 0xb0, 0x1a, 0x00, 0x00
        .word func_ov002_02252c08
        .byte 0xb1, 0x1a, 0x00, 0x00
        .word func_ov002_02252ca4
        .byte 0xd6, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xd7, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xdc, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xdd, 0x1a, 0x00, 0x00
        .word func_ov002_0224848c
        .byte 0xf4, 0x1a, 0x00, 0x00
        .word func_ov002_02252d2c
        .byte 0xf5, 0x1a, 0x00, 0x00
        .word func_ov002_02252d98
        .byte 0xf9, 0x1a, 0x00, 0x00
        .word func_ov002_02249268
        .byte 0xfb, 0x1a, 0x00, 0x00
        .word func_ov002_02252e54
        .byte 0x17, 0x1b, 0x00, 0x00
        .word func_ov002_02252f64
        .byte 0x1d, 0x1b, 0x00, 0x00
        .word func_ov002_02253000
        .byte 0x1f, 0x1b, 0x00, 0x00
        .word func_ov002_022517c0
        .byte 0x22, 0x1b, 0x00, 0x00
        .word func_ov002_022530a8
        .byte 0x25, 0x1b, 0x00, 0x00
        .word func_ov002_022499b0
        .byte 0x26, 0x1b, 0x00, 0x00
        .word func_ov002_02253154
        .byte 0x27, 0x1b, 0x00, 0x00
        .word func_ov002_022531bc
        .byte 0x44, 0x1b, 0x00, 0x00
        .word func_ov002_0224b550
        .byte 0x53, 0x1b, 0x00, 0x00
        .word func_ov002_02253304
        .byte 0x62, 0x1b, 0x00, 0x00
        .word func_ov002_0224ee48
        .byte 0x65, 0x1b, 0x00, 0x00
        .word func_ov002_0224b3b0
        .byte 0xfe, 0xff, 0x00, 0x00
        .word func_ov002_02259b4c
        .byte 0xff, 0xff, 0x00, 0x00
        .word func_ov002_02253390
