; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov002
; Range:  0x022cd090..0x022cd300 (624 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern data_020ce420
        .extern data_020ce4f0
        .extern data_020ce650
        .extern data_020ced10
        .extern data_020ceea0
        .extern data_020cef50
        .extern data_020cf010
        .extern data_020cf0f0
        .extern data_020cf640
        .extern data_020cf690
        .extern data_020cf9c0
        .extern data_020cfa90
        .extern data_020cfb90
        .extern data_020cfd10
        .extern data_020d0480
        .extern data_020d0dd0
        .extern data_020d0e30
        .extern data_020d0e80
        .extern data_020d0ef0
        .extern data_020d0f60
        .extern data_020d0fc0
        .extern data_020d1200
        .extern data_020d12a0
        .extern data_020d13a0
        .extern data_020d1c30
        .extern data_020d1c90
        .extern data_020d1fe0
        .extern data_020d2030
        .extern data_020d20b0
        .extern data_020d2120
        .extern data_020d21d0
        .extern data_020d2280
        .extern data_020d2340
        .extern data_020d23f0
        .extern data_020d24a0
        .extern data_020d2550
        .extern data_020d2610
        .extern data_020d26c0
        .extern data_020d2780
        .extern data_020d28d0
        .extern data_020d2a60
        .extern data_020d2b80
        .extern data_020d2c30
        .extern data_020d2ce0
        .extern data_020d2d90
        .extern data_020d2e40
        .extern data_020d2ef0
        .extern data_020d2fa0
        .extern data_020d30a0
        .extern data_020d3200
        .extern data_020d36c0
        .extern data_020d37e0
        .extern data_020d38a0
        .extern data_020d3960
        .extern data_020d39c0
        .extern data_020d4420
        .extern data_020d44f0
        .extern data_020d45f0
        .extern data_020d4700
        .extern data_020d4750
        .extern data_020d4880
        .extern data_020d5110
        .extern data_020d5270
        .extern data_020d5c90
        .extern data_020d5cf0
        .extern data_020d5f00
        .extern data_020d6040
        .extern data_020d6180
        .extern data_020d62c0
        .extern data_020d6330
        .extern data_020d6450
        .extern data_020d6570
        .extern data_020e0980
        .extern data_020d6690
        .extern data_020e0d40
        .extern data_020d6880

        .global data_ov002_022cd090
data_ov002_022cd090:
        .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        .word data_020ce420
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020ce4f0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020ce650
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020ced10
        .byte 0x03, 0x00, 0x00, 0x00
        .word data_020ceea0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cef50
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cf010
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020cf0f0
        .byte 0x09, 0x00, 0x00, 0x00
        .word data_020cf640
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cf690
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020cf9c0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cfa90
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020cfb90
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020cfd10
        .byte 0x06, 0x00, 0x00, 0x00
        .word data_020d0480
        .byte 0x09, 0x00, 0x00, 0x00
        .word data_020d0dd0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0e30
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0e80
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0ef0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0f60
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d0fc0
        .byte 0x03, 0x00, 0x00, 0x00
        .word data_020d1200
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d12a0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d13a0
        .byte 0x0f, 0x00, 0x00, 0x00
        .word data_020d1c30
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d1c90
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d1fe0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2030
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d20b0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2120
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d21d0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2280
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2340
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d23f0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d24a0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2550
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2610
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d26c0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2780
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d28d0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2a60
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2b80
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2c30
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2ce0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2d90
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2e40
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2ef0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d2fa0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d30a0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d3200
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020d36c0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d37e0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d38a0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d3960
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d39c0
        .byte 0x08, 0x00, 0x00, 0x00
        .word data_020d4420
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d44f0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d45f0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d4700
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d4750
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d4880
        .byte 0x0f, 0x00, 0x00, 0x00
        .word data_020d5110
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d5270
        .byte 0x09, 0x00, 0x00, 0x00
        .word data_020d5c90
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d5cf0
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d5f00
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d6040
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d6180
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d62c0
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d6330
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d6450
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d6570
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020e0980
        .byte 0x02, 0x00, 0x00, 0x00
        .word data_020d6690
        .byte 0x06, 0x00, 0x00, 0x00
        .word data_020e0d40
        .byte 0x01, 0x00, 0x00, 0x00
        .word data_020d6880
        .byte 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        .byte 0x00, 0x00, 0x00, 0x00
