; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov004
; Range:  0x02200dbc..0x02200de8 (44 bytes, 2 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .rodata

        .extern data_ov004_02209aa0
        .extern data_ov004_02209ab8
        .extern data_ov004_02209ab0
        .extern data_ov004_02209aa8

        .global data_ov004_02200dbc
data_ov004_02200dbc:
        .word data_ov004_02209aa0
        .word data_ov004_02209ab8
        .word data_ov004_02209ab0
        .word data_ov004_02209aa8
        .byte 0x80, 0x00, 0x00, 0x00

        .global data_ov004_02200dd0
data_ov004_02200dd0:
        .byte 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10
        .byte 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x30
        .byte 0x00, 0x06, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00
