; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov007
; Range:  0x021b30c0..0x021b3318 (600 bytes, 1 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern data_ov007_021b3078
        .extern data_020d21d0
        .extern data_ov007_021b3344
        .extern data_020d2280
        .extern data_ov007_021b3354
        .extern data_ov007_021b3082
        .extern data_ov007_021b3094
        .extern data_ov007_021b30ae
        .extern data_020d2340
        .extern data_ov007_021b3458
        .extern data_020d23f0
        .extern data_ov007_021b3374
        .extern data_020d24a0
        .extern data_ov007_021b3364
        .extern data_020d2550
        .extern data_ov007_021b3324
        .extern data_020d2610
        .extern data_ov007_021b3334
        .extern data_020d26c0
        .extern data_ov007_021b3384
        .extern data_ov007_021b3088
        .extern data_ov007_021b309c
        .extern data_ov007_021b30a4
        .extern data_020d2780
        .extern data_ov007_021b341c
        .extern data_020d28d0
        .extern data_ov007_021b3430
        .extern data_020d2a60
        .extern data_ov007_021b3444
        .extern data_020d2b80
        .extern data_ov007_021b33f4
        .extern data_020d2c30
        .extern data_ov007_021b33a4
        .extern data_020d2ce0
        .extern data_ov007_021b33cc
        .extern data_020d2d90
        .extern data_ov007_021b33e0
        .extern data_020d2e40
        .extern data_ov007_021b3408
        .extern data_020d2ef0
        .extern data_ov007_021b33b8
        .extern data_ov007_021b308e
        .extern data_ov007_021b307c
        .extern data_020d0f60
        .extern func_ov006_021b3318

        .global data_ov007_021b30c0
data_ov007_021b30c0:
        .byte 0x61, 0x00, 0x00, 0x00, 0x61, 0x00, 0x00, 0x00
        .byte 0x61, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d21d0
        .word data_ov007_021b3344
        .byte 0x64, 0x00, 0x00, 0x00, 0x63, 0x00, 0x00, 0x00
        .byte 0x62, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2280
        .word data_ov007_021b3354
        .byte 0x67, 0x00, 0x00, 0x00, 0x66, 0x00, 0x00, 0x00
        .byte 0x65, 0x00, 0x00, 0x00
        .word data_ov007_021b3082
        .word data_ov007_021b3094
        .word data_ov007_021b30ae
        .word data_020d2340
        .word data_ov007_021b3458
        .byte 0x68, 0x00, 0x00, 0x00, 0x68, 0x00, 0x00, 0x00
        .byte 0x68, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d23f0
        .word data_ov007_021b3374
        .byte 0x69, 0x00, 0x00, 0x00, 0x69, 0x00, 0x00, 0x00
        .byte 0x69, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d24a0
        .word data_ov007_021b3364
        .byte 0x6a, 0x00, 0x00, 0x00, 0x6a, 0x00, 0x00, 0x00
        .byte 0x6a, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2550
        .word data_ov007_021b3324
        .byte 0x6b, 0x00, 0x00, 0x00, 0x6b, 0x00, 0x00, 0x00
        .byte 0x6b, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2610
        .word data_ov007_021b3334
        .byte 0x6c, 0x00, 0x00, 0x00, 0x6c, 0x00, 0x00, 0x00
        .byte 0x6c, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d26c0
        .word data_ov007_021b3384
        .byte 0x6f, 0x00, 0x00, 0x00, 0x6e, 0x00, 0x00, 0x00
        .byte 0x6d, 0x00, 0x00, 0x00
        .word data_ov007_021b3088
        .word data_ov007_021b309c
        .word data_ov007_021b30a4
        .word data_020d2780
        .word data_ov007_021b341c
        .byte 0x72, 0x00, 0x00, 0x00, 0x71, 0x00, 0x00, 0x00
        .byte 0x70, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d28d0
        .word data_ov007_021b3430
        .byte 0x75, 0x00, 0x00, 0x00, 0x74, 0x00, 0x00, 0x00
        .byte 0x73, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2a60
        .word data_ov007_021b3444
        .byte 0x78, 0x00, 0x00, 0x00, 0x77, 0x00, 0x00, 0x00
        .byte 0x76, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2b80
        .word data_ov007_021b33f4
        .byte 0x7b, 0x00, 0x00, 0x00, 0x7a, 0x00, 0x00, 0x00
        .byte 0x79, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2c30
        .word data_ov007_021b33a4
        .byte 0x7e, 0x00, 0x00, 0x00, 0x7d, 0x00, 0x00, 0x00
        .byte 0x7c, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2ce0
        .word data_ov007_021b33cc
        .byte 0x7f, 0x00, 0x00, 0x00, 0x7f, 0x00, 0x00, 0x00
        .byte 0x7f, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2d90
        .word data_ov007_021b33e0
        .byte 0x80, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00
        .byte 0x80, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2e40
        .word data_ov007_021b3408
        .byte 0x81, 0x00, 0x00, 0x00, 0x81, 0x00, 0x00, 0x00
        .byte 0x81, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_020d2ef0
        .word data_ov007_021b33b8
        .byte 0x82, 0x00, 0x00, 0x00, 0x82, 0x00, 0x00, 0x00
        .byte 0x82, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b308e
        .word data_ov007_021b307c
        .word data_020d0f60
        .word func_ov006_021b3318
        .byte 0x31, 0x00, 0x00, 0x00, 0x31, 0x00, 0x00, 0x00
        .byte 0x31, 0x00, 0x00, 0x00
        .word data_ov007_021b3078
        .word data_ov007_021b3078
        .word data_ov007_021b3078
