; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov002
; Range:  0x022cac38..0x022cb8a8 (3184 bytes, 2 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern func_ov002_022483a4
        .extern func_ov002_022481e8
        .extern func_ov002_022482c4
        .extern func_ov002_0224834c
        .extern func_ov002_02248934
        .extern func_ov002_022489c8
        .extern func_ov002_02248ad8
        .extern func_ov002_02248c00
        .extern func_ov002_02248a74
        .extern func_ov002_02248c88
        .extern func_ov002_02248fa8
        .extern func_ov002_02248d64
        .extern func_ov002_02248e78
        .extern func_ov002_02248ef4
        .extern func_ov002_02249074
        .extern func_ov002_022490e0
        .extern func_ov002_02249180
        .extern func_ov002_02249228
        .extern func_ov002_022492b0
        .extern func_ov002_02249308
        .extern func_ov002_022493bc
        .extern func_ov002_022494a4
        .extern func_ov002_02249730
        .extern func_ov002_02249830
        .extern func_ov002_022498c8
        .extern func_ov002_02249b40
        .extern func_ov002_0224996c
        .extern func_ov002_02249c04
        .extern func_ov002_0224af34
        .extern func_ov002_022495cc
        .extern func_ov002_02249aa0
        .extern func_ov002_022496a8
        .extern func_ov002_02249a08
        .extern func_ov002_02249cb4
        .extern func_ov002_02249d9c
        .extern func_ov002_02249ddc
        .extern func_ov002_02249e80
        .extern func_ov002_02249f50
        .extern func_ov002_0224a038
        .extern func_ov002_0224a0fc
        .extern func_ov002_0224a1a4
        .extern func_ov002_0224a244
        .extern func_ov002_0224a498
        .extern func_ov002_0224a530
        .extern func_ov002_0224a60c
        .extern func_ov002_0224a690
        .extern func_ov002_0224a86c
        .extern func_ov002_0224a2e8
        .extern func_ov002_0224a410
        .extern func_ov002_0224a92c
        .extern func_ov002_0224a9d8
        .extern func_ov002_0224aa5c
        .extern func_ov002_0224aae4
        .extern func_ov002_0224ab84
        .extern func_ov002_0224ac7c
        .extern func_ov002_0224add0
        .extern func_ov002_0224afc8
        .extern func_ov002_0224b070
        .extern func_ov002_0224b0f8
        .extern func_ov002_0224b468
        .extern func_ov002_0224b860
        .extern func_ov002_0224b194
        .extern func_ov002_0224b1f8
        .extern func_ov002_0224b2c8
        .extern func_ov002_0224b37c
        .extern func_ov002_0224b3b4
        .extern func_ov002_0224b4cc
        .extern func_ov002_0224b5a4
        .extern func_ov002_0224b760
        .extern func_ov002_0224baf0
        .extern func_ov002_0224b8e4
        .extern func_ov002_0224ba00
        .extern func_ov002_0224ba6c
        .extern func_ov002_0224bba0
        .extern func_ov002_0224bc54
        .extern func_ov002_0224bcec
        .extern func_ov002_0224bd68
        .extern func_ov002_0224be54
        .extern func_ov002_0224c1bc
        .extern func_ov002_0224bf4c
        .extern func_ov002_0224c078
        .extern func_ov002_0224bfd0
        .extern func_ov002_0224c0fc
        .extern func_ov002_0224c270
        .extern func_ov002_0224c358
        .extern func_ov002_0224c400
        .extern func_ov002_0224c494
        .extern func_ov002_0224c538
        .extern func_ov002_0224c5b4
        .extern func_ov002_0224c7dc
        .extern func_ov002_0224c898
        .extern func_ov002_0224c920
        .extern func_ov002_0224cb6c
        .extern func_ov002_0224c9dc
        .extern func_ov002_0224cb14
        .extern func_ov002_0224d7cc
        .extern func_ov002_0224d850
        .extern func_ov002_0224cba8
        .extern func_ov002_0224cc30
        .extern func_ov002_0224ccb4
        .extern func_ov002_0224cd30
        .extern func_ov002_0224ce2c
        .extern func_ov002_0224ceb0
        .extern func_ov002_0224cf5c
        .extern func_ov002_0224d010
        .extern func_ov002_0224d0b4
        .extern func_ov002_0224d108
        .extern func_ov002_0224d204
        .extern func_ov002_0224d28c
        .extern func_ov002_0224d33c
        .extern func_ov002_0224d3c4
        .extern func_ov002_0224d428
        .extern func_ov002_0224d4e0
        .extern func_ov002_0224d578
        .extern func_ov002_0224d630
        .extern func_ov002_0224d6ac
        .extern func_ov002_0224d730
        .extern func_ov002_0224d994
        .extern func_ov002_0224daac
        .extern func_ov002_0224da14
        .extern func_ov002_0224db3c
        .extern func_ov002_0224dd08
        .extern func_ov002_0224ddac
        .extern func_ov002_0224de90
        .extern func_ov002_0224df30
        .extern func_ov002_0224dff4
        .extern func_ov002_0224e09c
        .extern func_ov002_0224e148
        .extern func_ov002_0224e28c
        .extern func_ov002_0224e1d0
        .extern func_ov002_0224e2a8
        .extern func_ov002_0224e3a8
        .extern func_ov002_0224e430
        .extern func_ov002_0224e578
        .extern func_ov002_0224e600
        .extern func_ov002_0224e6a4
        .extern func_ov002_0224e758
        .extern func_ov002_0224e814
        .extern func_ov002_0224e8e4
        .extern func_ov002_0224e96c
        .extern func_ov002_0224e9cc
        .extern func_ov002_0224ea54
        .extern func_ov002_0224eca4
        .extern func_ov002_0224ed60
        .extern func_ov002_0224edc4
        .extern func_ov002_0224ee9c
        .extern func_ov002_0224ef3c
        .extern func_ov002_0224efdc
        .extern func_ov002_0224f090
        .extern func_ov002_0224f288
        .extern func_ov002_0224f2fc
        .extern func_ov002_0224f3b8
        .extern func_ov002_0224f460
        .extern func_ov002_0224f514
        .extern func_ov002_0224f664
        .extern func_ov002_0224f6b8
        .extern func_ov002_0224f73c
        .extern func_ov002_0224f7c4
        .extern func_ov002_0224f828
        .extern func_ov002_0224f8d8
        .extern func_ov002_0224f984
        .extern func_ov002_0224f9f0
        .extern func_ov002_0224fa70
        .extern func_ov002_0224fbec
        .extern func_ov002_0224fcac
        .extern func_ov002_0224fd9c
        .extern func_ov002_0224fe40
        .extern func_ov002_0224ff5c
        .extern func_ov002_0225014c
        .extern func_ov002_02250268
        .extern func_ov002_022502f0
        .extern func_ov002_022503b0
        .extern func_ov002_02250458
        .extern func_ov002_02250500
        .extern func_ov002_02250588
        .extern func_ov002_02250624
        .extern func_ov002_022506d8
        .extern func_ov002_02250774
        .extern func_ov002_02250940
        .extern func_ov002_02250a4c
        .extern func_ov002_02250a5c
        .extern func_ov002_02250c2c
        .extern func_ov002_02250cb4
        .extern func_ov002_02250d58
        .extern func_ov002_0225101c
        .extern func_ov002_022510d4
        .extern func_ov002_022511bc
        .extern func_ov002_02251298
        .extern func_ov002_0225139c
        .extern func_ov002_022514c8
        .extern func_ov002_02251554
        .extern func_ov002_02251624
        .extern func_ov002_022516d8
        .extern func_ov002_0225175c
        .extern func_ov002_02251820
        .extern func_ov002_02251a2c
        .extern func_ov002_022518dc
        .extern func_ov002_02251ac8
        .extern func_ov002_02251b54
        .extern func_ov002_02251c18
        .extern func_ov002_02251c90
        .extern func_ov002_02251d0c
        .extern func_ov002_02251dd8
        .extern func_ov002_02251e88
        .extern func_ov002_02251f2c
        .extern func_ov002_02252008
        .extern func_ov002_022520c4
        .extern func_ov002_02252158
        .extern func_ov002_022522e4
        .extern func_ov002_02252350
        .extern func_ov002_022523bc
        .extern func_ov002_02252470
        .extern func_ov002_0225257c
        .extern func_ov002_0225264c
        .extern func_ov002_022526d0
        .extern func_ov002_02252780
        .extern func_ov002_0225282c
        .extern func_ov002_022528b0
        .extern func_ov002_02252970
        .extern func_ov002_02252a10
        .extern func_ov002_02252a98
        .extern func_ov002_02252b20
        .extern func_ov002_02252bbc
        .extern func_ov002_02252c44
        .extern func_ov002_02252cb0
        .extern func_ov002_02252d6c
        .extern func_ov002_02252e7c
        .extern func_ov002_02252f18
        .extern func_ov002_02252fc0
        .extern func_ov002_0225306c
        .extern func_ov002_022530d4
        .extern func_ov002_0225321c
        .extern func_ov002_02259a64
        .extern func_ov002_022532a8
        .extern func_ov002_0225ab80
        .extern func_ov002_0225acbc
        .extern func_ov002_0225b250
        .extern func_ov002_0225bc64
        .extern func_ov002_0225c010
        .extern func_ov002_0225c0f0
        .extern func_ov002_0225c978
        .extern func_ov002_0225d540
        .extern func_ov002_0225e244
        .extern func_ov002_0225e788
        .extern func_ov002_0225ed60
        .extern func_ov002_02260bf8
        .extern func_ov002_02261b5c
        .extern func_ov002_02262650

        .global data_ov002_022cac38
data_ov002_022cac38:
        .word func_ov002_022483a4
        .byte 0xd6, 0x0f, 0x00, 0x00
        .word func_ov002_022481e8
        .byte 0x0c, 0x10, 0x00, 0x00
        .word func_ov002_022482c4
        .byte 0x51, 0x10, 0x00, 0x00
        .word func_ov002_0224834c
        .byte 0xe4, 0x10, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x38, 0x11, 0x00, 0x00
        .word func_ov002_02248934
        .byte 0x4a, 0x11, 0x00, 0x00
        .word func_ov002_022489c8
        .byte 0x4f, 0x11, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x52, 0x11, 0x00, 0x00
        .word func_ov002_02248c00
        .byte 0xa0, 0x11, 0x00, 0x00
        .word func_ov002_02248a74
        .byte 0xe4, 0x11, 0x00, 0x00
        .word func_ov002_02248c88
        .byte 0x32, 0x12, 0x00, 0x00
        .word func_ov002_02248fa8
        .byte 0x93, 0x12, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x94, 0x12, 0x00, 0x00
        .word func_ov002_02248d64
        .byte 0xa4, 0x12, 0x00, 0x00
        .word func_ov002_02248e78
        .byte 0xa7, 0x12, 0x00, 0x00
        .word func_ov002_02248ef4
        .byte 0xca, 0x12, 0x00, 0x00
        .word func_ov002_02249074
        .byte 0xde, 0x12, 0x00, 0x00
        .word func_ov002_02248fa8
        .byte 0xe5, 0x12, 0x00, 0x00
        .word func_ov002_022490e0
        .byte 0xea, 0x12, 0x00, 0x00
        .word func_ov002_02249180
        .byte 0xed, 0x12, 0x00, 0x00
        .word func_ov002_02249228
        .byte 0xf4, 0x12, 0x00, 0x00
        .word func_ov002_022492b0
        .byte 0xf9, 0x12, 0x00, 0x00
        .word func_ov002_02249308
        .byte 0x03, 0x13, 0x00, 0x00
        .word func_ov002_022490e0
        .byte 0x08, 0x13, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x15, 0x13, 0x00, 0x00
        .word func_ov002_022493bc
        .byte 0x2f, 0x13, 0x00, 0x00
        .word func_ov002_022494a4
        .byte 0x33, 0x13, 0x00, 0x00
        .word func_ov002_02249730
        .byte 0x34, 0x13, 0x00, 0x00
        .word func_ov002_02249830
        .byte 0x35, 0x13, 0x00, 0x00
        .word func_ov002_02249730
        .byte 0x39, 0x13, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0x3a, 0x13, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0x3b, 0x13, 0x00, 0x00
        .word func_ov002_02249b40
        .byte 0x3c, 0x13, 0x00, 0x00
        .word func_ov002_02249730
        .byte 0x3e, 0x13, 0x00, 0x00
        .word func_ov002_02249730
        .byte 0x3f, 0x13, 0x00, 0x00
        .word func_ov002_02249730
        .byte 0x41, 0x13, 0x00, 0x00
        .word func_ov002_0224996c
        .byte 0x42, 0x13, 0x00, 0x00
        .word func_ov002_02249730
        .byte 0x59, 0x13, 0x00, 0x00
        .word func_ov002_02249c04
        .byte 0x5b, 0x13, 0x00, 0x00
        .word func_ov002_0224af34
        .byte 0x62, 0x13, 0x00, 0x00
        .word func_ov002_022495cc
        .byte 0x65, 0x13, 0x00, 0x00
        .word func_ov002_02249aa0
        .byte 0x66, 0x13, 0x00, 0x00
        .word func_ov002_02249aa0
        .byte 0x6a, 0x13, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0x79, 0x13, 0x00, 0x00
        .word func_ov002_022496a8
        .byte 0x7c, 0x13, 0x00, 0x00
        .word func_ov002_02249a08
        .byte 0x7d, 0x13, 0x00, 0x00
        .word func_ov002_02249aa0
        .byte 0x9d, 0x13, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0xa1, 0x13, 0x00, 0x00
        .word func_ov002_02249cb4
        .byte 0xed, 0x13, 0x00, 0x00
        .word func_ov002_02249d9c
        .byte 0xf5, 0x13, 0x00, 0x00
        .word func_ov002_02249ddc
        .byte 0xfe, 0x13, 0x00, 0x00
        .word func_ov002_02249e80
        .byte 0x0b, 0x14, 0x00, 0x00
        .word func_ov002_02249f50
        .byte 0x3d, 0x14, 0x00, 0x00
        .word func_ov002_0224a038
        .byte 0x45, 0x14, 0x00, 0x00
        .word func_ov002_0224a0fc
        .byte 0x46, 0x14, 0x00, 0x00
        .word func_ov002_0224a1a4
        .byte 0x49, 0x14, 0x00, 0x00
        .word func_ov002_02249ddc
        .byte 0x4c, 0x14, 0x00, 0x00
        .word func_ov002_02249ddc
        .byte 0x52, 0x14, 0x00, 0x00
        .word func_ov002_0224a244
        .byte 0x57, 0x14, 0x00, 0x00
        .word func_ov002_02249ddc
        .byte 0x66, 0x14, 0x00, 0x00
        .word func_ov002_0224a498
        .byte 0x68, 0x14, 0x00, 0x00
        .word func_ov002_0224a530
        .byte 0x6e, 0x14, 0x00, 0x00
        .word func_ov002_0224a60c
        .byte 0x6f, 0x14, 0x00, 0x00
        .word func_ov002_0224a690
        .byte 0x74, 0x14, 0x00, 0x00
        .word func_ov002_0224a86c
        .byte 0x76, 0x14, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0x80, 0x14, 0x00, 0x00
        .word func_ov002_02249228
        .byte 0x81, 0x14, 0x00, 0x00
        .word func_ov002_022489c8
        .byte 0x82, 0x14, 0x00, 0x00
        .word func_ov002_0224a410
        .byte 0x83, 0x14, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0x84, 0x14, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0x85, 0x14, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0x86, 0x14, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0x87, 0x14, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0x88, 0x14, 0x00, 0x00
        .word func_ov002_02249aa0
        .byte 0x8b, 0x14, 0x00, 0x00
        .word func_ov002_0224a9d8
        .byte 0x90, 0x14, 0x00, 0x00
        .word func_ov002_0224aa5c
        .byte 0x9c, 0x14, 0x00, 0x00
        .word func_ov002_022490e0
        .byte 0x9e, 0x14, 0x00, 0x00
        .word func_ov002_0224aae4
        .byte 0xa7, 0x14, 0x00, 0x00
        .word func_ov002_0224ab84
        .byte 0xb3, 0x14, 0x00, 0x00
        .word func_ov002_0224ac7c
        .byte 0xba, 0x14, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0xc1, 0x14, 0x00, 0x00
        .word func_ov002_0224add0
        .byte 0xc2, 0x14, 0x00, 0x00
        .word func_ov002_02249228
        .byte 0xc4, 0x14, 0x00, 0x00
        .word func_ov002_0224afc8
        .byte 0xc6, 0x14, 0x00, 0x00
        .word func_ov002_0224af34
        .byte 0xd0, 0x14, 0x00, 0x00
        .word func_ov002_0224afc8
        .byte 0xd2, 0x14, 0x00, 0x00
        .word func_ov002_0224b070
        .byte 0xd7, 0x14, 0x00, 0x00
        .word func_ov002_0224b0f8
        .byte 0xdd, 0x14, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0xe7, 0x14, 0x00, 0x00
        .word func_ov002_0224b468
        .byte 0xea, 0x14, 0x00, 0x00
        .word func_ov002_02248c00
        .byte 0xee, 0x14, 0x00, 0x00
        .word func_ov002_0224b860
        .byte 0xef, 0x14, 0x00, 0x00
        .word func_ov002_0224b194
        .byte 0xf6, 0x14, 0x00, 0x00
        .word func_ov002_0224b1f8
        .byte 0xf7, 0x14, 0x00, 0x00
        .word func_ov002_0224b2c8
        .byte 0xfd, 0x14, 0x00, 0x00
        .word func_ov002_0224b37c
        .byte 0x07, 0x15, 0x00, 0x00
        .word func_ov002_0224b3b4
        .byte 0x08, 0x15, 0x00, 0x00
        .word func_ov002_0224b3b4
        .byte 0x15, 0x15, 0x00, 0x00
        .word func_ov002_0224b468
        .byte 0x1e, 0x15, 0x00, 0x00
        .word func_ov002_0224b4cc
        .byte 0x22, 0x15, 0x00, 0x00
        .word func_ov002_0224b5a4
        .byte 0x29, 0x15, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x2f, 0x15, 0x00, 0x00
        .word func_ov002_0224b760
        .byte 0x31, 0x15, 0x00, 0x00
        .word func_ov002_0224b860
        .byte 0x34, 0x15, 0x00, 0x00
        .word func_ov002_0224baf0
        .byte 0x36, 0x15, 0x00, 0x00
        .word func_ov002_0224b8e4
        .byte 0x3b, 0x15, 0x00, 0x00
        .word func_ov002_0224ba00
        .byte 0x62, 0x15, 0x00, 0x00
        .word func_ov002_0224ba6c
        .byte 0x6a, 0x15, 0x00, 0x00
        .word func_ov002_0224baf0
        .byte 0x6d, 0x15, 0x00, 0x00
        .word func_ov002_0224bba0
        .byte 0x72, 0x15, 0x00, 0x00
        .word func_ov002_0224bc54
        .byte 0x79, 0x15, 0x00, 0x00
        .word func_ov002_0224bcec
        .byte 0x7a, 0x15, 0x00, 0x00
        .word func_ov002_0224bd68
        .byte 0x85, 0x15, 0x00, 0x00
        .word func_ov002_0224be54
        .byte 0x8b, 0x15, 0x00, 0x00
        .word func_ov002_0224c1bc
        .byte 0x90, 0x15, 0x00, 0x00
        .word func_ov002_0224bf4c
        .byte 0x93, 0x15, 0x00, 0x00
        .word func_ov002_0224c078
        .byte 0x9c, 0x15, 0x00, 0x00
        .word func_ov002_0224bfd0
        .byte 0xa1, 0x15, 0x00, 0x00
        .word func_ov002_0224c078
        .byte 0xa3, 0x15, 0x00, 0x00
        .word func_ov002_0224c0fc
        .byte 0xac, 0x15, 0x00, 0x00
        .word func_ov002_0224c1bc
        .byte 0xb5, 0x15, 0x00, 0x00
        .word func_ov002_0224c270
        .byte 0xb6, 0x15, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0xb9, 0x15, 0x00, 0x00
        .word func_ov002_0224c358
        .byte 0xbc, 0x15, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xd0, 0x15, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0xd4, 0x15, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0xdd, 0x15, 0x00, 0x00
        .word func_ov002_0224b468
        .byte 0xe0, 0x15, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xe2, 0x15, 0x00, 0x00
        .word func_ov002_0224c400
        .byte 0xe6, 0x15, 0x00, 0x00
        .word func_ov002_0224c494
        .byte 0xed, 0x15, 0x00, 0x00
        .word func_ov002_0224c538
        .byte 0x10, 0x16, 0x00, 0x00
        .word func_ov002_0224c5b4
        .byte 0x11, 0x16, 0x00, 0x00
        .word func_ov002_0224c5b4
        .byte 0x12, 0x16, 0x00, 0x00
        .word func_ov002_0224c7dc
        .byte 0x16, 0x16, 0x00, 0x00
        .word func_ov002_0224c898
        .byte 0x19, 0x16, 0x00, 0x00
        .word func_ov002_0224c920
        .byte 0x26, 0x16, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x28, 0x16, 0x00, 0x00
        .word func_ov002_0224cb6c
        .byte 0x29, 0x16, 0x00, 0x00
        .word func_ov002_0224c9dc
        .byte 0x2c, 0x16, 0x00, 0x00
        .word func_ov002_0224cb14
        .byte 0x30, 0x16, 0x00, 0x00
        .word func_ov002_02248c00
        .byte 0x31, 0x16, 0x00, 0x00
        .word func_ov002_02248d64
        .byte 0x38, 0x16, 0x00, 0x00
        .word func_ov002_02248c00
        .byte 0x42, 0x16, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x47, 0x16, 0x00, 0x00
        .word func_ov002_0224d7cc
        .byte 0x4a, 0x16, 0x00, 0x00
        .word func_ov002_0224d850
        .byte 0x56, 0x16, 0x00, 0x00
        .word func_ov002_0224cb6c
        .byte 0x5a, 0x16, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x5b, 0x16, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0x64, 0x16, 0x00, 0x00
        .word func_ov002_0224cba8
        .byte 0x6b, 0x16, 0x00, 0x00
        .word func_ov002_0224cc30
        .byte 0x78, 0x16, 0x00, 0x00
        .word func_ov002_0224ccb4
        .byte 0x7d, 0x16, 0x00, 0x00
        .word func_ov002_0224c5b4
        .byte 0x7e, 0x16, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x86, 0x16, 0x00, 0x00
        .word func_ov002_0224cd30
        .byte 0x89, 0x16, 0x00, 0x00
        .word func_ov002_0224ce2c
        .byte 0x9f, 0x16, 0x00, 0x00
        .word func_ov002_0224ceb0
        .byte 0xa4, 0x16, 0x00, 0x00
        .word func_ov002_0224cf5c
        .byte 0xa8, 0x16, 0x00, 0x00
        .word func_ov002_0224d010
        .byte 0xb9, 0x16, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xbc, 0x16, 0x00, 0x00
        .word func_ov002_0224d850
        .byte 0xc0, 0x16, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xc1, 0x16, 0x00, 0x00
        .word func_ov002_0224d0b4
        .byte 0xc2, 0x16, 0x00, 0x00
        .word func_ov002_0224d108
        .byte 0xc4, 0x16, 0x00, 0x00
        .word func_ov002_0224d204
        .byte 0xc5, 0x16, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xc6, 0x16, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xc7, 0x16, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xc8, 0x16, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xc9, 0x16, 0x00, 0x00
        .word func_ov002_0224d28c
        .byte 0xcb, 0x16, 0x00, 0x00
        .word func_ov002_0224d28c
        .byte 0xd5, 0x16, 0x00, 0x00
        .word func_ov002_0224d33c
        .byte 0xd6, 0x16, 0x00, 0x00
        .word func_ov002_0224d3c4
        .byte 0xd8, 0x16, 0x00, 0x00
        .word func_ov002_0224d428
        .byte 0xe4, 0x16, 0x00, 0x00
        .word func_ov002_0224d28c
        .byte 0xf6, 0x16, 0x00, 0x00
        .word func_ov002_02248e78
        .byte 0xf8, 0x16, 0x00, 0x00
        .word func_ov002_02248c00
        .byte 0xfd, 0x16, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0x0c, 0x17, 0x00, 0x00
        .word func_ov002_0224d4e0
        .byte 0x12, 0x17, 0x00, 0x00
        .word func_ov002_0224d428
        .byte 0x13, 0x17, 0x00, 0x00
        .word func_ov002_0224c5b4
        .byte 0x14, 0x17, 0x00, 0x00
        .word func_ov002_0224d578
        .byte 0x15, 0x17, 0x00, 0x00
        .word func_ov002_0224d630
        .byte 0x17, 0x17, 0x00, 0x00
        .word func_ov002_0224d6ac
        .byte 0x27, 0x17, 0x00, 0x00
        .word func_ov002_0224d730
        .byte 0x41, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x45, 0x17, 0x00, 0x00
        .word func_ov002_0224d850
        .byte 0x46, 0x17, 0x00, 0x00
        .word func_ov002_0224b5a4
        .byte 0x48, 0x17, 0x00, 0x00
        .word func_ov002_0224d994
        .byte 0x54, 0x17, 0x00, 0x00
        .word func_ov002_0224d730
        .byte 0x58, 0x17, 0x00, 0x00
        .word func_ov002_0224daac
        .byte 0x5c, 0x17, 0x00, 0x00
        .word func_ov002_0224da14
        .byte 0x64, 0x17, 0x00, 0x00
        .word func_ov002_0224daac
        .byte 0x68, 0x17, 0x00, 0x00
        .word func_ov002_0224db3c
        .byte 0x69, 0x17, 0x00, 0x00
        .word func_ov002_0224dd08
        .byte 0x88, 0x17, 0x00, 0x00
        .word func_ov002_0224ddac
        .byte 0x8a, 0x17, 0x00, 0x00
        .word func_ov002_022482c4
        .byte 0x8c, 0x17, 0x00, 0x00
        .word func_ov002_0224de90
        .byte 0x95, 0x17, 0x00, 0x00
        .word func_ov002_0224df30
        .byte 0x96, 0x17, 0x00, 0x00
        .word func_ov002_0224dff4
        .byte 0x9a, 0x17, 0x00, 0x00
        .word func_ov002_0224e09c
        .byte 0xa2, 0x17, 0x00, 0x00
        .word func_ov002_0224e148
        .byte 0xaf, 0x17, 0x00, 0x00
        .word func_ov002_0224e28c
        .byte 0xb2, 0x17, 0x00, 0x00
        .word func_ov002_0224e1d0
        .byte 0xb7, 0x17, 0x00, 0x00
        .word func_ov002_0224b2c8
        .byte 0xbe, 0x17, 0x00, 0x00
        .word func_ov002_0224d428
        .byte 0xc3, 0x17, 0x00, 0x00
        .word func_ov002_0224bcec
        .byte 0xc5, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xc9, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd1, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd2, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd3, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd5, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd7, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd8, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd9, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xda, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xdd, 0x17, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0xe5, 0x17, 0x00, 0x00
        .word func_ov002_0224e2a8
        .byte 0xe6, 0x17, 0x00, 0x00
        .word func_ov002_0224e2a8
        .byte 0xf1, 0x17, 0x00, 0x00
        .word func_ov002_0224e3a8
        .byte 0xf4, 0x17, 0x00, 0x00
        .word func_ov002_0224e430
        .byte 0xf5, 0x17, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xf7, 0x17, 0x00, 0x00
        .word func_ov002_0224e578
        .byte 0xf8, 0x17, 0x00, 0x00
        .word func_ov002_0224e600
        .byte 0xf9, 0x17, 0x00, 0x00
        .word func_ov002_0224e6a4
        .byte 0x07, 0x18, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x0b, 0x18, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x0c, 0x18, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x11, 0x18, 0x00, 0x00
        .word func_ov002_0224bfd0
        .byte 0x12, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x14, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x17, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x18, 0x18, 0x00, 0x00
        .word func_ov002_0224e758
        .byte 0x20, 0x18, 0x00, 0x00
        .word func_ov002_02249aa0
        .byte 0x21, 0x18, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0x22, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x3c, 0x18, 0x00, 0x00
        .word func_ov002_02249228
        .byte 0x3d, 0x18, 0x00, 0x00
        .word func_ov002_0224e814
        .byte 0x45, 0x18, 0x00, 0x00
        .word func_ov002_0224e8e4
        .byte 0x47, 0x18, 0x00, 0x00
        .word func_ov002_0224e96c
        .byte 0x4c, 0x18, 0x00, 0x00
        .word func_ov002_0224cb14
        .byte 0x5d, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x5e, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x64, 0x18, 0x00, 0x00
        .word func_ov002_0224e9cc
        .byte 0x67, 0x18, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0x70, 0x18, 0x00, 0x00
        .word func_ov002_0224ea54
        .byte 0x71, 0x18, 0x00, 0x00
        .word func_ov002_0224ea54
        .byte 0x72, 0x18, 0x00, 0x00
        .word func_ov002_0224ea54
        .byte 0x76, 0x18, 0x00, 0x00
        .word func_ov002_0224eca4
        .byte 0x79, 0x18, 0x00, 0x00
        .word func_ov002_02249074
        .byte 0x7a, 0x18, 0x00, 0x00
        .word func_ov002_0224ed60
        .byte 0x7e, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x7f, 0x18, 0x00, 0x00
        .word func_ov002_0224edc4
        .byte 0x80, 0x18, 0x00, 0x00
        .word func_ov002_0224ee9c
        .byte 0x81, 0x18, 0x00, 0x00
        .word func_ov002_0224ef3c
        .byte 0x89, 0x18, 0x00, 0x00
        .word func_ov002_0224efdc
        .byte 0x95, 0x18, 0x00, 0x00
        .word func_ov002_0224f090
        .byte 0x9a, 0x18, 0x00, 0x00
        .word func_ov002_0224a2e8
        .byte 0x9e, 0x18, 0x00, 0x00
        .word func_ov002_0224f288
        .byte 0x9f, 0x18, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0xa3, 0x18, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xb4, 0x18, 0x00, 0x00
        .word func_ov002_0224a498
        .byte 0xc5, 0x18, 0x00, 0x00
        .word func_ov002_0224f2fc
        .byte 0xcb, 0x18, 0x00, 0x00
        .word func_ov002_0224f3b8
        .byte 0xcc, 0x18, 0x00, 0x00
        .word func_ov002_0224f460
        .byte 0xd4, 0x18, 0x00, 0x00
        .word func_ov002_0224f514
        .byte 0xd9, 0x18, 0x00, 0x00
        .word func_ov002_0224f664
        .byte 0xda, 0x18, 0x00, 0x00
        .word func_ov002_0224f6b8
        .byte 0xe0, 0x18, 0x00, 0x00
        .word func_ov002_0224a92c
        .byte 0xf4, 0x18, 0x00, 0x00
        .word func_ov002_0224e2a8
        .byte 0xf7, 0x18, 0x00, 0x00
        .word func_ov002_0224f73c
        .byte 0xf8, 0x18, 0x00, 0x00
        .word func_ov002_0224f7c4
        .byte 0xfe, 0x18, 0x00, 0x00
        .word func_ov002_0224f828
        .byte 0x00, 0x19, 0x00, 0x00
        .word func_ov002_0224f8d8
        .byte 0x07, 0x19, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x08, 0x19, 0x00, 0x00
        .word func_ov002_0224f984
        .byte 0x0a, 0x19, 0x00, 0x00
        .word func_ov002_02249aa0
        .byte 0x18, 0x19, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x19, 0x19, 0x00, 0x00
        .word func_ov002_02248ad8
        .byte 0x1e, 0x19, 0x00, 0x00
        .word func_ov002_0224d428
        .byte 0x1f, 0x19, 0x00, 0x00
        .word func_ov002_0224f9f0
        .byte 0x20, 0x19, 0x00, 0x00
        .word func_ov002_0224fa70
        .byte 0x21, 0x19, 0x00, 0x00
        .word func_ov002_0224fbec
        .byte 0x27, 0x19, 0x00, 0x00
        .word func_ov002_0224fcac
        .byte 0x2b, 0x19, 0x00, 0x00
        .word func_ov002_0224fd9c
        .byte 0x35, 0x19, 0x00, 0x00
        .word func_ov002_0224fe40
        .byte 0x38, 0x19, 0x00, 0x00
        .word func_ov002_0224ff5c
        .byte 0x39, 0x19, 0x00, 0x00
        .word func_ov002_0225014c
        .byte 0x3a, 0x19, 0x00, 0x00
        .word func_ov002_02250268
        .byte 0x44, 0x19, 0x00, 0x00
        .word func_ov002_022502f0
        .byte 0x4f, 0x19, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0x51, 0x19, 0x00, 0x00
        .word func_ov002_022503b0
        .byte 0x5c, 0x19, 0x00, 0x00
        .word func_ov002_0224c5b4
        .byte 0x6a, 0x19, 0x00, 0x00
        .word func_ov002_02250458
        .byte 0x6f, 0x19, 0x00, 0x00
        .word func_ov002_02250500
        .byte 0x71, 0x19, 0x00, 0x00
        .word func_ov002_02249e80
        .byte 0x72, 0x19, 0x00, 0x00
        .word func_ov002_02250588
        .byte 0x73, 0x19, 0x00, 0x00
        .word func_ov002_02250624
        .byte 0x74, 0x19, 0x00, 0x00
        .word func_ov002_022506d8
        .byte 0x78, 0x19, 0x00, 0x00
        .word func_ov002_0224bd68
        .byte 0x79, 0x19, 0x00, 0x00
        .word func_ov002_02250774
        .byte 0x7c, 0x19, 0x00, 0x00
        .word func_ov002_02250940
        .byte 0x8d, 0x19, 0x00, 0x00
        .word func_ov002_02250a4c
        .byte 0x8e, 0x19, 0x00, 0x00
        .word func_ov002_02250a5c
        .byte 0x90, 0x19, 0x00, 0x00
        .word func_ov002_02249aa0
        .byte 0x96, 0x19, 0x00, 0x00
        .word func_ov002_02250c2c
        .byte 0xa7, 0x19, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0xac, 0x19, 0x00, 0x00
        .word func_ov002_02250cb4
        .byte 0xad, 0x19, 0x00, 0x00
        .word func_ov002_02250d58
        .byte 0xae, 0x19, 0x00, 0x00
        .word func_ov002_0225101c
        .byte 0xb1, 0x19, 0x00, 0x00
        .word func_ov002_0224c5b4
        .byte 0xb5, 0x19, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xb6, 0x19, 0x00, 0x00
        .word func_ov002_022510d4
        .byte 0xc0, 0x19, 0x00, 0x00
        .word func_ov002_0224b468
        .byte 0xc5, 0x19, 0x00, 0x00
        .word func_ov002_022511bc
        .byte 0xca, 0x19, 0x00, 0x00
        .word func_ov002_0224a498
        .byte 0xd7, 0x19, 0x00, 0x00
        .word func_ov002_02251298
        .byte 0xd8, 0x19, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xdc, 0x19, 0x00, 0x00
        .word func_ov002_0225139c
        .byte 0xdd, 0x19, 0x00, 0x00
        .word func_ov002_0225139c
        .byte 0xec, 0x19, 0x00, 0x00
        .word func_ov002_022514c8
        .byte 0xf4, 0x19, 0x00, 0x00
        .word func_ov002_0224c494
        .byte 0x03, 0x1a, 0x00, 0x00
        .word func_ov002_02251554
        .byte 0x05, 0x1a, 0x00, 0x00
        .word func_ov002_02251624
        .byte 0x0c, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x10, 0x1a, 0x00, 0x00
        .word func_ov002_022516d8
        .byte 0x12, 0x1a, 0x00, 0x00
        .word func_ov002_0225175c
        .byte 0x13, 0x1a, 0x00, 0x00
        .word func_ov002_02251820
        .byte 0x16, 0x1a, 0x00, 0x00
        .word func_ov002_02251a2c
        .byte 0x17, 0x1a, 0x00, 0x00
        .word func_ov002_022518dc
        .byte 0x1a, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x24, 0x1a, 0x00, 0x00
        .word func_ov002_02251ac8
        .byte 0x25, 0x1a, 0x00, 0x00
        .word func_ov002_02251ac8
        .byte 0x26, 0x1a, 0x00, 0x00
        .word func_ov002_02251b54
        .byte 0x2b, 0x1a, 0x00, 0x00
        .word func_ov002_02251c18
        .byte 0x2c, 0x1a, 0x00, 0x00
        .word func_ov002_02251c18
        .byte 0x2d, 0x1a, 0x00, 0x00
        .word func_ov002_02251c18
        .byte 0x2e, 0x1a, 0x00, 0x00
        .word func_ov002_02251c18
        .byte 0x31, 0x1a, 0x00, 0x00
        .word func_ov002_02251c90
        .byte 0x36, 0x1a, 0x00, 0x00
        .word func_ov002_02251d0c
        .byte 0x42, 0x1a, 0x00, 0x00
        .word func_ov002_0224e814
        .byte 0x5c, 0x1a, 0x00, 0x00
        .word func_ov002_02251dd8
        .byte 0x5d, 0x1a, 0x00, 0x00
        .word func_ov002_02251e88
        .byte 0x61, 0x1a, 0x00, 0x00
        .word func_ov002_02251f2c
        .byte 0x64, 0x1a, 0x00, 0x00
        .word func_ov002_02252008
        .byte 0x6a, 0x1a, 0x00, 0x00
        .word func_ov002_022520c4
        .byte 0x6b, 0x1a, 0x00, 0x00
        .word func_ov002_02252158
        .byte 0x6c, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x76, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0x7b, 0x1a, 0x00, 0x00
        .word func_ov002_022522e4
        .byte 0x7c, 0x1a, 0x00, 0x00
        .word func_ov002_02252350
        .byte 0x7d, 0x1a, 0x00, 0x00
        .word func_ov002_022523bc
        .byte 0x7e, 0x1a, 0x00, 0x00
        .word func_ov002_02252470
        .byte 0x7f, 0x1a, 0x00, 0x00
        .word func_ov002_0225257c
        .byte 0x80, 0x1a, 0x00, 0x00
        .word func_ov002_0225264c
        .byte 0x8d, 0x1a, 0x00, 0x00
        .word func_ov002_022526d0
        .byte 0x8f, 0x1a, 0x00, 0x00
        .word func_ov002_02252780
        .byte 0x97, 0x1a, 0x00, 0x00
        .word func_ov002_0225282c
        .byte 0x98, 0x1a, 0x00, 0x00
        .word func_ov002_022528b0
        .byte 0x9b, 0x1a, 0x00, 0x00
        .word func_ov002_02252970
        .byte 0xa1, 0x1a, 0x00, 0x00
        .word func_ov002_0224d630
        .byte 0xa2, 0x1a, 0x00, 0x00
        .word func_ov002_02252a10
        .byte 0xa9, 0x1a, 0x00, 0x00
        .word func_ov002_02252a98
        .byte 0xae, 0x1a, 0x00, 0x00
        .word func_ov002_02252b20
        .byte 0xaf, 0x1a, 0x00, 0x00
        .word func_ov002_02252b20
        .byte 0xb0, 0x1a, 0x00, 0x00
        .word func_ov002_02252b20
        .byte 0xb1, 0x1a, 0x00, 0x00
        .word func_ov002_02252bbc
        .byte 0xd6, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xd7, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xdc, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xdd, 0x1a, 0x00, 0x00
        .word func_ov002_022483a4
        .byte 0xf4, 0x1a, 0x00, 0x00
        .word func_ov002_02252c44
        .byte 0xf5, 0x1a, 0x00, 0x00
        .word func_ov002_02252cb0
        .byte 0xf9, 0x1a, 0x00, 0x00
        .word func_ov002_02249180
        .byte 0xfb, 0x1a, 0x00, 0x00
        .word func_ov002_02252d6c
        .byte 0x17, 0x1b, 0x00, 0x00
        .word func_ov002_02252e7c
        .byte 0x1d, 0x1b, 0x00, 0x00
        .word func_ov002_02252f18
        .byte 0x1f, 0x1b, 0x00, 0x00
        .word func_ov002_022516d8
        .byte 0x22, 0x1b, 0x00, 0x00
        .word func_ov002_02252fc0
        .byte 0x25, 0x1b, 0x00, 0x00
        .word func_ov002_022498c8
        .byte 0x26, 0x1b, 0x00, 0x00
        .word func_ov002_0225306c
        .byte 0x27, 0x1b, 0x00, 0x00
        .word func_ov002_022530d4
        .byte 0x44, 0x1b, 0x00, 0x00
        .word func_ov002_0224b468
        .byte 0x53, 0x1b, 0x00, 0x00
        .word func_ov002_0225321c
        .byte 0x62, 0x1b, 0x00, 0x00
        .word func_ov002_0224ed60
        .byte 0x65, 0x1b, 0x00, 0x00
        .word func_ov002_0224b2c8
        .byte 0xfe, 0xff, 0x00, 0x00
        .word func_ov002_02259a64
        .byte 0xff, 0xff, 0x00, 0x00
        .word func_ov002_022532a8

        .global data_ov002_022cb86c
data_ov002_022cb86c:
        .word func_ov002_0225ab80
        .word func_ov002_0225acbc
        .word func_ov002_0225b250
        .word func_ov002_0225bc64
        .word func_ov002_0225c010
        .word func_ov002_0225c0f0
        .word func_ov002_0225c978
        .word func_ov002_0225d540
        .word func_ov002_0225e244
        .word func_ov002_0225e788
        .word func_ov002_0225ed60
        .word func_ov002_02260bf8
        .word func_ov002_02261b5c
        .word func_ov002_02262650
        .byte 0x00, 0x00, 0x00, 0x00
