/* Brief 170 cross-region cluster B pointer slot.
 *
 * Generated by tools/cross_region_cluster_apply.py from
 * the region's own symbols.txt + relocs.txt. The slot's
 * `kind:load` reloc resolves to data_02101504
 * (VA 0x02101504). Recipe per brief 148:
 * opaque `extern char` declaration of the pointee +
 * `void *` slot initialised with `&pointee`. mwldarm
 * emits the reloc that resolves the pointee at link
 * time.
 */

extern char data_02101504;

void *data_02101500 = &data_02101504;
