/* Brief 170 cross-region cluster B pointer slot.
 *
 * Generated by tools/cross_region_cluster_apply.py from
 * the region's own symbols.txt + relocs.txt. The slot's
 * `kind:load` reloc resolves to func_0207de10
 * (VA 0x0207de10). Recipe per brief 148:
 * opaque `extern char` declaration of the pointee +
 * `void *` slot initialised with `&pointee`. mwldarm
 * emits the reloc that resolves the pointee at link
 * time.
 */

extern char func_0207de10;

void *data_02102018 = &func_0207de10;
