; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: main
; Range:  0x020f8b80..0x020f8f10 (912 bytes, 2 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .extern data_020f9000
        .extern data_020f9028
        .extern data_020f9050
        .extern data_020f909c
        .extern data_020f90c4
        .extern data_020f90f4
        .extern data_020f9124
        .extern data_020f9154
        .extern data_020f9184
        .extern data_020f91b4
        .extern data_020f91e4
        .extern data_020f9214
        .extern data_020f9244
        .extern data_020f9274
        .extern data_020f92a4
        .extern data_020f92d4
        .extern data_020f9304
        .extern data_020f9334
        .extern data_020f9364
        .extern data_020f9394
        .extern data_020f93c4
        .extern data_020f93f4
        .extern data_020f9424
        .extern data_020f9454
        .extern data_020f9484
        .extern data_020f94b4
        .extern data_020f94e4
        .extern data_020f9514
        .extern data_020f9544
        .extern data_020f9574
        .extern data_020f95a4
        .extern data_020f95d4
        .extern data_020f9604
        .extern data_020f9634
        .extern data_020f9664
        .extern data_020f9694
        .extern data_020f96c4
        .extern data_020f96f4
        .extern data_020f9724
        .extern data_020f9754
        .extern data_020f9784
        .extern data_020f97b4
        .extern data_020f97e4
        .extern data_020f99d4
        .extern data_020f9a68
        .extern data_020f9c74
        .extern data_020f9c88
        .extern data_020f9c9c
        .extern data_020f9cb0
        .extern data_020f9cc4
        .extern data_020f9cd8
        .extern data_020f9cec
        .extern data_020f9d00
        .extern data_020f9d14
        .extern data_020f9dac
        .extern data_020f9dc8
        .extern data_020f9de4
        .extern data_020f9e00
        .extern data_020f9e1c
        .extern data_020f9e38
        .extern data_020f9e54
        .extern data_020f9e70
        .extern data_020f9ad0
        .extern data_020f8f10
        .extern data_020f8f40

        .global data_020f8b80
data_020f8b80:
        .byte 0x00, 0x00, 0x00, 0xf1
        .word data_020f8ee8
        .byte 0x04, 0x00, 0x00, 0x00
        .word data_020f9000
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9028
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9050
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f909c
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f90c4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f90f4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9124
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9154
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9184
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f91b4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f91e4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9214
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9244
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9274
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f92a4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f92d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9304
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9334
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9364
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9394
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f93c4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f93f4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9424
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9454
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9484
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f94b4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f94e4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9514
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9544
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9574
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f95a4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f95d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9604
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9634
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9664
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9694
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f96c4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f96f4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9724
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9754
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9784
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f97b4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f97e4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f99d4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9a68
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9a68
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9c74
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9c88
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9c9c
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9cb0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9cc4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9cd8
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9cec
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9d00
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9d14
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9dac
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9dc8
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9de4
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e00
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e1c
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e38
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e54
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9e70
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ad0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ad0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ad0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ad0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ad0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ad0
        .byte 0x05, 0x00, 0x00, 0x00
        .word data_020f9ad0
        .byte 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0

        .global data_020f8ee8
data_020f8ee8:
        .byte 0x20, 0x10, 0x00, 0xfa, 0x01, 0x00, 0x00, 0x00
        .byte 0x04, 0x00, 0x00, 0x74, 0x20, 0x10, 0x00, 0xfb
        .byte 0x00, 0x08, 0x00, 0x00
        .word data_020f8f10
        .byte 0x00, 0x00, 0x00, 0x10
        .word data_020f8f40
        .byte 0x00, 0x00, 0x00, 0xf8
        .word data_020f8f10
