#!/usr/bin/env python3

"""
ci_format_mega_cascades.py — render the per-PR mega-cascade ranking
diff as an upsertable Markdown comment.

Companion to `ci_format_rename_cascades.py` (#172):

  - `ci_format_rename_cascades` reports **per-rename** primary-cascade
    impact (one-step `hard → medium` promotions).
  - `ci_format_mega_cascades` (this) reports how the PR's renames
    shift the **transitive** mega-cascade ranking — which previously-
    high-leverage anchors are now consumed (named or rendered
    irrelevant), and which new anchors rise into the top-N.

Why both: the per-rename view answers "what does this PR unlock NOW?"
The ranking-diff view answers "what's the most leverage-rich thing
the next PR should target?" Together they cover the immediate +
follow-on planning surface that find_mega_cascades.py (#207) was
designed to support.

Pattern mirrors `ci_format_rename_cascades` / `ci_format_worklist_diff`:
single upsertable PR comment with a trailing footer marker so the
workflow can find + patch it on follow-up pushes.

Usage (called from `.github/workflows/mega-cascades-diff.yml`):

    python tools/ci_format_mega_cascades.py \\
        --before-config /tmp/base-tree/config/eur \\
        --after-config config/eur \\
        -o /tmp/comment.md

Pure function-of-two-directories — the workflow does the git-worktree
dance to materialise the base-branch config.
"""

from __future__ import annotations

import argparse
import io
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from analyze_symbols import (  # noqa: E402
    build_call_graph,
    load_all,
)
from find_mega_cascades import (  # noqa: E402
    MegaCascade,
    rank_mega_cascades,
)
from next_targets import (  # noqa: E402
    collect_matched_ranges,
)


FOOTER_MARKER = (
    "<sub>🤖 Generated by `tools/ci_format_mega_cascades.py`. "
    "See `tools/find_mega_cascades.py` for the model.</sub>"
)


@dataclass(frozen=True)
class RankingEntry:
    """One placeholder anchor in the mega-cascade ranking, plus its
    rank (1-based)."""
    rank: int
    module: str
    addr: int
    name: str           # name as it appears in this snapshot
    weight: int         # total promotions
    direct: int
    indirect: int
    depth: int

    @property
    def key(self) -> tuple[str, int]:
        return (self.module, self.addr)


@dataclass(frozen=True)
class RankingDiff:
    """Cross-PR diff of the mega-cascade ranking.

    `consumed` — anchors in the BEFORE top-N that are no longer in
      the AFTER top-N (typically because they got named, were
      matched, or their cascade promoted away).
    `entered`  — anchors in the AFTER top-N that weren't in the
      BEFORE top-N.
    `moved`    — anchors in both, with rank/weight changes worth
      reporting.
    `unchanged` — anchors in both with no rank or weight change.
    """
    consumed: tuple[RankingEntry, ...]
    entered: tuple[RankingEntry, ...]
    moved: tuple[tuple[RankingEntry, RankingEntry], ...]   # (before, after)
    unchanged: tuple[tuple[RankingEntry, RankingEntry], ...]


# --------------------------------------------------------------------------- #
# Ranking computation
# --------------------------------------------------------------------------- #

def _rank(
    cascades: list[MegaCascade], top_n: int,
) -> list[RankingEntry]:
    out: list[RankingEntry] = []
    for i, mc in enumerate(cascades[:top_n], start=1):
        out.append(RankingEntry(
            rank=i,
            module=mc.anchor.module,
            addr=mc.anchor.addr,
            name=mc.anchor.name,
            weight=mc.weight,
            direct=len(mc.direct),
            indirect=len(mc.indirect),
            depth=mc.depth,
        ))
    return out


def diff_rankings(
    before: list[RankingEntry],
    after: list[RankingEntry],
) -> RankingDiff:
    """Bucket entries into consumed / entered / moved / unchanged.

    `moved` only includes entries whose rank OR weight changed —
    pure-cosmetic re-renders (same rank, same weight) go to
    `unchanged`."""
    by_key_before = {e.key: e for e in before}
    by_key_after = {e.key: e for e in after}

    consumed = tuple(
        e for e in before if e.key not in by_key_after
    )
    entered = tuple(
        e for e in after if e.key not in by_key_before
    )

    moved: list[tuple[RankingEntry, RankingEntry]] = []
    unchanged: list[tuple[RankingEntry, RankingEntry]] = []
    for after_entry in after:
        before_entry = by_key_before.get(after_entry.key)
        if before_entry is None:
            continue
        if (
            before_entry.rank != after_entry.rank
            or before_entry.weight != after_entry.weight
        ):
            moved.append((before_entry, after_entry))
        else:
            unchanged.append((before_entry, after_entry))

    return RankingDiff(
        consumed=consumed,
        entered=entered,
        moved=tuple(moved),
        unchanged=tuple(unchanged),
    )


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #

def _fmt_anchor(e: RankingEntry) -> str:
    return f"`{e.name}` (`{e.module}|0x{e.addr:08x}`)"


def render_markdown(
    diff: RankingDiff,
    *,
    version: str,
    top_n: int,
) -> str:
    """Render the PR comment. Empty-diff case still emits a marker
    so brain can tell the workflow ran."""
    lines: list[str] = []
    lines.append("## 🌊 Mega-cascade ranking diff")
    lines.append("")

    n_consumed = len(diff.consumed)
    n_entered = len(diff.entered)
    n_moved = len(diff.moved)

    if n_consumed == 0 and n_entered == 0 and n_moved == 0:
        lines.append(
            f"_No change to the top-{top_n} mega-cascade ranking "
            f"on `{version}`. This PR's renames don't shift the "
            "transitive-leverage frontier._",
        )
        lines.append("")
        lines.append(FOOTER_MARKER)
        return "\n".join(lines)

    lines.append(
        f"PR shifts the top-**{top_n}** mega-cascade leverage "
        f"frontier on `{version}`: **{n_consumed}** consumed, "
        f"**{n_entered}** entered, **{n_moved}** moved."
    )
    lines.append("")

    if diff.consumed:
        lines.append(
            f"### Consumed ({n_consumed}) — exited top-{top_n}",
        )
        lines.append("")
        lines.append(
            "_These anchors were high-leverage on base; they are "
            "no longer in the top-N (named, matched, or their "
            "cascade collapsed via this PR's renames)._",
        )
        lines.append("")
        lines.append(
            "| Was rank | Anchor | Before weight | Before depth |",
        )
        lines.append(
            "|---------:|--------|--------------:|-------------:|",
        )
        for e in diff.consumed:
            lines.append(
                f"| {e.rank} | {_fmt_anchor(e)} | "
                f"**{e.weight}** | {e.depth} |",
            )
        lines.append("")

    if diff.entered:
        lines.append(
            f"### Entered ({n_entered}) — new in top-{top_n}",
        )
        lines.append("")
        lines.append(
            "_Newly-surfaced cascade leverage. These are the next-"
            "wave brief candidates._",
        )
        lines.append("")
        lines.append(
            "| Now rank | Anchor | After weight | After depth | "
            "Direct | Indirect |",
        )
        lines.append(
            "|---------:|--------|-------------:|------------:|"
            "-------:|---------:|",
        )
        for e in diff.entered:
            lines.append(
                f"| {e.rank} | {_fmt_anchor(e)} | "
                f"**{e.weight}** | {e.depth} | "
                f"{e.direct} | {e.indirect} |",
            )
        lines.append("")

    if diff.moved:
        lines.append(
            f"### Moved ({n_moved}) — rank or weight changed",
        )
        lines.append("")
        lines.append(
            "| Anchor | Rank Δ | Weight Δ | Depth Δ |",
        )
        lines.append(
            "|--------|-------:|---------:|--------:|",
        )
        # Sort by absolute weight delta desc so the biggest shifts
        # surface first.
        sorted_moved = sorted(
            diff.moved,
            key=lambda pair: (
                -abs(pair[1].weight - pair[0].weight),
                pair[1].rank,
            ),
        )
        for before_e, after_e in sorted_moved:
            rank_delta = after_e.rank - before_e.rank
            weight_delta = after_e.weight - before_e.weight
            depth_delta = after_e.depth - before_e.depth
            rank_str = f"{before_e.rank} → {after_e.rank}"
            if rank_delta < 0:
                rank_str += " ⬆"  # better rank = lower number
            elif rank_delta > 0:
                rank_str += " ⬇"
            weight_str = (
                f"{before_e.weight} → {after_e.weight} "
                f"({weight_delta:+d})"
            )
            depth_str = (
                f"{before_e.depth} → {after_e.depth} "
                f"({depth_delta:+d})"
            )
            lines.append(
                f"| {_fmt_anchor(after_e)} | {rank_str} | "
                f"{weight_str} | {depth_str} |",
            )
        lines.append("")

    lines.append(
        "<sub>Mega-cascade model: BFS over the `hard → medium` "
        "promotion graph; `weight` = total promoted callers across "
        "all waves; `depth` = BFS rounds to fixpoint. See "
        "`tools/find_mega_cascades.py` for the per-anchor query.</sub>",
    )
    lines.append("")
    lines.append(FOOTER_MARKER)
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _empty_msg(version: str, top_n: int) -> str:
    """Render the no-base case (PR from a fork or base ref deleted)
    so the upsert still produces something visible."""
    lines = [
        "## 🌊 Mega-cascade ranking diff",
        "",
        f"_No base-branch snapshot available; can't compute the "
        f"top-{top_n} mega-cascade diff for `{version}`. "
        "(This usually means the PR is from a fork without history "
        "access, or the base ref was deleted.)_",
        "",
        FOOTER_MARKER,
    ]
    return "\n".join(lines)


def main() -> int:
    # Force UTF-8 on stdout so the emoji header (🌊) survives on
    # Windows cp1252 consoles when the tool is run locally. The
    # `-o <path>` writer already pins utf-8; this covers the plain
    # stdout invocation that crashes otherwise. No-op in
    # environments where stdout is already utf-8 (Linux/macOS,
    # GitHub Actions runners) or where reconfigure isn't available
    # (piped, non-TextIO stdout).
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, io.UnsupportedOperation):
        pass

    ap = argparse.ArgumentParser(
        description="Render mega-cascade ranking diff as Markdown.",
    )
    ap.add_argument(
        "--before-config", type=Path, required=True,
        help="Path to config/<ver>/ on the base branch (typically "
             "a git worktree of origin/main).",
    )
    ap.add_argument(
        "--after-config", type=Path, required=True,
        help="Path to config/<ver>/ on the PR head (usually the "
             "checked-out workspace).",
    )
    ap.add_argument(
        "-o", "--out", type=Path, default=None,
        help="Write Markdown to this path (default: stdout).",
    )
    ap.add_argument(
        "--top-n", type=int, default=20,
        help="Top-N depth for the ranking diff (default 20).",
    )
    ap.add_argument(
        "--version", default="eur",
        help="Version tag for the comment header (default eur).",
    )
    args = ap.parse_args()

    if not args.before_config.is_dir():
        print(
            f"warning: --before-config {args.before_config} "
            "is not a directory; emitting no-base placeholder.",
            file=sys.stderr,
        )
        md = _empty_msg(args.version, args.top_n)
        if args.out:
            args.out.write_text(md, encoding="utf-8")
        else:
            sys.stdout.write(md)
        return 0

    before_modules = load_all(args.before_config)
    after_modules = load_all(args.after_config)
    before_graph = build_call_graph(before_modules)
    after_graph = build_call_graph(after_modules)
    before_matched = collect_matched_ranges(args.before_config)
    after_matched = collect_matched_ranges(args.after_config)

    before_cascades = rank_mega_cascades(
        before_modules, before_graph, before_matched,
    )
    after_cascades = rank_mega_cascades(
        after_modules, after_graph, after_matched,
    )
    before_top = _rank(before_cascades, args.top_n)
    after_top = _rank(after_cascades, args.top_n)

    diff = diff_rankings(before_top, after_top)
    md = render_markdown(diff, version=args.version, top_n=args.top_n)

    if args.out:
        args.out.write_text(md, encoding="utf-8")
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
