#!/usr/bin/env python3

"""
ci_format_rename_cascades.py — render the per-PR rename-cascade
comment for CI.

For every symbol renamed in the PR (`func_*` → `RealName`), runs
`find_cascades.cascades_for_target` against the **base-branch**
call graph and reports which `hard → medium` tier promotions would
fire from that rename.

Rationale: the decomper reviews PRs based on what the changes do
to the build and the match state. `analyzer.yml` / `worklist-diff`
already surface the build / tier side. This comment covers the
**identity side** — "what cascades does the PR's rename set
unlock?" — which is the specific leverage the decomper cares
about when picking brief follow-ups.

Pattern mirrors `ci_format_worklist_diff.py`: single upsertable PR
comment with a trailing marker so the workflow can find + patch
it on follow-up pushes.

Usage (called from `.github/workflows/cascades-diff.yml`):

    python tools/ci_format_rename_cascades.py \\
        --before-config /tmp/base-tree/config/eur \\
        --after-config config/eur \\
        -o /tmp/comment.md

The workflow does the git-worktree dance to materialise the base-
branch config; this tool is pure function-of-two-directories.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from analyze_symbols import (  # noqa: E402
    build_call_graph,
    load_all,
)
from find_cascades import (  # noqa: E402
    cascades_for_target,
)
from next_targets import (  # noqa: E402
    collect_matched_ranges,
)


# Trailing footer marker — identical-shape to the other CI format
# tools so the upsert step can `grep` for it without collisions.
FOOTER_MARKER = (
    "<sub>🤖 Generated by `tools/ci_format_rename_cascades.py`. "
    "See `docs/decomp-workflow.md` for the cascade model.</sub>"
)


@dataclass(frozen=True)
class Rename:
    module: str
    addr: int
    old_name: str
    new_name: str


@dataclass(frozen=True)
class RenameImpact:
    rename: Rename
    promoted: frozenset[tuple[str, int]]  # caller keys (module, addr)

    @property
    def weight(self) -> int:
        return len(self.promoted)


# --------------------------------------------------------------------------- #
# Rename detection
# --------------------------------------------------------------------------- #

PLACEHOLDER_PREFIXES = ("func_", "data_", "_dsd_gap")


def _is_placeholder(name: str) -> bool:
    return name.startswith(PLACEHOLDER_PREFIXES)


def detect_renames(
    before_modules, after_modules,
) -> list[Rename]:
    """Return every (module, addr) whose name went from placeholder
    → real in `after_modules` relative to `before_modules`.

    Skips:
      - entries new in after (no before row) — those aren't renames
      - entries removed in after (would-be-dropped) — noise, decomper
        would spot the removal directly
      - entries that were already named on base — no signal change
      - placeholder → placeholder (e.g. address-suffix drift) — not
        a real rename
    """
    out: list[Rename] = []
    for mod_name, after_md in after_modules.items():
        before_md = before_modules.get(mod_name)
        if before_md is None:
            continue
        for sym in after_md.symbols:
            if not sym.is_function:
                continue
            before_sym = before_md.by_addr.get(sym.addr)
            if before_sym is None:
                continue
            if not _is_placeholder(before_sym.name):
                continue
            if _is_placeholder(sym.name):
                continue
            out.append(Rename(
                module=mod_name, addr=sym.addr,
                old_name=before_sym.name, new_name=sym.name,
            ))
    # Deterministic order: module, addr ascending.
    out.sort(key=lambda r: (r.module, r.addr))
    return out


def compute_impacts(
    renames: list[Rename],
    before_modules,
    before_graph,
    before_matched,
) -> list[RenameImpact]:
    """For each rename, compute its individual cascade against the
    base-branch graph. Using base ensures we surface the cascades
    that *were pending* — not the post-rename state (where the
    newly-named callee doesn't produce new cascade since it's
    already named)."""
    out: list[RenameImpact] = []
    for r in renames:
        before_md = before_modules.get(r.module)
        if before_md is None:
            continue
        before_sym = before_md.by_addr.get(r.addr)
        if before_sym is None:
            continue
        promoted = cascades_for_target(
            before_sym, before_modules, before_graph, before_matched,
        )
        # Convert to hashable pairs for downstream set ops.
        promoted_pairs = frozenset(
            (m, a) for (m, a) in promoted
        )
        out.append(RenameImpact(rename=r, promoted=promoted_pairs))
    return out


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #

def render_markdown(
    impacts: list[RenameImpact],
    *,
    top_rows: int = 10,
    top_callers_per_rename: int = 3,
) -> str:
    """Render the PR comment. Shape matches the sibling ci_format_*
    renderers so readers can skim any of them and know what they're
    looking at. Empty-impacts case still renders a short section so
    brain can tell the tool ran (not silently failed)."""
    lines: list[str] = []
    lines.append("## 🔗 Rename-cascade impact")
    lines.append("")

    n_renames = len(impacts)
    aggregate = frozenset()
    for imp in impacts:
        aggregate = aggregate | imp.promoted
    n_aggregate = len(aggregate)

    with_cascade = [imp for imp in impacts if imp.weight > 0]
    without_cascade = [imp for imp in impacts if imp.weight == 0]

    if n_renames == 0:
        lines.append(
            "_No placeholder → real renames detected in this PR's "
            "`symbols.txt` diff. Nothing to analyze._",
        )
        lines.append("")
        lines.append(FOOTER_MARKER)
        return "\n".join(lines)

    lines.append(
        f"This PR renames **{n_renames}** placeholder "
        f"function(s). {len(with_cascade)} of them had a pending "
        f"`hard → medium` cascade; together they promote "
        f"**{n_aggregate}** caller(s) to `medium` tier."
    )
    lines.append("")

    if with_cascade:
        # Sort by weight desc so the big cascades are at top.
        with_cascade.sort(
            key=lambda i: (-i.weight, i.rename.module, i.rename.addr),
        )
        lines.append(
            f"### Renames with cascades ({len(with_cascade)})",
        )
        lines.append("")
        lines.append(
            "| Module | Addr | `old` → `new` | Cascade | First promoted caller(s) |",
        )
        lines.append(
            "|--------|------|---------------|--------:|--------------------------|",
        )
        for imp in with_cascade[:top_rows]:
            r = imp.rename
            sample = sorted(imp.promoted)[:top_callers_per_rename]
            sample_str = ", ".join(
                f"`{m}|0x{a:08x}`" for (m, a) in sample
            )
            if imp.weight > top_callers_per_rename:
                extra = imp.weight - top_callers_per_rename
                sample_str += f", …(+{extra})"
            lines.append(
                f"| `{r.module}` | `0x{r.addr:08x}` | "
                f"`{r.old_name}` → `{r.new_name}` | "
                f"**{imp.weight}** | {sample_str} |",
            )
        if len(with_cascade) > top_rows:
            lines.append(
                f"\n_(+{len(with_cascade) - top_rows} more rename(s) "
                f"with cascades truncated for readability.)_"
            )
        lines.append("")

    if without_cascade:
        lines.append(
            f"### Renames without cascades ({len(without_cascade)})",
        )
        lines.append("")
        lines.append(
            "_These renames don't unlock any `hard → medium` "
            "promotion today — either they're leaf functions whose "
            "name doesn't block a size-≤0x80 caller, or every "
            "caller has another placeholder callee still blocking._",
        )
        lines.append("")

    lines.append(
        "<sub>Cascade model: `analyze_symbols.classify` places a "
        "function in `medium` tier when size ≤ 0x80 AND all direct "
        "callees are named. Renaming the **last** placeholder "
        "callee cascades its size-≤0x80 callers `hard → medium`. "
        "See `tools/find_cascades.py` for the per-symbol query.</sub>",
    )
    lines.append("")
    lines.append(FOOTER_MARKER)
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Render per-PR rename-cascade impact as Markdown.",
    )
    ap.add_argument(
        "--before-config", type=Path, required=True,
        help="Path to config/<ver>/ on the base branch "
             "(typically a git worktree of origin/main).",
    )
    ap.add_argument(
        "--after-config", type=Path, required=True,
        help="Path to config/<ver>/ on the PR head (usually the "
             "checked-out workspace).",
    )
    ap.add_argument(
        "-o", "--out", type=Path, default=None,
        help="Write Markdown to this path (default: stdout).",
    )
    ap.add_argument(
        "--top-rows", type=int, default=10,
        help="Top-N renames shown in the with-cascade table "
             "(default 10).",
    )
    args = ap.parse_args()

    if not args.before_config.is_dir():
        print(
            f"error: --before-config {args.before_config} "
            "is not a directory; writing empty snapshot.",
            file=sys.stderr,
        )
        md = render_markdown([])
        if args.out:
            args.out.write_text(md, encoding="utf-8")
        else:
            sys.stdout.write(md)
        return 0

    before_modules = load_all(args.before_config)
    after_modules = load_all(args.after_config)
    before_graph = build_call_graph(before_modules)
    before_matched = collect_matched_ranges(args.before_config)

    renames = detect_renames(before_modules, after_modules)
    impacts = compute_impacts(
        renames, before_modules, before_graph, before_matched,
    )
    md = render_markdown(impacts, top_rows=args.top_rows)

    if args.out:
        args.out.write_text(md, encoding="utf-8")
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
