#!/usr/bin/env python3

"""
ci_format_pattern_clusters.py — render the per-PR pattern-cluster
diff as an upsertable Markdown comment.

Pattern clusters (from `find_pattern_clusters.py` #227) group
functions sharing an exact `(size, reloc-signature)` fingerprint
where ≥1 is matched (template) and ≥1 is still unmatched
(propagation target). When a PR matches new functions, three
things can happen at the cluster level:

  - **Drained** — the PR matched M unmatched siblings of an
    existing cluster (cluster size shrinks; matched count grows).
  - **Newly-ready** — a cluster that had zero matched anchors on
    base now has ≥1 (the PR added the first template, opening
    the cluster up for `propagate_template` runs).
  - **Closed** — a cluster's unmatched count went to zero
    (entirely consumed; remove from the worklist).

This formatter computes the diff and posts a single upsertable PR
comment so the decomper sees cluster-level leverage shifts in PR
review without running the tool locally.

Companion to:

  - `ci_format_rename_cascades.py` (#172)   per-rename cascade impact
  - `ci_format_mega_cascades.py`   (#224)   top-N transitive ranking shift
  - `ci_format_pattern_clusters.py` (this)  cluster drainage / new-ready

Pattern mirrors the others: pure function-of-two-directories;
upsertable comment with a footer marker; identical workflow shape
in `.github/workflows/pattern-clusters-diff.yml`.

Usage (called from the workflow):

    python tools/ci_format_pattern_clusters.py \\
        --before-config /tmp/base-tree/config/eur \\
        --after-config config/eur \\
        -o /tmp/comment.md
"""

from __future__ import annotations

import argparse
import io
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from analyze_symbols import (  # noqa: E402
    load_all,
)
from find_pattern_clusters import (  # noqa: E402
    Cluster,
    find_clusters,
)
from next_targets import (  # noqa: E402
    collect_matched_ranges,
)


FOOTER_MARKER = (
    "<sub>🤖 Generated by `tools/ci_format_pattern_clusters.py`. "
    "See `tools/find_pattern_clusters.py` for the model.</sub>"
)


# --------------------------------------------------------------------------- #
# Diff computation
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class ClusterSnapshot:
    """A simplified Cluster suitable for diffing — keyed by
    fingerprint, holding only the matched/unmatched counts +
    a representative anchor name for display."""
    fingerprint: tuple[int, tuple]
    matched_count: int
    unmatched_count: int
    representative: str   # name of one matched anchor (for display)
    representative_module: str
    representative_addr: int

    @property
    def size(self) -> int:
        return self.fingerprint[0]

    @property
    def sig_len(self) -> int:
        return len(self.fingerprint[1])


@dataclass(frozen=True)
class ClusterDiff:
    """Cross-PR cluster diff.

    `drained`     — clusters present in both with ≥1 fewer unmatched.
                    Each entry is (before, after).
    `newly_ready` — clusters present in BOTH (same fingerprint exists)
                    where matched went from 0 → ≥1. Note: a cluster
                    with 0 matched is filtered out by find_clusters,
                    so this is computed from raw fingerprint buckets,
                    not from find_clusters output.
    `closed`      — clusters present on base with ≥1 unmatched whose
                    after-state has 0 unmatched (all matched).
    """
    drained: tuple[tuple[ClusterSnapshot, ClusterSnapshot], ...]
    newly_ready: tuple[ClusterSnapshot, ...]
    closed: tuple[ClusterSnapshot, ...]


def _snapshot(c: Cluster) -> ClusterSnapshot:
    rep = c.matched[0] if c.matched else c.unmatched[0]
    return ClusterSnapshot(
        fingerprint=c.fingerprint,
        matched_count=len(c.matched),
        unmatched_count=len(c.unmatched),
        representative=rep.name,
        representative_module=rep.module,
        representative_addr=rep.addr,
    )


def diff_clusters(
    before: list[Cluster], after: list[Cluster],
) -> ClusterDiff:
    """Bucket cluster-fingerprint transitions into drained /
    newly_ready / closed. Identical-counts clusters are dropped."""
    before_by_fp = {c.fingerprint: _snapshot(c) for c in before}
    after_by_fp = {c.fingerprint: _snapshot(c) for c in after}

    drained: list[tuple[ClusterSnapshot, ClusterSnapshot]] = []
    newly_ready: list[ClusterSnapshot] = []
    closed: list[ClusterSnapshot] = []

    for fp, before_snap in before_by_fp.items():
        after_snap = after_by_fp.get(fp)
        if after_snap is None:
            # Cluster is gone in `after`. Two cases:
            #   - All unmatched siblings got matched (and the lone
            #     matched anchor is now the only member, OR more
            #     matched anchors joined and unmatched went to 0).
            #     → "closed".
            #   - The cluster shape itself changed (very rare —
            #     would require a function's reloc set to change).
            #     → still effectively "closed" from the worklist's
            #     POV; the old fingerprint isn't actionable anymore.
            closed.append(before_snap)
            continue
        # Cluster present in both. Did unmatched count drop?
        if after_snap.unmatched_count < before_snap.unmatched_count:
            drained.append((before_snap, after_snap))

    # Newly-ready: clusters in `after` that weren't in `before` AND
    # have ≥1 matched. find_clusters already filters out zero-matched
    # clusters, so the simple "after \ before" set is exactly the
    # newly-ready bucket. We DON'T fold in clusters that existed on
    # base with 0 matched (those would require sniffing raw
    # fingerprint buckets pre-filter — defer until we have a
    # use case for them).
    for fp, after_snap in after_by_fp.items():
        if fp not in before_by_fp:
            newly_ready.append(after_snap)

    # Sort each bucket by impact: drained by absolute drainage desc,
    # newly_ready / closed by unmatched-count desc.
    drained.sort(
        key=lambda pair: (
            -(pair[0].unmatched_count - pair[1].unmatched_count),
            pair[1].representative_module,
            pair[1].representative_addr,
        ),
    )
    newly_ready.sort(
        key=lambda s: (-s.unmatched_count, s.representative_addr),
    )
    closed.sort(
        key=lambda s: (-s.unmatched_count, s.representative_addr),
    )
    return ClusterDiff(
        drained=tuple(drained),
        newly_ready=tuple(newly_ready),
        closed=tuple(closed),
    )


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #

def _fmt_anchor(s: ClusterSnapshot) -> str:
    return (
        f"`{s.representative}` "
        f"(`{s.representative_module}|0x{s.representative_addr:08x}`)"
    )


def render_markdown(
    diff: ClusterDiff,
    *,
    version: str,
    top_rows: int = 10,
) -> str:
    """Render the PR comment. Empty-diff case still emits the
    footer marker so brain can tell the workflow ran."""
    lines: list[str] = []
    lines.append("## 🧩 Pattern-cluster impact")
    lines.append("")

    n_drained = len(diff.drained)
    n_newly = len(diff.newly_ready)
    n_closed = len(diff.closed)

    if n_drained == 0 and n_newly == 0 and n_closed == 0:
        lines.append(
            f"_No pattern-cluster shifts on `{version}`. This PR "
            "doesn't drain any existing template family, open any "
            "new ones, or close any out._",
        )
        lines.append("")
        lines.append(FOOTER_MARKER)
        return "\n".join(lines)

    total_unmatched_drained = sum(
        before.unmatched_count - after.unmatched_count
        for before, after in diff.drained
    )
    total_closed_unmatched = sum(c.unmatched_count for c in diff.closed)

    summary_bits: list[str] = []
    if n_drained:
        summary_bits.append(
            f"drained **{total_unmatched_drained}** target(s) from "
            f"**{n_drained}** existing cluster(s)"
        )
    if n_newly:
        new_unmatched = sum(c.unmatched_count for c in diff.newly_ready)
        summary_bits.append(
            f"opened **{n_newly}** new cluster(s) "
            f"(**{new_unmatched}** newly-ready target(s))"
        )
    if n_closed:
        summary_bits.append(
            f"closed **{n_closed}** cluster(s) "
            f"(**{total_closed_unmatched}** target(s) consumed)"
        )
    lines.append(f"This PR {', '.join(summary_bits)}.")
    lines.append("")

    if diff.drained:
        lines.append(
            f"### Drained ({n_drained}) — existing cluster shrunk",
        )
        lines.append("")
        lines.append(
            "_Existing cluster anchors with fewer unmatched "
            "siblings — the PR matched some of them. Each "
            "remaining row is still a `propagate_template` "
            "candidate._",
        )
        lines.append("")
        lines.append(
            "| Anchor | Size | Sig | Unmatched (Δ) | Drainage |",
        )
        lines.append(
            "|--------|-----:|----:|---------------|---------:|",
        )
        for before, after in diff.drained[:top_rows]:
            delta = before.unmatched_count - after.unmatched_count
            pct = (
                100.0 * delta / before.unmatched_count
                if before.unmatched_count else 0.0
            )
            lines.append(
                f"| {_fmt_anchor(after)} | "
                f"`0x{after.size:x}` | {after.sig_len} | "
                f"{before.unmatched_count} → "
                f"{after.unmatched_count} (−{delta}) | "
                f"{pct:.0f}% |",
            )
        if n_drained > top_rows:
            lines.append("")
            lines.append(
                f"_(+{n_drained - top_rows} more drained "
                "cluster(s) truncated for readability.)_",
            )
        lines.append("")

    if diff.newly_ready:
        lines.append(
            f"### Newly-ready ({n_newly}) — first template landed",
        )
        lines.append("")
        lines.append(
            "_These clusters had no matched anchor on base. The "
            "PR added the first template, so they're now ready to "
            "propagate to the listed unmatched siblings._",
        )
        lines.append("")
        lines.append(
            "| Anchor | Size | Sig | Matched | Unmatched targets |",
        )
        lines.append(
            "|--------|-----:|----:|--------:|------------------:|",
        )
        for s in diff.newly_ready[:top_rows]:
            lines.append(
                f"| {_fmt_anchor(s)} | `0x{s.size:x}` | "
                f"{s.sig_len} | {s.matched_count} | "
                f"**{s.unmatched_count}** |",
            )
        if n_newly > top_rows:
            lines.append("")
            lines.append(
                f"_(+{n_newly - top_rows} more newly-ready "
                "cluster(s) truncated for readability.)_",
            )
        lines.append("")

    if diff.closed:
        lines.append(
            f"### Closed ({n_closed}) — fully consumed",
        )
        lines.append("")
        lines.append(
            "_All unmatched siblings of these clusters are now "
            "matched. They're done — remove from worklist._",
        )
        lines.append("")
        lines.append(
            "| Anchor | Size | Sig | Was unmatched |",
        )
        lines.append(
            "|--------|-----:|----:|--------------:|",
        )
        for s in diff.closed[:top_rows]:
            lines.append(
                f"| {_fmt_anchor(s)} | `0x{s.size:x}` | "
                f"{s.sig_len} | {s.unmatched_count} |",
            )
        if n_closed > top_rows:
            lines.append("")
            lines.append(
                f"_(+{n_closed - top_rows} more closed cluster(s) "
                "truncated for readability.)_",
            )
        lines.append("")

    lines.append(
        "<sub>Cluster model: functions sharing an exact "
        "`(size, reloc-signature)` fingerprint where ≥1 is matched "
        "and ≥1 is unmatched. Each row is a "
        "`tools/propagate_template.py` candidate.</sub>",
    )
    lines.append("")
    lines.append(FOOTER_MARKER)
    return "\n".join(lines)


def _empty_msg(version: str) -> str:
    """No-base placeholder so the upsert still produces a comment."""
    lines = [
        "## 🧩 Pattern-cluster impact",
        "",
        f"_No base-branch snapshot available; can't compute the "
        f"pattern-cluster diff for `{version}`. (Fork PR without "
        "history access, or base ref deleted.)_",
        "",
        FOOTER_MARKER,
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def main() -> int:
    # Force UTF-8 on stdout so the emoji header (🧩) survives on
    # Windows cp1252 consoles when the tool is run locally.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, io.UnsupportedOperation):
        pass

    ap = argparse.ArgumentParser(
        description=(
            "Render pattern-cluster drainage / newly-ready / "
            "closed diff as Markdown."
        ),
    )
    ap.add_argument(
        "--before-config", type=Path, required=True,
        help="Path to config/<ver>/ on the base branch.",
    )
    ap.add_argument(
        "--after-config", type=Path, required=True,
        help="Path to config/<ver>/ on the PR head.",
    )
    ap.add_argument(
        "-o", "--out", type=Path, default=None,
        help="Write Markdown to this path (default: stdout).",
    )
    ap.add_argument(
        "--top-rows", type=int, default=10,
        help="Top-N rows shown per section (default 10).",
    )
    ap.add_argument(
        "--version", default="eur",
        help="Version tag for the comment header (default eur).",
    )
    args = ap.parse_args()

    if not args.before_config.is_dir():
        print(
            f"warning: --before-config {args.before_config} "
            "is not a directory; emitting no-base placeholder.",
            file=sys.stderr,
        )
        md = _empty_msg(args.version)
        if args.out:
            args.out.write_text(md, encoding="utf-8")
        else:
            sys.stdout.write(md)
        return 0

    before_modules = load_all(args.before_config)
    after_modules = load_all(args.after_config)
    before_matched = collect_matched_ranges(args.before_config)
    after_matched = collect_matched_ranges(args.after_config)

    before_clusters = find_clusters(before_modules, before_matched)
    after_clusters = find_clusters(after_modules, after_matched)

    diff = diff_clusters(before_clusters, after_clusters)
    md = render_markdown(
        diff, version=args.version, top_rows=args.top_rows,
    )

    if args.out:
        args.out.write_text(md, encoding="utf-8")
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
