#!/usr/bin/env python3

"""
Regenerate docs/briefs/README.md from the briefs in the same directory.

A "brief" is a markdown file named `NNN-slug.md` whose first non-blank
line has the form `### <branch>/<slug>` and whose first paragraph
labelled `**Goal:**` describes what the brief covers.

Run after adding or editing a brief; commit the regenerated README
alongside the brief itself.

    python tools/generate_briefs_index.py
    # → writes docs/briefs/README.md

    python tools/generate_briefs_index.py --check
    # → exits non-zero if the committed index is out of date
    #   (suitable for CI gate)
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRIEFS_DIR = ROOT / "docs" / "briefs"
INDEX_PATH = BRIEFS_DIR / "README.md"

BRIEF_FILENAME_RE = re.compile(r"^(\d{3})-(.+)\.md$")
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$")
GOAL_LABEL = "**Goal:**"
GOAL_MAX_CHARS = 200


def _truncate_balanced(s: str, max_chars: int) -> str:
    """Truncate `s` to at most `max_chars` characters with `...`,
    walking back if needed so the result has balanced backtick code
    spans. Markdownlint's MD038 flags an unclosed backtick because
    it treats the rest of the line as an open code span; balanced
    truncation avoids the false alarm. Also drops any trailing `[`,
    `(`, or `_` so we don't leave a half-open markdown construct.

    Mirror of `tools/generate_research_index.py`'s helper of the same
    name; kept in sync by convention. If a third caller appears,
    factor into a shared module.
    """
    if len(s) <= max_chars:
        return s
    cut = max_chars - 3
    candidate = s[:cut].rstrip()
    while candidate and candidate.count("`") % 2 == 1:
        # Find the previous backtick and cut there. Drop the trailing
        # backtick too — that leaves a clean closing-backtick boundary.
        last = candidate.rfind("`")
        if last < 0:
            break
        candidate = candidate[:last].rstrip()
    while candidate and candidate[-1] in "[(_":
        candidate = candidate[:-1].rstrip()
    return candidate + "..."


def parse_brief(path: Path) -> dict | None:
    m = BRIEF_FILENAME_RE.match(path.name)
    if not m:
        return None
    number, slug = m.group(1), m.group(2)

    heading = ""
    goal = ""
    in_goal = False
    goal_lines: list[str] = []

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not heading:
            hm = HEADING_RE.match(line)
            if hm:
                heading = hm.group(1)
                continue
        if not in_goal:
            if line.startswith(GOAL_LABEL):
                in_goal = True
                rest = line[len(GOAL_LABEL):].strip()
                if rest:
                    goal_lines.append(rest)
            continue
        # In goal block: stop at the first blank line.
        if not line.strip():
            break
        goal_lines.append(line.strip())

    goal = " ".join(goal_lines).strip()
    return {
        "number": number,
        "slug": slug,
        "heading": heading or f"{number}-{slug}",
        "goal": goal,
        "filename": path.name,
    }


def render_index(briefs: list[dict]) -> str:
    lines = [
        "# Decomp Briefs",
        "",
        "Short, scoped task descriptions for individual decomp efforts.",
        "Each brief lives in its own file; this index is auto-generated by",
        "[`tools/generate_briefs_index.py`](../../tools/generate_briefs_index.py).",
        "",
        "> Run `python tools/generate_briefs_index.py` after adding or",
        "> editing a brief, and commit the regenerated `README.md` alongside.",
        "",
        "## Briefs",
        "",
        "| #   | Brief | Goal |",
        "|-----|-------|------|",
    ]
    for b in briefs:
        # Markdown table cells: collapse pipes and newlines, trim length.
        # `_truncate_balanced` keeps backtick code spans paired so the
        # rendered output passes MD038 even when the cut-point lands
        # inside a `code-span`.
        goal = b["goal"].replace("|", "\\|").replace("\n", " ")
        goal = _truncate_balanced(goal, GOAL_MAX_CHARS)
        link = f"[`{b['heading']}`]({b['filename']})"
        lines.append(f"| {b['number']} | {link} | {goal} |")

    lines += [
        "",
        "## Adding a new brief",
        "",
        "1. Create `docs/briefs/NNN-slug.md` with the next number.",
        "2. First line: `### <branch>/<slug>` (matches the working branch name).",
        "3. First paragraph after the heading: `**Goal:** ...` — one or two",
        "   sentences describing what success looks like.",
        "4. `python tools/generate_briefs_index.py` to refresh this file.",
        "5. Commit both the new brief and the updated `README.md`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Regenerate docs/briefs/README.md.",
    )
    ap.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if the committed index is out of date. "
             "For CI use.",
    )
    args = ap.parse_args()

    briefs: list[dict] = []
    for path in sorted(BRIEFS_DIR.glob("*.md")):
        if path.name == "README.md":
            continue
        parsed = parse_brief(path)
        if parsed is None:
            print(f"warning: skipping {path.name} (filename doesn't match NNN-slug.md)",
                  file=sys.stderr)
            continue
        briefs.append(parsed)

    if not briefs:
        print("no briefs found in docs/briefs/", file=sys.stderr)
        return 1

    rendered = render_index(briefs)

    if args.check:
        existing = (
            INDEX_PATH.read_text(encoding="utf-8")
            if INDEX_PATH.is_file() else ""
        )
        if existing != rendered:
            print(
                f"error: {INDEX_PATH.relative_to(ROOT)} is out of "
                "date. Re-run `python tools/generate_briefs_index.py` "
                "and commit.",
                file=sys.stderr,
            )
            return 1
        print(f"{INDEX_PATH.relative_to(ROOT)} is current.")
        return 0

    if INDEX_PATH.exists() and INDEX_PATH.read_text(encoding="utf-8") == rendered:
        print(f"{INDEX_PATH.relative_to(ROOT)} already up to date.")
        return 0

    INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(ROOT)} ({len(briefs)} briefs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
