#!/usr/bin/env python3
"""Generate a navigable index for the codegen wall catalog."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "docs/research/codegen-walls.md"
OUT = ROOT / "docs/research/codegen-walls-index.md"
HEADING_RE = re.compile(
    r"^### (?P<key>[PC]-\d+)\.\s+(?P<title>.+?)\s*$", re.MULTILINE,
)
# A wall's own section ends at the next level-3 heading of ANY shape, not just
# the next formal `### P-N.`/`### C-N.` one. The catalog has plenty of other
# `###` headings between two formal wall entries (compound sub-entries like
# `### P-20-mode-switch-selector.`, unrelated appendix sections like `### BR-1.`
# or `### T-3.`) -- HEADING_RE alone is blind to all of them, so a section's
# `end` used to fall through to the NEXT formal heading, silently sweeping
# every intervening heading's own content (including its own "Affected
# picks/drops" bracket) into the prior wall's count. Confirmed real: P-49's
# true section ends 26 lines after its own heading, but the next `[PC]-\d+`
# heading HEADING_RE recognises is ~1,800 lines later, past an entire
# unrelated "Band ship-rate closures" appendix (BR-1..BR-9, OQ-1, E-1..E-3,
# T-1..T-4, S-1, S-2). Deliberately excludes `####`+ headings (the required
# `[ \t]` right after the third `#` fails to match a fourth `#`), and content
# inside fenced code blocks never starts a line with `### ` in this document
# (verified against the current catalog) so this doesn't need fence-tracking.
ANY_HEADING_RE = re.compile(r"^###[ \t]+\S.*$", re.MULTILINE)
STATUS_RE = re.compile(r"^\| (?P<key>[PC]-\d+) \| (?P<status>[^|]+) \|", re.MULTILINE)


@dataclass(frozen=True)
class WallEntry:
    key: str
    status: str
    member_count: str
    symptom: str
    line: int


def _status(value: str) -> str:
    upper = value.strip().upper()
    if "RETIRED" in upper:
        return "RETIRED"
    if "UNDER" in upper:
        return "UNDER RECONSIDERATION"
    if "TENTATIVE" in upper:
        return "LIVE (tentative)"
    return "LIVE"


def _member_count(section: str) -> str:
    explicit = [
        int(value)
        for value in re.findall(
            r"\*\*Affected (?:picks|drops) \((\d+)[^)]*\):\*\*", section,
        )
    ]
    if explicit:
        return str(sum(explicit))
    blocks = re.findall(
        r"\*\*Affected (?:picks|drops)[^:]*:\*\*(.*?)(?=\n\n|\n\*\*|\n###|\Z)",
        section,
        re.DOTALL,
    )
    if not blocks:
        members = re.findall(r"Falsified on (\d+) members?", section)
        return members[-1] if members else "n/a"
    tokens = set()
    for block in blocks:
        tokens.update(re.findall(r"(?:func_|data_)?(?:0x)?[0-9a-fA-F]{8}", block))
    return str(len(tokens)) if tokens else "n/a"


def parse_catalog(text: str) -> list[WallEntry]:
    status_by_key = {
        match.group("key"): _status(match.group("status"))
        for match in STATUS_RE.finditer(text)
    }
    headings = list(HEADING_RE.finditer(text))
    boundary_starts = [match.start() for match in ANY_HEADING_RE.finditer(text)]
    entries: list[WallEntry] = []
    for heading in headings:
        start = heading.start()
        end = next((pos for pos in boundary_starts if pos > start), len(text))
        section = text[start:end]
        key = heading.group("key")
        entries.append(WallEntry(
            key=key,
            status=status_by_key.get(key, "LIVE"),
            member_count=_member_count(section),
            symptom=heading.group("title"),
            line=text.count("\n", 0, start) + 1,
        ))
    return entries


def render(text: str) -> str:
    entries = parse_catalog(text)
    lines = [
        "<!-- GENERATED by tools/generate_walls_index.py — do not edit by hand. -->",
        "",
        "# Codegen walls index",
        "",
        "Generated from [`codegen-walls.md`](codegen-walls.md). Run `python "
        "tools/generate_walls_index.py` after catalog edits; CI uses `--check`.",
        "",
        "| Wall | Status | Members | Symptom | Catalog line |",
        "| --- | --- | ---: | --- | ---: |",
    ]
    lines.extend(
        f"| [{entry.key}](codegen-walls.md# {entry.key.lower()}) | {entry.status} | "
        f"{entry.member_count} | {entry.symptom} | {entry.line} |".replace("# ", "#")
        for entry in entries
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the index is stale")
    parser.add_argument("--catalog", type=Path, default=CATALOG)
    parser.add_argument("--output", type=Path, default=OUT)
    args = parser.parse_args(argv)
    generated = render(args.catalog.read_text(encoding="utf-8"))
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != generated:
            print(f"{args.output} is out of date; regenerate it", file=sys.stderr)
            return 1
        print(f"{args.output} is current.")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    print(f"wrote {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
