#!/usr/bin/env python3
"""
generate_state_table.py — regenerate docs/state-table.md, the committed
snapshot of "where the project actually is".

Why this exists: the same handful of numbers — per-region readable-C, the
remaining-candidate pools by size band, the data-typing metrics — get re-derived
by hand every round, by the brain and by every campaign wave. Every wave of the
data campaign found the count it had been handed was wrong, and at least one
round's dispatch was planned around a stale figure. Hand-derivation is also
error-prone in a specific, repeatable way: a naive delinks.txt parser attributes
the module-wide section map to whichever TU block preceded it, which inflates
"shipped bytes" to ~99% of the ROM. That mistake has been made.

So this tool derives everything from `tools/progress.py`'s OWN parser
(`parse_delinks_file`, `summarize_delinks`, `summarize_data_readability`) rather
than reimplementing it. Whatever the real metric counts, this table counts —
they cannot drift apart, because there is only one implementation.

Committed output + `--check` means the generated-files drift gate keeps the
table honest: a PR that moves the numbers and forgets to regenerate fails CI,
exactly like the tools/briefs/research indexes.

Reads only committed files (`config/<region>/**/delinks.txt`). No build, no
baserom, no toolchain — runs anywhere, in seconds.

Usage:
    python3.13 tools/generate_state_table.py            # rewrite docs/state-table.md
    python3.13 tools/generate_state_table.py --check    # exit 1 if stale
    python3.13 tools/generate_state_table.py --stdout   # print, don't write

Exit codes:
    0   written, or --check found it current
    1   --check found it stale (regenerate and commit)
    2   usage / IO error
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import progress  # noqa: E402

OUT = ROOT / "docs" / "state-table.md"
REGIONS = ("eur", "usa", "jpn")

# Bands chosen to match how the sweeps are actually dispatched, so the table
# answers "which band should the next round take" without re-bucketing.
BANDS = ((1, 148), (149, 256), (257, 512), (513, 1023), (1024, 2047), (2048, 1 << 30))


def _band_rows(config_dir: Path) -> tuple[list[dict], int, int]:
    """(rows, shipped_total_bytes, remaining_total_bytes) by .text size band.

    A TU counts as SHIPPED when its source is a `.c`/`.cpp` file and REMAINING
    when it is `.s`. Gap TUs (`_dsd_gap@...`) are neither — they are unassigned
    filler, not candidates — so they are excluded from both.
    """
    done: list[int] = []
    todo: list[int] = []
    for _module, path in progress._discover_module_delinks(config_dir):
        _sections, tus = progress.parse_delinks_file(path)
        for tu in tus:
            src = tu.get("source") or ""
            if src.startswith("_dsd_gap@"):
                continue
            text = next((s for s in tu.get("sections") or [] if s[0] == ".text"), None)
            if not text:
                continue
            size = text[2] - text[1]
            if size <= 0:
                continue
            (done if src.endswith((".c", ".cpp")) else todo).append(size)

    rows = []
    for lo, hi in BANDS:
        d = [n for n in done if lo <= n <= hi]
        t = [n for n in todo if lo <= n <= hi]
        rows.append({
            "band": f"{lo}–{hi}" if hi < (1 << 30) else f"{lo}+",
            "done": len(d),
            "todo": len(t),
            "done_pct": (100 * len(d) / (len(d) + len(t))) if (d or t) else 0.0,
            "todo_bytes": sum(t),
            "mean_todo": (sum(t) // len(t)) if t else 0,
        })
    return rows, sum(done), sum(todo)


def render() -> str:
    lines: list[str] = []
    add = lines.append
    add("<!-- GENERATED by tools/generate_state_table.py — do not edit by hand. -->")
    add("<!-- Regenerate after any merge that moves the numbers; `--check` gates it. -->")
    add("")
    add("# Project state table")
    add("")
    add("Derived from `config/<region>/**/delinks.txt` via `tools/progress.py`'s own")
    add("parser, so these figures cannot drift from the real metric. Re-derive rather")
    add("than inherit: every campaign wave that trusted a handed-down count found it wrong.")
    add("")

    add("## Readable C by region")
    add("")
    add("`natural-C` is hand-written readable C — the headline figure, and the one to")
    add("quote. `asm-C` is inline-asm coverage hygiene, counted separately on purpose.")
    add("`C-decompiled` is their sum; do not conflate it with natural-C.")
    add("")
    add("| region | natural-C | natural-C % | asm-C | C-decompiled % |")
    add("| --- | ---: | ---: | ---: | ---: |")
    for region in REGIONS:
        cfg = ROOT / "config" / region
        if not cfg.is_dir():
            continue
        total = progress.c_code_total_bytes(cfg)
        split = progress.c_code_bytes_by_class(cfg)
        nat, asm = split.get("natural-c", 0), split.get("asm-c", 0)
        nat_pct = (100 * nat / total) if total else 0.0
        both_pct = (100 * (nat + asm) / total) if total else 0.0
        add(f"| {region} | {nat:,} | **{nat_pct:.2f}%** | {asm:,} | {both_pct:.2f}% |")
    add("")

    eur = ROOT / "config" / "eur"
    rows, shipped, remaining = _band_rows(eur)
    denom = progress.c_code_total_bytes(eur) or 1

    add("## EUR candidates by function size")
    add("")
    add("`done` = matched as C. `todo` = still `.s`. Gap TUs excluded (not candidates).")
    add("`remaining pp` is that band's share of the whole `.text` denominator — i.e. how")
    add("much of the project is still locked in functions of that size.")
    add("")
    add("| size (bytes) | done | todo | done % | remaining pp | mean todo |")
    add("| --- | ---: | ---: | ---: | ---: | ---: |")
    for r in rows:
        add(f"| {r['band']} | {r['done']:,} | {r['todo']:,} | {r['done_pct']:.1f}% "
            f"| {100 * r['todo_bytes'] / denom:.2f} | {r['mean_todo']:,} |")
    add(f"| **total** | **{sum(r['done'] for r in rows):,}** "
        f"| **{sum(r['todo'] for r in rows):,}** | | "
        f"**{100 * remaining / denom:.2f}** | |")
    add("")
    add(f"Shipped `.text`: {shipped:,} B · remaining `.text`: {remaining:,} B "
        f"· denominator: {denom:,} B")
    add("")

    add("## EUR data typing")
    add("")
    data = progress.summarize_data_readability(eur)
    total_data = data.get("data_total_bytes") or 0
    add("| metric | bytes | of data bytes |")
    add("| --- | ---: | ---: |")
    for key, label in (("typed_array_bytes", "Typed-array"),
                       ("named_struct_bytes", "Named-struct")):
        v = data.get(key) or 0
        pct = (100 * v / total_data) if total_data else 0.0
        add(f"| {label} | {v:,} | {pct:.2f}% |")
    add(f"| *(total data bytes)* | {total_data:,} | |")
    add("")
    add("`Typed-array` counts any file-scope array declaration, including opaque")
    add("`unsigned char[N]` carve placeholders — it is a coverage metric, not a")
    add("correctness one. `Named-struct` excludes primitive-typed arrays by design.")
    add("Read `summarize_data_readability` before reasoning about either.")
    add("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate docs/state-table.md.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed table is stale")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args(argv)

    try:
        text = render()
    except Exception as exc:  # noqa: BLE001 - report, don't half-write
        print(f"generate_state_table: could not derive state: {exc}", file=sys.stderr)
        return 2

    if args.stdout:
        print(text, end="")
        return 0

    if args.check:
        if not OUT.is_file():
            print(f"{OUT} is missing. Run `python tools/generate_state_table.py`.",
                  file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT} is out of date. Re-run "
                  f"`python tools/generate_state_table.py` and commit.", file=sys.stderr)
            return 1
        print(f"{OUT} is current.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
