#!/usr/bin/env python3
"""
protected_paths.py — the paths no agent may edit, and the Codex hook that
enforces them.

One list, two enforcers (rounds 004 and 005):

  * Claude Code: `.claude/settings.json` has `permissions.deny` rules
    `Edit(/<pattern>)` per pattern below, and `Edit(/.worktrees/*/<pattern>)`
    beside each, so a session started in the primary checkout is denied the
    same paths inside a seat's worktree (`claude_rules()` writes the list; a
    test keeps the file in step). Claude Code applies a rule to its own file
    tools, to the file commands it recognises in Bash and to Bash
    redirections, in every permission mode. Which Bash forms are checked
    depends on the version: the permissions page says input redirects from
    v2.1.257 and `tee` targets from v2.1.269, so `... | tee build.ninja` is
    not checked before that.
  * Codex CLI: `.codex/hooks.json` runs `protected_paths.py --codex-hook` as a
    PreToolUse hook on `apply_patch`. It reads the hook's JSON from stdin and
    denies a patch that adds, updates, deletes or moves a protected path,
    including one under `.worktrees/<seat>/`. Not observed inside Codex.

Neither stops a program the agent runs that writes files itself (a Python
script, `ninja`, `git checkout`): the build must keep writing `build/` and
friends, so that is by design, and the reason the three-ROM SHA-1 stays the
proof. `tests/test_protected_paths.py` keeps the two settings files in step
with this list.

Patterns are relative to the repository root, `/`-separated; `*` matches
within one path segment and `**` across segments. Plain Python 3.9+, no
third-party imports: the hook runs under whatever `python3` / `python` the
agent's machine has.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Why each one is protected is in the comment beside it.
PATTERNS = (
    "**/*.sha1",                  # the checksums the ROM is proved against
    "orig/**",                    # the owner's original dumps
    "**/*.nds",                   # ROMs, original or rebuilt
    "**/*bios.bin",               # BIOS dumps
    "build/**",                   # generated by ninja
    "extract/**",                 # generated by dsd rom extract
    "build.ninja",                # generated by configure.py
    "objdiff.json",               # generated by configure.py / ninja objdiff
    ".ninja_log",                 # ninja's own state
    ".ninja_lock",
    "config/*/arm9/config.yaml",  # dsd's module config; AGENTS.md: never hand-edit
    "dsd",                        # downloaded tool binaries
    "dsd.exe",
    "objdiff-cli",
    "objdiff-cli.exe",
    "wibo",
    "ninja.exe",
    "tools/mwccarm/**",
    "tools/arm-none-eabi/**",
    "tools/_dl/**",
    ".claude/settings.json",      # the enforcers themselves
    ".codex/hooks.json",
    "tools/protected_paths.py",
    "tools/reference_baseline.txt",   # the tolerated findings may only shrink
    "tools/fake_match_baseline.txt",
)

WORKTREES = ".worktrees"  # seats work in .worktrees/<role>-<round>, inside the primary checkout


def claude_rules() -> list[str]:
    """The `permissions.deny` rules for `.claude/settings.json`.

    A `/` rule is anchored at the directory the session starts in. Started in
    a worktree that is the worktree; started in the primary checkout, the
    worktree is `.worktrees/<seat>/`, so each pattern gets a second rule there.
    A `**/` pattern already reaches into it.
    """
    rules = [f"Edit(/{p})" for p in PATTERNS]
    rules += [f"Edit(/{WORKTREES}/*/{p})" for p in PATTERNS if not p.startswith("**/")]
    return rules


def _inside_worktree(rel: str) -> str | None:
    """`.worktrees/<seat>/x/y` -> `x/y`; None for a path outside any worktree."""
    parts = rel.split("/")
    if len(parts) > 2 and parts[0] == WORKTREES:
        return "/".join(parts[2:])
    return None


def _pattern_regex(pattern: str) -> re.Pattern[str]:
    out = []
    i = 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        elif pattern[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return re.compile("".join(out) + r"\Z")


_REGEXES = tuple((p, _pattern_regex(p)) for p in PATTERNS)


def repo_relative(path: str, *, root: Path = ROOT, cwd: Path | None = None) -> str | None:
    """Return `path` relative to the repository root, or None if outside it."""
    candidate = Path(path.strip().strip('"').strip("'"))
    if not candidate.is_absolute():
        candidate = (cwd or Path.cwd()) / candidate
    normalised = Path(os.path.normpath(str(candidate)))
    try:
        rel = normalised.relative_to(Path(os.path.normpath(str(root))))
    except ValueError:
        return None
    return rel.as_posix()


def protected_pattern(path: str, *, root: Path = ROOT, cwd: Path | None = None) -> str | None:
    """Return the pattern protecting `path`, or None."""
    rel = repo_relative(path, root=root, cwd=cwd)
    if rel is None or rel in ("", "."):
        return None
    forms = [rel]
    if os.sep == "\\" or sys.platform == "darwin":
        forms.append(rel.lower())  # case-insensitive file systems
    candidates = list(forms)
    candidates += [inner for f in forms if (inner := _inside_worktree(f)) is not None]
    return next((p for p, rx in _REGEXES if any(rx.match(c) for c in candidates)), None)


_PATCH_PATH_RE = re.compile(
    r"^\*\*\* (?:Add File|Update File|Delete File|Move to):\s*(.+?)\s*$", re.MULTILINE
)


def patch_paths(patch: str) -> list[str]:
    """Every path an `apply_patch` envelope adds, updates, deletes or moves to."""
    return [m.group(1) for m in _PATCH_PATH_RE.finditer(patch)]


def _strings(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        return [s for v in value.values() for s in _strings(v)]
    if isinstance(value, list):
        return [s for v in value for s in _strings(v)]
    return []


def codex_hook(payload: dict, *, root: Path = ROOT) -> str | None:
    """Return a denial reason for a Codex PreToolUse payload, or None to allow."""
    tool_input = payload.get("tool_input", payload)
    cwd = Path(payload["cwd"]) if isinstance(payload.get("cwd"), str) else None
    paths = [p for text in _strings(tool_input) for p in patch_paths(text)]
    if isinstance(tool_input, dict):
        for key in ("file_path", "path"):
            if isinstance(tool_input.get(key), str):
                paths.append(tool_input[key])
    for path in paths:
        pattern = protected_pattern(path, root=root, cwd=cwd)
        if pattern is not None:
            return (f"{path} is protected ({pattern}); see tools/protected_paths.py. "
                    "Checksums, original ROMs and generated files are never edited by hand.")
    return None


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if args == ["--codex-hook"]:
        try:
            payload = json.load(sys.stdin)
        except (ValueError, OSError) as exc:
            print(f"protected_paths: unreadable hook input ({exc}); denying", file=sys.stderr)
            return 2
        reason = codex_hook(payload if isinstance(payload, dict) else {})
        if reason is None:
            return 0
        print(reason, file=sys.stderr)  # Codex: exit 2 + stderr blocks the call
        return 2
    if args and args[0] == "--check":
        hits = [(p, protected_pattern(p)) for p in args[1:]]
        for path, pattern in hits:
            print(f"{path}: {'PROTECTED by ' + pattern if pattern else 'not protected'}")
        return 1 if any(pattern for _, pattern in hits) else 0
    print("usage: protected_paths.py --codex-hook < payload.json | --check PATH...",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
