; Cluster C Pattern 3 chunk — brief 125 generator output.
;
; Module: ov006
; Range:  0x021ce9e4..0x021cea0c (40 bytes, 2 symbols)
; Generated by tools/cluster_c_pattern3_gen.py

        .section .data

        .global data_ov006_021ce9e4
data_ov006_021ce9e4:
        .byte 0x0c, 0x08, 0x04, 0x0b, 0x07, 0x03, 0x0a, 0x06
        .byte 0x02, 0x09, 0x05, 0x01

        .global data_ov006_021ce9f0
data_ov006_021ce9f0:
        .ascii "#ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        .byte 0x00
